-- ============================================================
-- IMPORT — FRA_orthographe | PFEQ-FRA-SEC1-ORTH
-- À exécuter dans Supabase → SQL Editor → Run
-- ============================================================
BEGIN;

-- SEC1_FRA_orthographe.sql (63 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-FRA-SEC1-ORTH') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Homophone a vs à', 1, 20000, '« a » = verbe avoir conjugué (il a). « à » = préposition (on peut remplacer par « avait » ; si ça marche, c''est « a »).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il a faim à midi.","Il à faim a midi.","Il a faim a midi.","Il à faim à midi."],"answer":"Il a faim à midi."}'),
('Homophone et vs est', 1, 20000, '« est » = verbe être (il est). « et » = conjonction de coordination (on peut remplacer par « et puis »).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il est grand et fort.","Il est grand est fort.","Il et grand est fort.","Il et grand et fort."],"answer":"Il est grand et fort."}'),
('Homophone son vs sont', 1, 20000, '« sont » = verbe être au pluriel (on peut remplacer par « étaient »). « son » = déterminant possessif.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Ils son contents.","Ils sont contents.","Son frère sont là.","Ils sont content."],"answer":"Ils sont contents."}'),
('Homophone on vs ont', 1, 20000, '« ont » = verbe avoir (ils ont). « on » = pronom sujet (remplaçable par « il »).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["On a mangé, ils on dormi.","On a mangé, ils ont dormi.","Ont a mangé, ils ont dormi.","On a mangé, ils on dormi."],"answer":"On a mangé, ils ont dormi."}'),
('Homophone ou vs où', 1, 20000, '« ou » = conjonction (ou bien). « où » = pronom/adverbe de lieu (on peut remplacer par « là où »).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Où vas-tu ou restes-tu ?","Ou vas-tu où restes-tu ?","Où vas-tu ou restes-tu ?","Ou vas-tu ou restes-tu ?"],"answer":"Où vas-tu ou restes-tu ?"}'),
('Homophone ces vs ses vs c''est vs s''est', 1, 25000, '« ses » = déterminant possessif (les siens). « ces » = déterminant démonstratif (ceux-là).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Ces livres sont ses préférés.","Ses livres sont ces préférés.","Ces livres sont ces préférés.","Ses livres sont ses préférés."],"answer":"Ces livres sont ses préférés."}'),
('Homophone c''est vs s''est', 1, 25000, '« c''est » = ce + est. « s''est » = pronom se + est (verbe pronominal passé composé).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["C''est lui qui s''est blessé.","S''est lui qui c''est blessé.","C''est lui qui c''est blessé.","S''est lui qui s''est blessé."],"answer":"C''est lui qui s''est blessé."}'),
('Homophone mais vs mes', 1, 20000, '« mais » = conjonction d''opposition. « mes » = déterminant possessif 1re pers. pluriel.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["J''aime mes amis mais pas mes ennemis.","J''aime mais amis mes pas mes ennemis.","J''aime mes amis mes pas mes ennemis.","J''aime mais amis mais pas mes ennemis."],"answer":"J''aime mes amis mais pas mes ennemis."}'),
('Homophone ni vs n''y', 1, 25000, '« ni » = conjonction de coordination négative. « n''y » = adverbe de lieu négatif.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il n''y a ni pain ni lait.","Il ni a n''y pain n''y lait.","Il n''y a ni pain n''y lait.","Il ni a ni pain ni lait."],"answer":"Il n''y a ni pain ni lait."}'),
('Homophone leur vs leurs', 1, 20000, '« leur » invariable = pronom (je leur parle). « leurs » variable = déterminant possessif (leurs livres).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Je leur ai donné leurs livres.","Je leurs ai donné leur livres.","Je leur ai donné leur livres.","Je leurs ai donné leurs livres."],"answer":"Je leur ai donné leurs livres."}'),
('Homophone tout vs tous', 1, 25000, '« tous » adjectif ou pronom (tous les élèves, ils sont tous là). « tout » adverbe (invariable, = très).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Tous les élèves sont tout contents.","Tous les élèves sont tous contents.","Tout les élèves sont tout contents.","Tout les élèves sont tous contents."],"answer":"Tous les élèves sont tout contents."}'),
('Accord pluriel des noms en -al', 1, 20000, 'Les noms en -al font généralement leur pluriel en -aux (cheval → chevaux, journal → journaux).',
 '{"type":"mcq","question":"Quel est le pluriel de « animal » ?","options":["animals","animaux","animeaux","animals"],"answer":"animaux"}'),
('Accord pluriel des noms en -ou', 1, 20000, 'La plupart des noms en -ou prennent -s. Mais : bijou, caillou, chou, genou, hibou, joujou, pou → -oux.',
 '{"type":"mcq","question":"Quel est le pluriel de « genou » ?","options":["genous","genoux","genouds","genous"],"answer":"genoux"}'),
('Féminin des adjectifs — doublement de consonne', 1, 20000, 'Certains adjectifs doublent leur consonne finale au féminin : bon → bonne, gros → grosse, ancien → ancienne.',
 '{"type":"mcq","question":"Quel est le féminin de l''adjectif « ancien » ?","options":["anciene","ancienne","ancièn","anciens"],"answer":"ancienne"}'),
('Féminin adjectifs en -eux', 1, 20000, 'Les adjectifs en -eux font leur féminin en -euse (heureux → heureuse, joyeux → joyeuse).',
 '{"type":"mcq","question":"Quel est le féminin de l''adjectif « heureux » ?","options":["heureuse","heureuxe","heureuse","heureusse"],"answer":"heureuse"}'),
('Féminin des noms — métiers', 1, 20000, 'On forme souvent le féminin des métiers en ajoutant -e ou en changeant la terminaison : directeur → directrice.',
 '{"type":"mcq","question":"Quel est le féminin du mot « directeur » ?","options":["directrice","directeure","directeuse","directère"],"answer":"directrice"}'),
('Accord sujet-verbe avec plusieurs sujets', 1, 25000, 'Quand il y a plusieurs sujets, le verbe se met au pluriel.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Pierre et Marie arrive.","Pierre et Marie arrivent.","Pierre et Marie arrivons.","Pierre et Marie arrivez."],"answer":"Pierre et Marie arrivent."}'),
('Accord de l''adjectif au pluriel', 1, 20000, 'L''adjectif s''accorde en genre et en nombre avec le nom. Nom pluriel → adjectif + -s.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Des fleurs rouge.","Des fleurs rouges.","Des fleurs rouges.","Des fleur rouge."],"answer":"Des fleurs rouges."}'),
('Homophone quand vs quant vs qu''en', 1, 25000, '« quand » = conjonction de temps. « quant à » = pour ce qui concerne. « qu''en » = que + en.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Quand arriveras-tu ? Quant à moi, je pars.","Quant arriveras-tu ? Quand à moi, je pars.","Quand arriveras-tu ? Quand à moi, je pars.","Quant arriveras-tu ? Quant à moi, je pars."],"answer":"Quand arriveras-tu ? Quant à moi, je pars."}'),
('Trait d''union — nombres', 1, 20000, 'On met un trait d''union entre les dizaines et les unités : vingt-deux, trente-cinq, soixante-dix.',
 '{"type":"mcq","question":"Laquelle de ces graphies est correcte ?","options":["vingt deux","vingt-deux","vingtdeux","vingts-deux"],"answer":"vingt-deux"}'),
('Majuscule en début de phrase', 1, 15000, 'Toute phrase commence par une majuscule et se termine par un point (. ! ?).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correctement commencée ?","options":["le chat dort.","Le chat dort.","LE chat dort.","le Chat dort."],"answer":"Le chat dort."}'),
('Accord PP avec avoir — pas de CD', 1, 25000, 'Avec avoir, si le CD est placé APRÈS le verbe, le PP ne s''accorde pas.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle a mangées des fruits.","Elle a mangé des fruits.","Elle a mangés des fruits.","Elle a mangée des fruits."],"answer":"Elle a mangé des fruits."}'),
('Homophone peu vs peux vs peut', 1, 25000, '« peu » = adverbe (petite quantité). « peux » = verbe pouvoir 1re/2e pers. « peut » = verbe pouvoir 3e pers.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il peut manger un peu.","Il peux manger un peu.","Il peu manger un peu.","Il peut manger un peux."],"answer":"Il peut manger un peu."}'),
('Homophone -é vs -er', 1, 25000, 'Après un verbe conjugué, on utilise l''infinitif (-er), pas le participe (-é). Exception : après être ou avoir.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il veut manger.","Il veut mangé.","Il veut mangée.","Il veut manges."],"answer":"Il veut manger."}'),
('Participe passé vs infinitif', 1, 25000, 'Si on peut remplacer le verbe par « vendre » (infinitif), c''est -er. Si on peut remplacer par « vendu » (participe), c''est -é.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle a décidé de partir.","Elle a décider de partir.","Elle a décidée de partir.","Elle a décider de partie."],"answer":"Elle a décidé de partir."}'),
('Accord adjectif de couleur', 1, 25000, 'Les adjectifs de couleur s''accordent sauf quand ils sont composés ou qu''ils proviennent d''un nom (marron, orange, kaki).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Des robes orange et des sacs marrons.","Des robes oranges et des sacs marron.","Des robes orange et des sacs marron.","Des robes oranges et des sacs marrons."],"answer":"Des robes orange et des sacs marron."}'),
('Accord de quel vs qu''elle', 1, 25000, '« quel » (adj. interrogatif) s''accorde avec le nom. « qu''elle » = que + elle (pronom + conjonction).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Quelle belle journée ! Je suis content qu''elle soit là.","Qu''elle belle journée ! Je suis content quel soit là.","Quelle belle journée ! Je suis content quel soit là.","Qu''elle belle journée ! Je suis content qu''elle soit là."],"answer":"Quelle belle journée ! Je suis content qu''elle soit là."}'),
('Accord après « c''est »', 1, 25000, '« c''est » + adjectif → adjectif au masculin singulier (invariable). « ils sont » → accord normal.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["C''est beaux ces fleurs.","C''est belles ces fleurs.","C''est beau, ces fleurs.","Ce sont beau, ces fleurs."],"answer":"C''est beau, ces fleurs."}'),
('Homophone sans vs s''en', 1, 25000, '« sans » = préposition (privation). « s''en » = pronom se + pronom en (elle s''en va).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il part sans rien dire et s''en va.","Il part s''en rien dire et sans va.","Il part sans rien dire et sans va.","Il part s''en rien dire et s''en va."],"answer":"Il part sans rien dire et s''en va."}'),
('Accent grave — là vs la', 1, 20000, '« là » (avec accent) = adverbe de lieu (ici/là). « la » = déterminant ou pronom.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["La fille est la, regarde-la.","La fille est là, regarde-la.","Là fille est là, regarde-la.","La fille est la, regarde-là."],"answer":"La fille est là, regarde-la."}'),
('Deux points et majuscule', 1, 20000, 'Après les deux points, on ne met pas de majuscule sauf si ce qui suit est un nom propre ou une citation (discours direct).',
 '{"type":"mcq","question":"Laquelle utilise correctement les deux points ?","options":["Il a dit : \"Bonne nuit.\"","Il a dit : bonne nuit.","Il a dit: \"Bonne nuit.\"","Il a dit; \"Bonne nuit.\""],"answer":"Il a dit : \"Bonne nuit.\""}'),
('Accord du PP — être', 1, 25000, 'Avec être, le PP s''accorde avec le sujet en genre et en nombre.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Ils sont partis hier.","Ils sont partie hier.","Ils sont parties hier.","Ils sont partis hier."],"answer":"Ils sont partis hier."}'),
('Homophone davantage vs d''avantage', 2, 35000, '« davantage » = adverbe (plus). « d''avantage(s) » = de + avantage(s) (un nom).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il gagne davantage de points.","Il gagne d''avantage de points.","Il gagne davantage des points.","Il gagne d''avantages de points."],"answer":"Il gagne davantage de points."}'),
('Accord de TOUT', 2, 40000, '« tout » adverbe devant adjectif féminin commençant par consonne ou H aspiré s''accorde (toute, toutes). Devant voyelle, il reste invariable.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle est toute contente.","Elle est tout contente.","Elle est touts contente.","Elle est toutes contente."],"answer":"Elle est toute contente."}'),
('Ne… que (restriction)', 2, 35000, '« ne… que » exprime une restriction (seulement). Différent de la négation ne… pas.',
 '{"type":"mcq","question":"Laquelle de ces phrases exprime la restriction ?","options":["Il ne mange pas de légumes.","Il ne mange que des légumes.","Il ne mange ni légumes.","Il ne mange jamais de légumes."],"answer":"Il ne mange que des légumes."}'),
('PP après un pronom relatif', 2, 40000, 'Si le pronom relatif « que » est CD et précède le PP (auxiliaire avoir), le PP s''accorde.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["La robe que j''ai acheté est belle.","La robe que j''ai achetée est belle.","La robe que j''ai acheté est belles.","La robe que j''ai achetées est belle."],"answer":"La robe que j''ai achetée est belle."}'),
('Accord adjectif — épithète détachée', 2, 40000, 'L''adjectif épithète détachée (mis en apposition) s''accorde avec le nom auquel il se rapporte.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Fatiguée, Marie s''est couchée tôt.","Fatigué, Marie s''est couchée tôt.","Fatiguée, Marie s''est coucher tôt.","Fatiguées, Marie s''est couchée tôt."],"answer":"Fatiguée, Marie s''est couchée tôt."}'),
('Invariabilité de certains adverbes', 2, 35000, 'Les adverbes sont invariables. « Possible » employé avec « le plus possible » est adverbe → invariable.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Répondez le plus vite possible.","Répondez le plus vite possibles.","Répondez les plus vite possibles.","Répondez le plus vite possiblement."],"answer":"Répondez le plus vite possible."}'),
('Accord de demi', 2, 35000, '« demi » avant le nom (avec trait d''union) est invariable. « demi » après le nom s''accorde en genre seulement.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["une demi-heure et demie","une demi-heure et demi","une demie-heure et demi","une demi-heure et demies"],"answer":"une demi-heure et demie"}'),
('Accord de même', 2, 35000, '« même » adjectif s''accorde. « même » adverbe (= aussi, jusqu''à) est invariable.',
 '{"type":"mcq","question":"Dans « Les enfants eux-mêmes ont ri », « mêmes » est...","options":["Un adjectif variable","Un adverbe invariable","Un verbe conjugué","Une préposition"],"answer":"Un adjectif variable"}'),
('Accord de tel', 2, 40000, '« tel » s''accorde avec le nom qui suit : « telle une étoile ». « tel que » s''accorde avec le nom qui précède.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Des experts tels que lui sont rares.","Des experts tel que lui sont rares.","Des experts tels qu''ils sont rares.","Des experts tel qu''eux sont rares."],"answer":"Des experts tels que lui sont rares."}'),
('Accord de nu', 2, 35000, '« nu » avant le nom (avec trait d''union) est invariable. Après le nom, il s''accorde.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il marche nu-pieds.","Il marche nu-pied.","Il marche nus-pieds.","Ils marchent pieds nus."],"answer":"Ils marchent pieds nus."}'),
('PP du verbe laisser + infinitif', 2, 40000, 'Le PP du verbe « laisser » suivi d''un infinitif est généralement invariable.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle s''est laissé tomber.","Elle s''est laissée tomber.","Elle s''est laissés tomber.","Elle s''est laissée tombé."],"answer":"Elle s''est laissé tomber."}'),
('Accord de PP — verbe faire', 2, 40000, 'Le PP du verbe « faire » suivi d''un infinitif est toujours invariable.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle les a fait courir.","Elle les a faits courir.","Elle les a faites courir.","Elle les a faire courir."],"answer":"Elle les a fait courir."}'),
('Erreur fréquente — palais/palace', 2, 35000, 'Ne pas confondre les mots de la même famille ou les homophones approximatifs. « Palais » vs « palace » (anglicisme).',
 '{"type":"mcq","question":"Laquelle de ces phrases utilise correctement un mot français ?","options":["Il habite dans un palace.","Il habite dans un palais.","Il habite dans un pâlace.","Il habite dans un pallas."],"answer":"Il habite dans un palais."}'),
('Accord après « se faire »', 2, 40000, 'Le PP de « se faire » suivi d''un infinitif est invariable (comme faire).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle s''est fait attaquer.","Elle s''est faite attaquer.","Elle s''est fait attaqué.","Elle s''est faites attaquer."],"answer":"Elle s''est fait attaquer."}'),
('Accord de l''attribut du CD', 2, 40000, 'L''attribut du CD (après rendre, appeler, trouver, élire, nommer, juger) s''accorde avec le CD.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["On les a nommé présidentes.","On les a nommées présidentes.","On les a nommés présidente.","On les a nommé présidente."],"answer":"On les a nommées présidentes."}'),
('Doubles consonnes — règle', 2, 35000, 'Certains préfixes entraînent un doublement : ir- + rationnel = irrationnel. Re- devant voyelle = redoublement possible.',
 '{"type":"mcq","question":"Lequel de ces mots est correctement orthographié ?","options":["irresponsable","iresponsable","irrresponsable","irresponsables"],"answer":"irresponsable"}'),
('Tréma', 2, 35000, 'Le tréma indique que deux voyelles consécutives se prononcent séparément (naïf, noël, maïs).',
 '{"type":"mcq","question":"Lequel de ces mots nécessite un tréma ?","options":["noel","noël","nöel","noël"],"answer":"noël"}'),
('Cédille', 2, 30000, 'La cédille se place sous le c (ç) devant a, o, u pour obtenir le son [s]. Ex : garçon, leçon, façon.',
 '{"type":"mcq","question":"Lequel de ces mots est correctement orthographié ?","options":["garcon","garçon","garçone","garçeons"],"answer":"garçon"}'),
('PP verbe impersonnel', 3, 50000, 'Le PP des verbes impersonnels (il a fallu, il a plu, il a neigé) est toujours invariable.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Les efforts qu''il a fallu faire étaient énormes.","Les efforts qu''il a fallus faire étaient énormes.","Les efforts qu''il a fallues faire étaient énormes.","Les efforts qu''il a fallut faire étaient énormes."],"answer":"Les efforts qu''il a fallu faire étaient énormes."}'),
('Accord de PP — verbes d''opinion', 3, 55000, 'Le PP des verbes de perception (voir, entendre, sentir) suivi d''un infinitif s''accorde si le CD fait l''action de l''infinitif.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ? (Les filles chantaient — elles font l''action)","options":["Les filles que j''ai entendu chanter étaient belles.","Les filles que j''ai entendues chanter étaient belles.","Les filles que j''ai entendus chanter étaient belles.","Les filles que j''ai entendue chanter étaient belles."],"answer":"Les filles que j''ai entendues chanter étaient belles."}'),
('Accord de PP — en', 3, 50000, 'Quand le CD est le pronom « en », le PP reste invariable.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Des pommes ? J''en ai mangées.","Des pommes ? J''en ai mangé.","Des pommes ? J''en ai mangés.","Des pommes ? J''en ai mangée."],"answer":"Des pommes ? J''en ai mangé."}'),
('Accord de PP — attribut', 3, 55000, 'Le PP employé comme attribut du sujet (avec être) s''accorde avec le sujet.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Ces questions semblent bien posés.","Ces questions semblent bien posées.","Ces questions semblent bien posée.","Ces questions semblent bien poser."],"answer":"Ces questions semblent bien posées."}'),
('Homophones — censé vs sensé', 3, 50000, '« censé » (supposé, est censé faire). « sensé » (qui a du sens, une idée sensée).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il est censé arriver à 9h.","Il est sensé arriver à 9h.","Il est censée arriver à 9h.","Il est sensée arriver à 9h."],"answer":"Il est censé arriver à 9h."}'),
('Homophones — pallier vs pâlir', 3, 50000, '« pallier » = remédier à (pallier un problème, sans préposition « à »).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Il faut pallier à ce problème.","Il faut pallier ce problème.","Il faut pâlier ce problème.","Il faut palier à ce problème."],"answer":"Il faut pallier ce problème."}'),
('Accord de « nu-tête » etc.', 3, 50000, '« Nu » devant un nom (avec trait d''union) est invariable : nu-pieds, nu-tête, nu-bras.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Ils sont sortis nus-pieds.","Ils sont sortis nu-pieds.","Ils sont sortis nud-pieds.","Ils sont sortis nue-pieds."],"answer":"Ils sont sortis nu-pieds."}'),
('Accord de PP — collectifs', 3, 55000, 'Après un collectif (une foule de, un groupe de, la majorité de), le PP s''accorde avec le nom collectif ou avec le nom qui suit selon le sens.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["La majorité des élèves est venue.","La majorité des élèves sont venus.","La majorité des élèves a venus.","La majorité des élèves est venu."],"answer":"La majorité des élèves est venue."}'),
('Double négation', 3, 50000, 'En français standard, une double négation est à éviter. « Je n''ai rien vu » (pas « Je n''ai pas rien vu »).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correctement formulée ?","options":["Je n''ai pas rien dit.","Je n''ai rien dit.","Je ai rien dit.","Je n''ai pas dit rien."],"answer":"Je n''ai rien dit."}'),
('Erreur sur l''apostrophe', 3, 50000, 'On élide les voyelles a, e, i devant un mot commençant par une voyelle ou un h muet. Mais pas devant un h aspiré.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Je suis allé en Haïti l''été passé.","Je suis allé en Haïti l''été passé.","Je suis allé en Haïti la été passé.","Je suis allée en Haïti l''été passée."],"answer":"Je suis allé en Haïti l''été passé."}'),
('Accord après « plus d''un »', 3, 55000, '« Plus d''un » est suivi d''un verbe au singulier. « Moins de deux » est suivi d''un verbe au pluriel.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Plus d''un élève ont réussi.","Plus d''un élève a réussi.","Plus d''un élève ont réussit.","Plus d''un élève réussirent."],"answer":"Plus d''un élève a réussi."}'),
('PP après « combien »', 3, 55000, 'Quand « combien de » est CD et placé avant le verbe (avoir), le PP s''accorde avec le nom sous-entendu.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Combien de pages as-tu lu ?","Combien de pages as-tu lues ?","Combien de pages as-tu lus ?","Combien de pages as-tu lis ?"],"answer":"Combien de pages as-tu lues ?"}'),
('Accord adjectif — invariable', 3, 50000, 'Certains adjectifs sont toujours invariables : chic, sympa, super, extra, bon marché, etc.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Des prix bon marché.","Des prix bons marchés.","Des prix bons marché.","Des prix bon marchés."],"answer":"Des prix bon marché."}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);


-- SEC1_FRA_orthographe_supp.sql (86 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-FRA-SEC1-ORTH') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Homophone : «a» vs «à»', 1, 20000, '«A» = verbe avoir (il a). «À» = préposition (il va à l''école).',
 '{"type":"mcq","question":"Complète : «Elle ___ mal à la tête.»","options":["à","a","â","ah"],"answer":"a"}'),
('Homophone : «à» préposition', 1, 20000, '«À» = préposition. On peut le remplacer par «vers» ou «au».',
 '{"type":"mcq","question":"Complète : «Je vais ___ l''école chaque matin.»","options":["a","à","â","as"],"answer":"à"}'),
('Homophone : «est» vs «et»', 1, 20000, '«Est» = verbe être. «Et» = conjonction (on peut ajouter «aussi»).',
 '{"type":"mcq","question":"Complète : «Il ___ grand ___ fort.»","options":["est / est","et / est","est / et","et / et"],"answer":"est / et"}'),
('Homophone : «ou» vs «où»', 1, 20000, '«Ou» = choix (on peut dire «ou bien»). «Où» = lieu/moment (où est-il ?).',
 '{"type":"mcq","question":"Complète : «Je ne sais pas ___ il est allé ___ s''il viendra.»","options":["où / ou","ou / où","où / où","ou / ou"],"answer":"où / ou"}'),
('Homophone : «ce» vs «se»', 1, 20000, '«Ce» = déterminant ou pronom démonstratif. «Se» = pronom réfléchi.',
 '{"type":"mcq","question":"Complète : «___ livre ___ trouve sur la table.»","options":["se / ce","ce / ce","ce / se","se / se"],"answer":"ce / se"}'),
('Homophone : «son» vs «sont»', 1, 20000, '«Son» = déterminant possessif. «Sont» = verbe être (ils sont).',
 '{"type":"mcq","question":"Complète : «Ses chaussures ___ dans ___ sac.»","options":["sont / son","son / sont","sont / sont","son / son"],"answer":"sont / son"}'),
('Homophone : «on» vs «ont»', 1, 20000, '«On» = pronom (on mange). «Ont» = auxiliaire avoir, 3e pers. pl. (ils ont).',
 '{"type":"mcq","question":"Complète : «___ dirait qu''ils ___ faim.»","options":["Ont / on","On / ont","On / on","Ont / ont"],"answer":"On / ont"}'),
('Homophone : «mes» vs «mais»', 1, 20000, '«Mes» = déterminant possessif pluriel. «Mais» = conjonction d''opposition.',
 '{"type":"mcq","question":"Complète : «J''ai perdu ___ clés, ___ je les ai retrouvées.»","options":["mais / mes","mes / mais","mes / mes","mais / mais"],"answer":"mes / mais"}'),
('Homophone : «peu» vs «peut»', 1, 20000, '«Peu» = adverbe de quantité. «Peut» = verbe pouvoir (il peut).',
 '{"type":"mcq","question":"Complète : «Il ___ rester encore un ___.»","options":["peut / peu","peu / peut","peut / peut","peu / peu"],"answer":"peut / peu"}'),
('Homophone : «sans» vs «s''en»', 1, 20000, '«Sans» = préposition (absence). «S''en» = pronom réfléchi + en.',
 '{"type":"mcq","question":"Complète : «Elle ___ va ___ le moindre regret.»","options":["s''en / sans","sans / s''en","s''en / s''en","sans / sans"],"answer":"s''en / sans"}'),
('Homophone : «dans» vs «d''en»', 1, 20000, '«Dans» = préposition de lieu. «D''en» = préposition «de» + pronom «en» (peu fréquent).',
 '{"type":"mcq","question":"Complète : «Il marche ___ la rue.»","options":["dans","d''en","dent","dan"],"answer":"dans"}'),
('Accord du nom en genre : règle de base', 1, 18000, 'En général, on ajoute «-e» pour former le féminin. Étudiant → étudiante.',
 '{"type":"mcq","question":"Quel est le féminin de «étudiant» ?","options":["étudiante","étudiant","étudiant-e","étudients"],"answer":"étudiante"}'),
('Accord du nom en nombre : règle de base', 1, 18000, 'En général, on ajoute «-s» pour former le pluriel. Maison → maisons.',
 '{"type":"mcq","question":"Quel est le pluriel de «voiture» ?","options":["voiturs","voitures","voiturex","voiturez"],"answer":"voitures"}'),
('Pluriel des noms en -al', 1, 20000, 'Les noms en «-al» font «-aux» au pluriel. Animal → animaux.',
 '{"type":"mcq","question":"Quel est le pluriel de «animal» ?","options":["animals","animaux","animaaux","animales"],"answer":"animaux"}'),
('Pluriel des noms en -eau', 1, 20000, 'Les noms en «-eau» font «-eaux» au pluriel. Bateau → bateaux.',
 '{"type":"mcq","question":"Quel est le pluriel de «gâteau» ?","options":["gâteaux","gâteaus","gâteaues","gâteausx"],"answer":"gâteaux"}'),
('Accord de l''adjectif (féminin)', 1, 20000, 'L''adjectif s''accorde avec le nom qu''il qualifie. «Robe» (fém.) → «bleue».',
 '{"type":"mcq","question":"Quelle forme est correcte : «une jupe ___» ?","options":["brun","bruns","brune","brunes"],"answer":"brune"}'),
('Accord de l''adjectif (masculin pluriel)', 1, 20000, 'Masculin pluriel → adjectif avec -s (ou -aux).',
 '{"type":"mcq","question":"Quelle forme est correcte : «des manteaux ___» ?","options":["chaud","chaude","chauds","chaudes"],"answer":"chauds"}'),
('Majuscule en début de phrase', 1, 18000, 'Tout début de phrase prend une majuscule.',
 '{"type":"mcq","question":"Quelle phrase a une majuscule au bon endroit ?","options":["le soleil brille.","Le soleil brille.","le Soleil brille.","LE soleil brille."],"answer":"Le soleil brille."}'),
('Majuscule pour un nom propre', 1, 18000, 'Les noms propres (personnes, villes, pays...) prennent une majuscule.',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["la ville de montréal","la ville de Montréal","La ville de montréal","La Ville de Montréal"],"answer":"la ville de Montréal"}'),
('Double consonne : «nn»', 1, 20000, 'Certains mots ont une double consonne. «Connexion», «innocent», «ennemi».',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["inocent","inoncer","innocent","innocant"],"answer":"innocent"}'),
('Accent grave : «è»', 1, 18000, 'L''accent grave se met sur «è» (ouvert), «à», «ù».',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["eleve","élève","elevé","eleve"],"answer":"élève"}'),
('Accent aigu : «é»', 1, 18000, 'L''accent aigu se met sur «é» (fermé).',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour le participe passé de «finir» ?","options":["fini","finit","finié","finì"],"answer":"fini"}'),
('Cédille : «ç»', 1, 18000, 'La cédille se met sous le «c» devant «a», «o», «u» pour faire le son [s].',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["ca","ça","cà","ça"],"answer":"ça"}'),
('Tréma : «ë»', 1, 18000, 'Le tréma indique que deux voyelles se prononcent séparément. Noël, Haïti.',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour la fête de décembre ?","options":["Noel","Noël","Noêl","Noèl"],"answer":"Noël"}'),
('Tiret dans les mots composés', 1, 18000, 'Certains mots composés prennent un tiret. Arc-en-ciel, porte-monnaie.',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["arc en ciel","arcenciel","arc-en-ciel","arc_en_ciel"],"answer":"arc-en-ciel"}'),
('Accent circonflexe : «â»', 1, 18000, 'L''accent circonflexe sur «â» est souvent une marque historique d''un «s» disparu. Fête = «feste».',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["fete","fête","fèté","feté"],"answer":"fête"}'),
('Lettres muettes : «-ent» des verbes', 1, 18000, 'La terminaison «-ent» des verbes (3e pers. pl.) est muette. «Ils chantent» → son [∅nt].',
 '{"type":"mcq","question":"Dans «Elles dansent», quelle lettre est muette ?","options":["E","A","S","T"],"answer":"T"}'),
('Homophone : «ces» vs «ses» vs «c''est» vs «s''est»', 1, 22000, '«Ces» = déterminant démonstratif pl. «Ses» = déterminant possessif pl.',
 '{"type":"mcq","question":"Complète : «___ livres appartiennent à Marie.»","options":["c''est","s''est","ses","ces"],"answer":"ces"}'),
('Déterminant possessif : «ses» vs «ces»', 1, 20000, '«Ses» = déterminant possessif. «Ces» = déterminant démonstratif.',
 '{"type":"mcq","question":"Complète : «Marie range ___ affaires.»","options":["ces","ses","c''est","s''est"],"answer":"ses"}'),
('Accord du participe passé employé avec avoir', 2, 32000, 'Avec «avoir», le p.p. s''accorde avec le COD si celui-ci est avant le verbe.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Les fleurs que j''ai cueillis sont belles.","Les fleurs que j''ai cueillies sont belles.","Les fleurs que j''ai cueilli sont belles.","Les fleurs que j''ai cueillies était belles."],"answer":"Les fleurs que j''ai cueillies sont belles."}'),
('Accord du participe passé avec être', 2, 32000, 'Avec «être», le p.p. s''accorde avec le sujet.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Les garçons sont partis.","Les garçons sont parties.","Les garçons sont partis.","Les garçons sont partir."],"answer":"Les garçons sont partis."}'),
('Participe passé invariable avec avoir (COD après)', 2, 32000, 'Avec avoir, si le COD est après le p.p., il reste invariable.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elle a mangée une pomme.","Elle a mangé une pomme.","Elle a mangés des pommes.","Elle a mangées des pommes."],"answer":"Elle a mangé une pomme."}'),
('Homophone : «quand» vs «quant» vs «qu''en»', 2, 30000, '«Quand» = conjonction de temps. «Quant» = pour ce qui est de (quant à lui). «Qu''en» = «que» + «en».',
 '{"type":"mcq","question":"Complète : «___ à moi, je préfère le chocolat.»","options":["Quand","Quant","Qu''en","Cant"],"answer":"Quant"}'),
('Homophone : «davantage» vs «d''avantage»', 2, 30000, '«Davantage» = plus. «D''avantage» n''existe pas comme locution standard.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Il faut d''avantage étudier.","Il faut davantage étudier.","Les deux sont correctes.","Aucune n''est correcte."],"answer":"Il faut davantage étudier."}'),
('Homophone : «par» vs «part»', 2, 30000, '«Par» = préposition. «Part» = une portion, ou dans «à part», «de ma part».',
 '{"type":"mcq","question":"Complète : «De ma ___, merci pour ce cadeau.»","options":["par","part","pars","parts"],"answer":"part"}'),
('Accord adjectif de couleur : règle générale', 2, 30000, 'Les adjectifs de couleur s''accordent en genre et nombre sauf s''ils sont composés ou issus de noms.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Des robes bleus","Des robes bleus","Des robes bleues","Des robes bleu"],"answer":"Des robes bleues"}'),
('Adjectifs de couleur invariables (noms)', 2, 30000, 'Les adjectifs de couleur provenant de noms sont invariables : marron, crème, ivoire, saumon.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Des vestes marrons","Des vestes marrons","Des vestes marron","Des vestes maronnes"],"answer":"Des vestes marron"}'),
('Adjectifs de couleur composés (invariables)', 2, 30000, 'Un adjectif de couleur composé est invariable : des robes bleu ciel, des chaussures gris foncé.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Des chemises bleu claires","Des chemises bleus clairs","Des chemises bleu clair","Des chemises bleues claires"],"answer":"Des chemises bleu clair"}'),
('Accord des noms en -ou', 2, 30000, 'Sept noms en -ou font leur pluriel en -oux : bijou, caillou, chou, genou, hibou, joujou, pou.',
 '{"type":"mcq","question":"Quel est le pluriel correct de «genou» ?","options":["genous","genoux","genoues","genouys"],"answer":"genoux"}'),
('Accord de «tout» adverbe (invariable)', 2, 32000, '«Tout» adverbe est normalement invariable, mais fait «toute, toutes» devant un adjectif féminin commençant par une consonne.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elles sont toute fatiguées.","Elles sont tout fatiguées.","Elles sont tous fatiguées.","Elles sont toutes fatiguées."],"answer":"Elles sont toutes fatiguées."}'),
('Accord de «quel» dans l''exclamation', 2, 30000, '«Quel» s''accorde avec le nom qui suit. Quel homme ! Quelle femme !',
 '{"type":"mcq","question":"Quelle forme est correcte ? «___ belle journée !»","options":["Quel","Quelle","Quels","Quelles"],"answer":"Quelle"}'),
('Majuscule dans les titres', 2, 30000, 'Les règles varient selon le type de titre. En général, premier mot et noms propres prennent la majuscule.',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour le titre d''un roman ?","options":["le Seigneur Des Anneaux","Le Seigneur des Anneaux","le seigneur des anneaux","LE SEIGNEUR DES ANNEAUX"],"answer":"Le Seigneur des Anneaux"}'),
('Usage du trait d''union dans les nombres', 2, 30000, 'On met un trait d''union entre les composantes des nombres de 17 à 99 quand elles sont juxtaposées.',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["vingt et un","vingt-et-un","vingt-et un","vingtetun"],"answer":"vingt et un"}'),
('Trait d''union : 82 et 92', 2, 30000, 'Quatre-vingt-deux, quatre-vingt-douze. Le trait d''union lie les composantes.',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour 82 ?","options":["quatre vingt deux","quatre-vingt deux","quatre-vingt-deux","quatre vingts deux"],"answer":"quatre-vingt-deux"}'),
('Accords dans un groupe nominal complexe', 2, 32000, 'Tous les éléments du GN (déterminant, nom, adjectif) s''accordent ensemble.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Ces grandes maisons blancs","Ces grandes maisons blanches","Ces grand maisons blanches","Ces grandes maison blanches"],"answer":"Ces grandes maisons blanches"}'),
('Accord après «avoir l''air» (sujet animé)', 2, 32000, 'Si le sujet est animé (être vivant), «avoir l''air» = «sembler» → accord avec le sujet.',
 '{"type":"mcq","question":"Quelle phrase est correcte pour un sujet animé ?","options":["Elles ont l''air contents.","Elles ont l''air contentes.","Elles ont l''air content.","Elles ont l''air contentes."],"answer":"Elles ont l''air contentes."}'),
('Homophones : «vingt» et «vin»', 2, 28000, '«Vingt» = nombre 20. «Vin» = boisson alcoolisée. «Vint» = passé simple de «venir».',
 '{"type":"mcq","question":"Complète : «Il y avait ___ élèves dans la classe.»","options":["vin","vins","vingt","vient"],"answer":"vingt"}'),
('«Rien» + négation : «ne... rien»', 2, 30000, 'La négation «ne... rien» nécessite le «ne» devant le verbe et «rien» après.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Il ne sait pas rien.","Il ne sait rien.","Il sait ne rien.","Il ne rien sait."],"answer":"Il ne sait rien."}'),
('Accord du participe passé des verbes d''état', 2, 32000, 'P.p. de «paraître», «sembler», «devenir» avec être : accord avec le sujet.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elles sont devenues médecines.","Elles sont devenues médecins.","Elles sont devenu médecins.","Elles sont devenus médecins."],"answer":"Elles sont devenues médecins."}'),
('Élision : l''apostrophe', 2, 28000, 'On élide (apostrophe) les voyelles finales devant une voyelle ou h muet.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["le élève","l''élève","l-élève","le élève (bis)"],"answer":"l''élève"}'),
('Élision de «que»', 2, 28000, '«Que» devient «qu''» devant une voyelle ou h muet.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Je crois que il viendra.","Je crois qu''il viendra.","Je crois quil viendra.","Je crois qu il viendra."],"answer":"Je crois qu''il viendra."}'),
('Accord après «c''est» (attribut)', 2, 30000, '«C''est» est suivi d''un attribut. «Ce sont» avec un nom pluriel.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["C''est mes amis.","Ce sont mes amis.","Ce suis mes amis.","C''est mes ami."],"answer":"Ce sont mes amis."}'),
('Orthographe des adverbes en «-ment»', 2, 30000, 'La plupart des adverbes en «-ment» se forment sur le féminin de l''adjectif.',
 '{"type":"mcq","question":"Quel adverbe se forme à partir de l''adjectif «naturel» ?","options":["naturèlement","naturelment","naturellement","naturellament"],"answer":"naturellement"}'),
('Pas de -s à l''impératif 2e pers. sg. (1er groupe)', 2, 30000, 'À la 2e personne du singulier de l''impératif des verbes en -er, pas de -s. «Mange ! Parle !»',
 '{"type":"mcq","question":"Quelle forme est correcte à l''impératif (2e pers. sing.) ?","options":["Manges !","Mange !","Mangez !","Mangeons !"],"answer":"Mange !"}'),
('Exception : -s à l''impératif devant y et en', 2, 32000, 'On ajoute -s devant «y» ou «en». «Vas-y !», «Parles-en !»',
 '{"type":"mcq","question":"Quelle forme est correcte ?","options":["Va-y !","Va y !","Vas-y !","Vay !"],"answer":"Vas-y !"}'),
('Accord des adjectifs numéraux ordinaux', 2, 30000, '«Vingt» et «cent» prennent -s seulement s''ils terminent le nombre. «Quatre-vingts» mais «quatre-vingt-deux».',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour 80 ?","options":["quatre-vingts","quatre-vingt","quatrevingts","quatre vingts"],"answer":"quatre-vingts"}'),
('«Cent» et son accord', 2, 30000, '«Cent» prend -s s''il est seul et non suivi d''un autre nombre. «Deux cents» mais «deux cent deux».',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour 200 ?","options":["deux cent","deux cents","deux-cent","deux-cents"],"answer":"deux cents"}'),
('Homophone : «leur» vs «leurs»', 2, 30000, '«Leur» = pronom (leur dire) ou adj. possessif singulier (leur maison). «Leurs» = adj. possessif pluriel.',
 '{"type":"mcq","question":"Complète : «Elles ont mis ___ livres dans ___ sac.»","options":["leurs / leur","leur / leur","leurs / leurs","leur / leurs"],"answer":"leurs / leur"}'),
('Accord du participe passé des verbes pronominaux (sens passif)', 3, 45000, 'Sens passif : «Ces livres se sont vendus rapidement.» Le p.p. s''accorde avec le sujet.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Ces maisons se sont vendu rapidement.","Ces maisons se sont vendues rapidement.","Ces maisons se sont vendus rapidement.","Ces maisons se sont vendues rapidement."],"answer":"Ces maisons se sont vendues rapidement."}'),
('Accord du participe passé : COD pronom antéposé', 3, 45000, 'COD pronom devant avoir (la, le, les, me, te, se, nous, vous, qu'') → accord.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Je les ai vu hier.","Je les ai vus hier.","Je les ai vue hier.","Je les ai vues hier."],"answer":"Je les ai vus hier. (masculin pluriel)"}'),
('«En» ne déclenche pas l''accord', 3, 45000, 'Le pronom «en» ne déclenche pas l''accord du p.p. «Des pommes, j''en ai mangé.»',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Des pommes, j''en ai mangées.","Des pommes, j''en ai mangé.","Des pommes, j''en ai mangés.","Des pommes, je les ai mangé."],"answer":"Des pommes, j''en ai mangé."}'),
('Accord du p.p. avec un COD collectif', 3, 45000, 'Le p.p. s''accorde avec le COD. «La foule que j''ai vue» (COD = «que» = foule, féminin singulier).',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["La foule que j''ai vue était immense.","La foule que j''ai vu était immense.","La foule que j''ai vus était immense.","La foule que j''ai vues était immense."],"answer":"La foule que j''ai vue était immense."}'),
('Accord complexe : «se faire + infinitif»', 3, 45000, 'P.p. de «se faire» suivi d''un infinitif : toujours invariable.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elle s''est faite couper les cheveux.","Elle s''est fait couper les cheveux.","Elle se fait coupé les cheveux.","Elle s''est faites couper les cheveux."],"answer":"Elle s''est fait couper les cheveux."}'),
('Accord du p.p. : «laisser + infinitif»', 3, 45000, 'P.p. de «laisser» suivi d''un infinitif : accord facultatif selon si le COD fait l''action ou la subit.',
 '{"type":"mcq","question":"Quelle phrase illustre la règle d''accord avec «laisser + infinitif» ?","options":["Je les ai laissés partir (ils partent = accord optionnel)","Je les ai laissé partir (forme toujours correcte)","Les deux formes sont acceptées","Aucune des deux"],"answer":"Les deux formes sont acceptées"}'),
('Orthographe rectifiée de 1990', 3, 45000, 'La réforme de 1990 permet de simplifier certains mots. Ex : «nénuphar» peut s''écrire «nénufar».',
 '{"type":"mcq","question":"Selon l''orthographe rectifiée de 1990, quelle forme est désormais acceptable pour «événement» ?","options":["évenement","évenèment","évènement","événement"],"answer":"évènement"}'),
('Noms en «-té» (sans -e final)', 3, 42000, 'Les noms féminins abstraits en «-té» ne prennent pas de «e» final. Beauté, bonté, liberté.',
 '{"type":"mcq","question":"Quelle orthographe est correcte pour «l''amitié» ?","options":["amitié","amitiée","amitée","amitier"],"answer":"amitié"}'),
('Noms en «-tié» vs «-tée»', 3, 42000, 'Des noms concrets en «-ée» : dictée, montée, pâtée. Des abstraits en «-té» : amitié, moitié.',
 '{"type":"mcq","question":"Laquelle de ces formes est correcte pour le nom abstrait de «demi» ?","options":["moitiée","moitiéé","moitié","moitie"],"answer":"moitié"}'),
('Accord de «quelque» vs «quel que»', 3, 45000, '«Quelque» = déterminant indéfini (quelques livres). «Quel que» = quel + que devant être.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Quelque soient les obstacles, il réussira.","Quels que soient les obstacles, il réussira.","Quel que soit les obstacles, il réussira.","Quelles que soient les obstacles, il réussira."],"answer":"Quels que soient les obstacles, il réussira."}'),
('Accord de «tel quel»', 3, 45000, '«Tel quel» s''accorde avec le nom. «Telle quelle», «tels quels», «telles quelles».',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elle a rendu la voiture tel quel.","Elle a rendu la voiture telle quelle.","Elle a rendu la voiture tels quels.","Elle a rendu la voiture telle quel."],"answer":"Elle a rendu la voiture telle quelle."}'),
('Accord de «même»', 3, 45000, '«Même» = adjectif (s''accorde) ou adverbe (invariable). «Les élèves mêmes» vs «Elles sont même venues».',
 '{"type":"mcq","question":"«Même» dans «elles sont même venues» est...","options":["Un adjectif qui s''accorde","Un adverbe invariable","Un pronom","Un déterminant"],"answer":"Un adverbe invariable"}'),
('Accord de «nu» dans «nu-pieds»', 3, 45000, '«Nu» placé avant un nom reste invariable et ne prend pas de trait d''union. «Nu-pieds» mais «les pieds nus».',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["marcher nu-pieds","marcher les pieds nu","marcher les pieds nus","Les deux dernières sont correctes"],"answer":"Les deux dernières sont correctes"}'),
('Accord de «demi»', 3, 45000, '«Demi» avant le nom est invariable avec trait d''union. Après, il s''accorde avec le nom.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["une demi-heure","une demie-heure","une heure et demi","une heure et demi"],"answer":"une demi-heure"}'),
('Accord de «ci-joint»', 3, 45000, '«Ci-joint» est invariable en tête de phrase ou avant le nom. Variable après le nom.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Ci-joints les documents","Ci-joint les documents","Vous trouverez les documents ci-jointes","Vous trouverez les documents ci-joints"],"answer":"Vous trouverez les documents ci-joints"}'),
('Orthographe de «cueillerons» (verbe cueillir)', 3, 42000, '«Cueillir» au futur : je cueillerai, tu cueilleras, il cueillera, nous cueillerons.',
 '{"type":"mcq","question":"Quelle forme est correcte au futur de «cueillir» à la 1re personne du pluriel ?","options":["cueillerons","cueillirons","cueillerons","cueillrons"],"answer":"cueillerons"}'),
('Verbe «appeler» au présent', 3, 42000, '«Appeler» double le «l» devant une terminaison muette. J''appelle, tu appelles, il appelle...',
 '{"type":"mcq","question":"Quelle forme est correcte à la 3e personne du singulier de «appeler» au présent ?","options":["apelle","appele","appelle","appellé"],"answer":"appelle"}'),
('Verbe «jeter» au présent', 3, 42000, '«Jeter» double le «t» devant une terminaison muette. Je jette, tu jettes, il jette...',
 '{"type":"mcq","question":"Quelle forme est correcte à la 1re personne du singulier de «jeter» au présent ?","options":["jète","jètte","jette","jet"],"answer":"jette"}'),
('Verbe «acheter» au présent (exception)', 3, 42000, '«Acheter» prend un accent grave plutôt que de doubler le «t». J''achète, tu achètes, il achète.',
 '{"type":"mcq","question":"Quelle forme est correcte à la 2e personne du singulier de «acheter» au présent ?","options":["achettes","achette","achètes","achete"],"answer":"achètes"}'),
('Accord du p.p. : «Ils se sont vu»', 3, 45000, 'Verbe pronominal réciproque + infinitif sous-entendu : accord si le p.p. a un COD. «Ils se sont vus.» (ils ont vu eux-mêmes).',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elles se sont vu dans le miroir.","Elles se sont vues dans le miroir.","Elles se sont vus dans le miroir.","Elles se sont vues dans le miroir."],"answer":"Elles se sont vues dans le miroir."}'),
('Accord des participes passés : «se rendre compte»', 3, 45000, '«Se rendre compte» est locution figée. P.p. s''accorde avec «compte» (COD = «compte»). Invariable car «compte» est après.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elles se sont rendues compte de l''erreur.","Elles se sont rendu compte de l''erreur.","Elles s''est rendu compte de l''erreur.","Elles se sont rendus compte de l''erreur."],"answer":"Elles se sont rendu compte de l''erreur."}'),
('Homophone savant : «près» vs «prêt»', 3, 42000, '«Près» = préposition de lieu (proche). «Prêt» = adjectif (préparé).',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Il est prêt du départ.","Il est près du départ.","Il est prêt à partir.","Il est près à partir."],"answer":"Il est prêt à partir."}'),
('Orthographe : «en train de» (locution)', 3, 42000, '«En train de» = locution exprimant une action en cours. S''écrit en trois mots séparés.',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["Il est entrain de travailler.","Il est en train de travailler.","Il est en-train de travailler.","Il est en train-de travailler."],"answer":"Il est en train de travailler."}'),
('Orthographe rectifiée : tiret et mots composés', 3, 45000, 'Depuis 1990, certains mots composés perdent leur trait d''union. «Weekend» peut s''écrire sans tiret.',
 '{"type":"mcq","question":"Selon la réforme de 1990, quelle simplification a été autorisée pour certains mots composés ?","options":["Supprimer la majuscule dans les noms propres","Supprimer les accents","Supprimer certains traits d''union ou en ajouter","Changer les pluriels irréguliers"],"answer":"Supprimer certains traits d''union ou en ajouter"}'),
('Accord de «nu» et «mi» en composition', 3, 42000, '«Nu-» et «mi-» restent invariables en composition. Nu-tête, mi-temps.',
 '{"type":"mcq","question":"Quelle orthographe est correcte ?","options":["à nu-tête","à nue-tête","à nu têtes","nu-têtes"],"answer":"à nu-tête"}'),
('Accord de «feu» (adjectif de deuil)', 3, 45000, 'L''adjectif «feu» (décédé) est variable. «Feus mes amis» mais «feu la reine» (avant le déterminant = invariable).',
 '{"type":"mcq","question":"Quelle phrase est correcte (feu = décédé) ?","options":["La feue reine","Feu la reine","Feux les rois","La feue reine est correcte"],"answer":"Feu la reine"}'),
('Accord de «nu-tête», «tête nue»', 3, 42000, '«Nu» avant le nom : invariable, trait d''union. Après le nom : variable, sans trait d''union.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["marcher tête nue","marcher tête nues","marcher nu-tête","Les première et troisième sont correctes"],"answer":"Les première et troisième sont correctes"}'),
('Accord du verbe avec un sujet collectif + complément pluriel', 3, 45000, 'Nom collectif + complément pluriel : accord selon le sens. «Un groupe d''élèves travaille/travaillent.»',
 '{"type":"mcq","question":"Quelle phrase respecte les règles d''accord avec un nom collectif ?","options":["Un groupe d''élèves travaillons.","Un groupe d''élèves travaillent. (sens pluriel accepté)","Un groupe d''élèves travaille. (singulier accepté)","Les formes 2 et 3 sont toutes deux acceptées."],"answer":"Les formes 2 et 3 sont toutes deux acceptées."}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);

COMMIT;
-- Total : 149 questions pour FRA_orthographe
