-- ============================================================
-- IMPORT — FRA_grammaire | PFEQ-FRA-SEC1-GR
-- À exécuter dans Supabase → SQL Editor → Run
-- ============================================================
BEGIN;

-- SEC1_FRA_grammaire.sql (72 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-FRA-SEC1-GR') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Nature du mot : nom commun', 1, 20000, 'Un nom commun désigne une réalité générale (personne, animal, chose, idée). Il peut être précédé d''un déterminant.',
 '{"type":"mcq","question":"Dans la phrase « Le chien court dans le parc », quel mot est un nom commun ?","options":["Le","court","chien","dans"],"answer":"chien"}'),
('Nature du mot : nom propre', 1, 20000, 'Un nom propre désigne une réalité unique et s''écrit avec une majuscule.',
 '{"type":"mcq","question":"Lequel de ces mots est un nom propre ?","options":["ville","montagne","Québec","rivière"],"answer":"Québec"}'),
('Nature du mot : déterminant', 1, 20000, 'Un déterminant accompagne toujours un nom et introduit le groupe nominal. (le, la, les, un, une, des, mon, ma…)',
 '{"type":"mcq","question":"Dans la phrase « Une belle fleur pousse là », quel mot est un déterminant ?","options":["belle","fleur","pousse","Une"],"answer":"Une"}'),
('Nature du mot : adjectif', 1, 20000, 'L''adjectif qualifie ou classifie un nom. Il s''accorde en genre et en nombre avec le nom qu''il accompagne.',
 '{"type":"mcq","question":"Dans la phrase « Ce gros chien noir aboie », quels mots sont des adjectifs ?","options":["Ce, chien, aboie","gros, noir","Ce, aboie","chien, aboie"],"answer":"gros, noir"}'),
('Nature du mot : verbe', 1, 20000, 'Le verbe exprime une action ou un état. Il se conjugue selon le temps, la personne et le nombre.',
 '{"type":"mcq","question":"Dans la phrase « Les élèves étudient avec sérieux », quel mot est le verbe ?","options":["élèves","étudient","sérieux","avec"],"answer":"étudient"}'),
('Nature du mot : pronom', 1, 20000, 'Un pronom remplace un nom ou un groupe nominal déjà mentionné (il, elle, ils, elles, lui, leur…)',
 '{"type":"mcq","question":"Dans la phrase « Marie est arrivée. Elle est contente. », quel mot est un pronom ?","options":["Marie","arrivée","Elle","contente"],"answer":"Elle"}'),
('Nature du mot : adverbe', 1, 20000, 'L''adverbe est invariable. Il modifie un verbe, un adjectif ou un autre adverbe. (vite, souvent, très, bien…)',
 '{"type":"mcq","question":"Dans la phrase « Il court très vite », lequel est un adverbe ?","options":["Il","court","très","l''ensemble très vite"],"answer":"l''ensemble très vite"}'),
('Nature du mot : préposition', 1, 20000, 'La préposition unit deux éléments de la phrase (à, de, dans, sur, sous, avec, pour, par, en…). Elle est invariable.',
 '{"type":"mcq","question":"Laquelle de ces listes contient seulement des prépositions ?","options":["le, la, les, un","à, de, dans, avec","et, ou, mais, donc","très, bien, jamais, souvent"],"answer":"à, de, dans, avec"}'),
('Nature du mot : conjonction', 1, 20000, 'La conjonction de coordination relie des mots ou des propositions (mais, ou, et, donc, or, ni, car).',
 '{"type":"mcq","question":"Dans la phrase « J''aime le football, mais je préfère le basketball », quel mot est une conjonction ?","options":["J''aime","football","mais","préfère"],"answer":"mais"}'),
('Groupe nominal identification', 1, 25000, 'Le GN contient au minimum un déterminant + un nom. Il peut être enrichi d''un adjectif ou d''un complément du nom.',
 '{"type":"mcq","question":"Quel est le groupe nominal (GN) dans la phrase « Le grand chien de ma voisine aboie » ?","options":["aboie","de ma voisine","Le grand chien de ma voisine","ma voisine aboie"],"answer":"Le grand chien de ma voisine"}'),
('Groupe verbal identification', 1, 25000, 'Le GV contient le verbe et ses compléments. Il forme la partie de la phrase après le sujet.',
 '{"type":"mcq","question":"Quel est le groupe verbal (GV) dans la phrase « Les enfants jouent dans la cour » ?","options":["Les enfants","jouent dans la cour","dans la cour","Les enfants jouent"],"answer":"jouent dans la cour"}'),
('Sujet du verbe', 1, 25000, 'Le sujet est le groupe qui fait l''action ou dont on parle. On le trouve en posant la question Qui est-ce qui ? + verbe.',
 '{"type":"mcq","question":"Dans la phrase « Les oiseaux chantent le matin », quel est le sujet ?","options":["Les oiseaux","chantent","le matin","matin"],"answer":"Les oiseaux"}'),
('Attribut du sujet', 1, 25000, 'L''attribut du sujet est relié au sujet par un verbe attributif (être, sembler, paraître, devenir…).',
 '{"type":"mcq","question":"Dans la phrase « Ce gâteau est délicieux », quel est l''attribut du sujet ?","options":["Ce gâteau","est","délicieux","Ce"],"answer":"délicieux"}'),
('Complément direct du verbe (CD)', 1, 25000, 'Le CD répond à la question Quoi ? ou Qui ? directement après le verbe, sans préposition.',
 '{"type":"mcq","question":"Dans la phrase « Luce mange une pomme », quel est le complément direct du verbe ?","options":["Luce","mange","une pomme","pomme"],"answer":"une pomme"}'),
('Complément indirect du verbe (CI)', 1, 25000, 'Le CI répond à la question À qui ? À quoi ? De qui ? De quoi ? Il est introduit par une préposition.',
 '{"type":"mcq","question":"Dans la phrase « Il parle à son ami », quel est le complément indirect ?","options":["Il","parle","à son ami","ami"],"answer":"à son ami"}'),
('Complément de phrase', 1, 25000, 'Le CP est facultatif et mobile. Il indique le temps, le lieu, la cause ou la manière. On peut le déplacer.',
 '{"type":"mcq","question":"Dans la phrase « Hier, les élèves ont bien travaillé », quel mot est un complément de phrase ?","options":["les élèves","ont travaillé","bien","Hier"],"answer":"Hier"}'),
('Accord du verbe avec le sujet', 1, 25000, 'Le verbe s''accorde en personne et en nombre avec son sujet. Sujet pluriel → verbe pluriel.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Les enfants court vite.","Les enfants courent vite.","Les enfants coure vite.","L''enfants courent vite."],"answer":"Les enfants courent vite."}'),
('Genre du nom', 1, 20000, 'Le genre (masculin/féminin) du nom est une propriété intrinsèque. Le déterminant permet de l''identifier.',
 '{"type":"mcq","question":"Quel déterminant complète correctement : « ___ température est élevée » ?","options":["Le","La","Les","Des"],"answer":"La"}'),
('Pluriel des noms', 1, 20000, 'En général, on forme le pluriel en ajoutant un -s à la fin du nom. Mais les noms en -eau font -eaux.',
 '{"type":"mcq","question":"Quel est le pluriel du mot « château » ?","options":["châteaux","châteaus","châteaus","châteauxe"],"answer":"châteaux"}'),
('Accord de l''adjectif', 1, 25000, 'L''adjectif s''accorde en genre et en nombre avec le nom ou le pronom qu''il qualifie ou avec lequel il est en relation.',
 '{"type":"mcq","question":"Laquelle de ces phrases contient un adjectif correctement accordé ?","options":["une robe bleu","des chapeaux verts","une maison grand","des fleurs rouge"],"answer":"des chapeaux verts"}'),
('Types de phrases — déclarative', 1, 20000, 'La phrase déclarative affirme ou nie quelque chose. Elle se termine par un point.',
 '{"type":"mcq","question":"Laquelle est une phrase déclarative ?","options":["Ferme la porte !","Est-ce qu''il viendra ?","Il fait beau aujourd''hui.","Comme c''est beau !"],"answer":"Il fait beau aujourd''hui."}'),
('Types de phrases — interrogative', 1, 20000, 'La phrase interrogative pose une question. Elle se termine par un point d''interrogation.',
 '{"type":"mcq","question":"Laquelle est une phrase interrogative ?","options":["Il est parti hier.","Partez maintenant !","Où est-il allé ?","Quelle belle journée !"],"answer":"Où est-il allé ?"}'),
('Types de phrases — impérative', 1, 20000, 'La phrase impérative donne un ordre ou un conseil. Le sujet est généralement absent.',
 '{"type":"mcq","question":"Laquelle est une phrase impérative ?","options":["Tu dois partir.","Pars maintenant !","Est-ce que tu pars ?","Il part bientôt."],"answer":"Pars maintenant !"}'),
('Types de phrases — exclamative', 1, 20000, 'La phrase exclamative exprime une émotion forte. Elle se termine par un point d''exclamation.',
 '{"type":"mcq","question":"Laquelle est une phrase exclamative ?","options":["Quelle belle surprise !","Est-ce une surprise ?","Il y a une surprise.","Prépare une surprise."],"answer":"Quelle belle surprise !"}'),
('Phrase de base et ses constituants', 1, 25000, 'La phrase de base contient un sujet (S) + un prédicat (P) et parfois un complément de phrase (CP).',
 '{"type":"mcq","question":"Quelle est la structure minimale d''une phrase de base en français ?","options":["CD + GV","Sujet + Prédicat","CP + Sujet","Det + N + V"],"answer":"Sujet + Prédicat"}'),
('Pronom personnel sujet', 1, 20000, 'Les pronoms personnels sujets : je, tu, il, elle, on, nous, vous, ils, elles.',
 '{"type":"mcq","question":"Lequel de ces pronoms est un pronom personnel sujet ?","options":["me","lui","elles","leur"],"answer":"elles"}'),
('Déterminant possessif', 1, 20000, 'Les déterminants possessifs : mon, ma, mes, ton, ta, tes, son, sa, ses, notre, votre, leur, leurs.',
 '{"type":"mcq","question":"Lequel est un déterminant possessif ?","options":["ce","leurs","des","le"],"answer":"leurs"}'),
('Déterminant démonstratif', 1, 20000, 'Les déterminants démonstratifs : ce, cet, cette, ces. Ils désignent ce dont on parle.',
 '{"type":"mcq","question":"Lequel est un déterminant démonstratif ?","options":["un","mon","ces","les"],"answer":"ces"}'),
('Complément du nom', 1, 25000, 'Le complément du nom est un groupe qui complète un nom. Il est souvent introduit par « de » ou une autre préposition.',
 '{"type":"mcq","question":"Dans « le livre de mon ami », quel est le complément du nom « livre » ?","options":["mon ami","de mon ami","le livre","ami"],"answer":"de mon ami"}'),
('Subordonnée relative', 1, 25000, 'La subordonnée relative commence par un pronom relatif (qui, que, dont, où) et complète un nom.',
 '{"type":"mcq","question":"Dans « La fille qui chante est ma sœur », à quoi sert « qui chante » ?","options":["C''est le sujet","C''est une subordonnée relative","C''est le complément de phrase","C''est le prédicat"],"answer":"C''est une subordonnée relative"}'),
('Accord participe passé avec être', 1, 30000, 'Avec l''auxiliaire être, le participe passé s''accorde avec le sujet.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Elle est parti.","Elle est partie.","Elle est partis.","Elle est partié."],"answer":"Elle est partie."}'),
('Accord participe passé avec avoir', 1, 30000, 'Avec l''auxiliaire avoir, le participe passé ne s''accorde pas avec le sujet mais avec le CD si celui-ci est placé avant le verbe.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Ils ont mangée la pizza.","Ils ont mangés la pizza.","Ils ont mangé la pizza.","Ils ont mangées la pizza."],"answer":"Ils ont mangé la pizza."}'),
('Négation complète', 1, 20000, 'La négation complète nécessite deux éléments : ne (n'') + pas (jamais, plus, rien, personne…).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correctement niée ?","options":["Il mange pas.","Il ne mange pas.","Il pas mange.","Ne il mange."],"answer":"Il ne mange pas."}'),
('Ponctuation virgule énumération', 1, 20000, 'On utilise la virgule pour séparer les éléments d''une énumération.',
 '{"type":"mcq","question":"Laquelle utilise correctement la virgule dans une énumération ?","options":["J''aime les chats, les chiens et les oiseaux.","J''aime les chats les chiens, et les oiseaux.","J''aime, les chats, les chiens et les oiseaux.","J''aime les chats, les chiens, et, les oiseaux."],"answer":"J''aime les chats, les chiens et les oiseaux."}'),
('Manipulations syntaxiques — déplacement', 2, 35000, 'Le CP est un constituant qu''on peut déplacer. Si on peut le mettre en début ou en fin de phrase, c''est un CP.',
 '{"type":"mcq","question":"Dans la phrase « Les élèves ont bien travaillé hier », comment vérifier que « hier » est un complément de phrase ?","options":["On peut l''effacer et le déplacer","On peut le remplacer par un pronom","On peut l''accorder avec le sujet","On peut le mettre au pluriel"],"answer":"On peut l''effacer et le déplacer"}'),
('Subordonnée complétive', 2, 35000, 'La subordonnée complétive est introduite par « que » et joue le rôle de CD du verbe principal.',
 '{"type":"mcq","question":"Dans la phrase « Je crois qu''il viendra demain », quel rôle joue « qu''il viendra demain » ?","options":["Sujet","Complément de phrase","Complément direct du verbe","Attribut du sujet"],"answer":"Complément direct du verbe"}'),
('Pronoms relatifs qui vs que', 2, 35000, '"Qui" est sujet de la subordonnée relative. "Que" est CD de la subordonnée relative.',
 '{"type":"mcq","question":"Lequel de ces choix est correct ? « C''est l''élève ___ a eu la meilleure note »","options":["que","dont","où","qui"],"answer":"qui"}'),
('Pronom relatif que', 2, 35000, '"Que" est CD de la relative : le nom remplacé est l''objet de l''action.',
 '{"type":"mcq","question":"Lequel est correct ? « C''est le livre ___ j''ai lu »","options":["qui","dont","que","lequel"],"answer":"que"}'),
('Pronom relatif dont', 2, 35000, '"Dont" remplace un nom introduit par "de" dans la subordonnée.',
 '{"type":"mcq","question":"Lequel est correct ? « C''est le projet ___ je suis fier »","options":["que","qui","dont","lequel"],"answer":"dont"}'),
('Coordination vs subordination', 2, 35000, 'La coordination relie des propositions de même niveau (et, mais, ou…). La subordination crée une hiérarchie entre propositions.',
 '{"type":"mcq","question":"Dans « Il est parti parce qu''il était fatigué », quel type de lien y a-t-il entre les deux propositions ?","options":["Coordination","Juxtaposition","Subordination","Apposition"],"answer":"Subordination"}'),
('Fonctions dans la phrase — récapitulatif', 2, 35000, 'S, CD, CI, CP, attribut du sujet sont les grandes fonctions syntaxiques à identifier.',
 '{"type":"mcq","question":"Dans la phrase « Mes amis m''offrent un cadeau pour mon anniversaire », quel est le CD ?","options":["Mes amis","m''","un cadeau","pour mon anniversaire"],"answer":"un cadeau"}'),
('Participe passé accord avec CD antéposé', 2, 40000, 'Avec avoir, si le CD est placé AVANT le verbe (pronom), le PP s''accorde. Les livres qu''il a LUS.',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte ?","options":["Les pommes qu''elle a mangé étaient bonnes.","Les pommes qu''elle a mangées étaient bonnes.","Les pommes qu''elles a mangés étaient bonnes.","Les pommes qu''elle a mangée étaient bonnes."],"answer":"Les pommes qu''elle a mangées étaient bonnes."}'),
('Verbes attributifs', 2, 35000, 'Les verbes attributifs (être, devenir, paraître, sembler, rester, demeurer) introduisent un attribut du sujet.',
 '{"type":"mcq","question":"Quel verbe est un verbe attributif dans la phrase « Elle semble fatiguée » ?","options":["Elle","semble","fatiguée","Aucun de ces mots"],"answer":"semble"}'),
('Infinitif ou participe passé', 2, 35000, 'Après un verbe conjugué + préposition (de, à), on met généralement l''infinitif (pas le PP).',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Il commence à manger.","Il commence à mangé.","Il commence à mangée.","Il commence à mangés."],"answer":"Il commence à manger."}'),
('GN expansé avec subordonnée', 2, 35000, 'On peut enrichir un GN en ajoutant une subordonnée relative, un adjectif, un complément du nom.',
 '{"type":"mcq","question":"Laquelle de ces phrases contient un GN enrichi d''une subordonnée relative ?","options":["un grand chien","le chien de mon voisin","le chien qui aboie toute la nuit","ce chien noir"],"answer":"le chien qui aboie toute la nuit"}'),
('Transformation phrase active → passive', 2, 40000, 'Passif : le CD devient sujet + être + PP + par + ancien sujet. « Le chat mange la souris » → « La souris est mangée par le chat ».',
 '{"type":"mcq","question":"Transformez à la voix passive : « Le vent renverse les arbres »","options":["Les arbres renversent le vent.","Les arbres sont renversés par le vent.","Le vent est renversé par les arbres.","Les arbres ont été renversés."],"answer":"Les arbres sont renversés par le vent."}'),
('Accord adjectif avec plusieurs noms', 2, 40000, 'Si l''adjectif qualifie plusieurs noms de genres différents, il se met au masculin pluriel.',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Un chat et une chienne noirs.","Un chat et une chienne noires.","Un chat et une chienne noir.","Un chat et une chienne noire."],"answer":"Un chat et une chienne noirs."}'),
('Position de l''adjectif', 2, 35000, 'Certains adjectifs courts changent de sens selon leur position : un grand homme (de valeur) / un homme grand (de taille).',
 '{"type":"mcq","question":"Dans « C''est un vieux médecin », que signifie la position de « vieux » avant le nom ?","options":["Il est âgé professionnellement","L''adjectif qualifie son âge","L''adjectif indique son expérience","L''adjectif est attribut"],"answer":"L''adjectif qualifie son âge"}'),
('Identification du prédicat', 2, 35000, 'Le prédicat est ce qu''on dit du sujet. Il contient le verbe et tout ce qui le suit (CD, CI, attribut, etc.).',
 '{"type":"mcq","question":"Dans la phrase « Ma sœur aime beaucoup le cinéma », quel est le prédicat ?","options":["Ma sœur","aime beaucoup le cinéma","le cinéma","aime"],"answer":"aime beaucoup le cinéma"}'),
('Subordonnée circonstancielle cause', 2, 35000, 'La subordonnée circonstancielle de cause est introduite par « parce que », « puisque », « car ».',
 '{"type":"mcq","question":"Quelle subordonnée exprime la cause ?","options":["Il travaille pour réussir.","Il travaille bien qu''il soit fatigué.","Il travaille parce qu''il aime ça.","Il travaille quand il est motivé."],"answer":"Il travaille parce qu''il aime ça."}'),
('Subordonnée circonstancielle temps', 2, 35000, 'La subordonnée de temps est introduite par quand, lorsque, avant que, après que, dès que…',
 '{"type":"mcq","question":"Laquelle est une subordonnée de temps ?","options":["Il part parce qu''il est fatigué.","Il part pour trouver du travail.","Il part quand il est prêt.","Il part bien qu''il soit occupé."],"answer":"Il part quand il est prêt."}'),
('Subordonnée concessive', 2, 35000, 'La subordonnée concessive exprime une opposition et est introduite par « bien que », « quoique » + subjonctif.',
 '{"type":"mcq","question":"Laquelle est une subordonnée concessive ?","options":["Il réussit parce qu''il travaille.","Il réussit bien qu''il soit paresseux.","Il réussit quand il le veut.","Il réussit pour impressionner ses parents."],"answer":"Il réussit bien qu''il soit paresseux."}'),
('Marqueurs de relation', 2, 35000, 'Les marqueurs de relation organisent le texte : d''abord, ensuite, enfin, cependant, donc, en effet…',
 '{"type":"mcq","question":"Quel marqueur de relation exprime une conséquence ?","options":["Cependant","D''abord","Donc","Néanmoins"],"answer":"Donc"}'),
('Type de déterminant — partitif', 2, 35000, 'Les déterminants partitifs (du, de la, des) désignent une quantité non comptable ou imprécise.',
 '{"type":"mcq","question":"Dans « Elle mange du pain et boit de l''eau », quels sont les déterminants partitifs ?","options":["Elle, l''","du, de l''","mange, boit","pain, eau"],"answer":"du, de l''"}'),
('Accord du participe passé — règle de base', 2, 35000, 'PP avec avoir : sans accord si aucun CD ou si CD placé après. PP avec être : accord avec le sujet.',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Elles sont arrivés.","Elles sont arrivé.","Elles sont arrivées.","Elles est arrivées."],"answer":"Elles sont arrivées."}'),
('Identification du GPrep', 2, 35000, 'Le groupe prépositionnel (GPrep) commence par une préposition. Il peut avoir la fonction de CI, CP, ou complément du nom.',
 '{"type":"mcq","question":"Dans « Elle pense à ses vacances », quelle est la fonction de « à ses vacances » ?","options":["Sujet","Complément direct","Complément indirect","Attribut du sujet"],"answer":"Complément indirect"}'),
('Phrase emphatique (mise en relief)', 2, 40000, 'La phrase emphatique met en relief un élément avec « C''est... qui » ou « C''est... que ».',
 '{"type":"mcq","question":"Quelle phrase met en relief le sujet « Marie » ?","options":["Marie aime la musique.","C''est Marie qui aime la musique.","C''est la musique que Marie aime.","Marie, elle aime la musique."],"answer":"C''est Marie qui aime la musique."}'),
('Pronom COD vs COI', 2, 35000, 'COD pronoms : le, la, les, me, te, se, nous, vous. COI pronoms : lui, leur, me, te, se, nous, vous.',
 '{"type":"mcq","question":"Dans « Il lui parle », « lui » est...","options":["Un COD","Un COI","Un sujet","Un CP"],"answer":"Un COI"}'),
('Déterminant numéral', 2, 30000, 'Les déterminants numéraux indiquent une quantité précise : deux, trois, cent, mille…',
 '{"type":"mcq","question":"Dans « J''ai acheté trois livres », quel est le déterminant numéral ?","options":["J''ai","acheté","trois","livres"],"answer":"trois"}'),
('Reprise pronominale', 2, 35000, 'La reprise pronominale (il, elle, ils, elles, le, la, les, lui, leur) remplace un GN déjà mentionné, assurant la cohérence du texte.',
 '{"type":"mcq","question":"Dans « Mon père est médecin. Il travaille à l''hôpital. », à quoi « Il » fait-il référence ?","options":["L''hôpital","Mon père","Le médecin","Un autre médecin"],"answer":"Mon père"}'),
('Subordonnée infinitive', 3, 50000, 'Une subordonnée infinitive a un sujet propre différent du verbe principal. « Je le vois partir » = il part (lui, pas moi).',
 '{"type":"mcq","question":"Dans « J''entends les oiseaux chanter », quelle est la fonction de « chanter » ?","options":["Attribut du sujet","CD du verbe entendre","Sujet","Subordonnée infinitive jouant le rôle de CD"],"answer":"Subordonnée infinitive jouant le rôle de CD"}'),
('Antécédent du pronom relatif', 3, 50000, 'L''antécédent du pronom relatif est le nom que le pronom remplace dans la subordonnée relative.',
 '{"type":"mcq","question":"Dans « C''est le film dont il m''a parlé qui m''a le plus plu », quel est l''antécédent de « qui » ?","options":["il","le film","dont","m''a parlé"],"answer":"le film"}'),
('Accord PP verbes pronominaux', 3, 55000, 'PP des verbes pronominaux : il s''accorde avec le sujet si le pronom est CD. Si le pronom est CI, pas d''accord.',
 '{"type":"mcq","question":"Laquelle est correcte ? « Elles ___ (se laver) les mains » (le pronom réfléchi est CI)","options":["se sont lavé les mains","se sont lavées les mains","s''est lavé les mains","se sont lavés les mains"],"answer":"se sont lavé les mains"}'),
('Discours direct et indirect', 3, 50000, 'Au discours indirect, les guillemets et les deux points disparaissent, et les pronoms changent. Le verbe peut changer de temps.',
 '{"type":"mcq","question":"Transformez au discours indirect : « Il dit : \" Je suis fatigué.\" »","options":["Il dit qu''il est fatigué.","Il dit que je suis fatigué.","Il dit : il est fatigué.","Il dit étant fatigué."],"answer":"Il dit qu''il est fatigué."}'),
('Syntaxe de la phrase complexe', 3, 55000, 'Une phrase complexe contient au moins deux propositions. On peut les identifier par le nombre de verbes conjugués.',
 '{"type":"mcq","question":"Combien de propositions contient la phrase : « Quand il pleut, je reste chez moi parce que je n''aime pas me mouiller » ?","options":["1","2","3","4"],"answer":"3"}'),
('Ellipse syntaxique', 3, 50000, 'L''ellipse supprime des éléments qui peuvent être récupérés par le contexte. « Pierre aime le sport et Paul aussi. »',
 '{"type":"mcq","question":"Dans la phrase « Pierre mange une pomme et Paul, une orange », quel élément est sous-entendu ?","options":["une pomme","aussi","mange","Paul"],"answer":"mange"}'),
('Apposition', 3, 50000, 'L''apposition est un GN placé à côté d''un autre GN pour le définir ou le préciser. Elle est souvent entre virgules.',
 '{"type":"mcq","question":"Dans « Montréal, la métropole du Québec, est une ville dynamique », quel rôle joue « la métropole du Québec » ?","options":["Sujet","Complément de phrase","Apposition","Subordonnée relative"],"answer":"Apposition"}'),
('Coordination et virgule', 3, 45000, 'Avant « et » dans une longue énumération ou devant « car, or, mais, donc, or, ni », on peut mettre une virgule.',
 '{"type":"mcq","question":"Laquelle utilise correctement la virgule avant une conjonction ?","options":["Il est venu, et il est parti.","Il est venu et, il est parti.","Il est tard, mais il travaille encore.","Il travaille, et dort peu."],"answer":"Il est tard, mais il travaille encore."}'),
('Analyse complète d''une phrase', 3, 60000, 'Phrase : « Chaque matin, ma mère prépare un délicieux repas pour toute la famille. »',
 '{"type":"mcq","question":"Dans la phrase « Chaque matin, ma mère prépare un délicieux repas pour toute la famille », quel est le sujet ?","options":["Chaque matin","ma mère","prépare un délicieux repas","pour toute la famille"],"answer":"ma mère"}'),
('Erreur d''accord fréquente', 3, 50000, 'Le verbe s''accorde avec le VRAI sujet, pas avec le nom le plus proche. « Un groupe d''élèves travaille ».',
 '{"type":"mcq","question":"Laquelle de ces phrases contient l''accord correct du verbe ?","options":["La majorité des élèves sont présents.","La majorité des élèves est présente.","La majorité des élèves est présents.","La majorité des élèves sont présente."],"answer":"La majorité des élèves est présente."}'),
('Enchâssement de subordonnées', 3, 55000, 'Plusieurs subordonnées peuvent être enchâssées les unes dans les autres, créant des phrases très complexes.',
 '{"type":"mcq","question":"Dans « Je sais que tu crois qu''il viendra », combien y a-t-il de propositions subordonnées ?","options":["0","1","2","3"],"answer":"2"}'),
('Dislocation', 3, 55000, 'La dislocation est un procédé d''emphase où un GN est détaché en début ou en fin de phrase et repris par un pronom.',
 '{"type":"mcq","question":"Dans « La musique, j''en raffole », quel procédé syntaxique est utilisé ?","options":["Mise en relief par C''est...que","Dislocation à gauche","Apposition","Ellipse"],"answer":"Dislocation à gauche"}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);


-- SEC1_FRA_grammaire_supp.sql (78 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-FRA-SEC1-GR') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Identifier un nom commun', 1, 18000, 'Un nom commun désigne une réalité générique (animal, objet, personne). Il peut être précédé d''un déterminant.',
 '{"type":"mcq","question":"Lequel de ces mots est un nom commun ?","options":["courir","Montréal","chien","beau"],"answer":"chien"}'),
('Identifier un nom propre', 1, 18000, 'Un nom propre commence par une majuscule et désigne un être ou un lieu unique.',
 '{"type":"mcq","question":"Lequel de ces mots est un nom propre ?","options":["ville","fleuve","forêt","Québec"],"answer":"Québec"}'),
('Identifier un verbe', 1, 18000, 'Un verbe exprime une action ou un état. Il se conjugue selon la personne et le temps.',
 '{"type":"mcq","question":"Lequel de ces mots est un verbe ?","options":["chaud","rapidement","manger","belle"],"answer":"manger"}'),
('Identifier un adjectif qualificatif', 1, 18000, 'Un adjectif qualificatif décrit ou qualifie un nom. Il s''accorde en genre et en nombre.',
 '{"type":"mcq","question":"Lequel de ces mots est un adjectif qualificatif ?","options":["courir","très","table","grand"],"answer":"grand"}'),
('Identifier un adverbe', 1, 18000, 'Un adverbe modifie un verbe, un adjectif ou un autre adverbe. Il est invariable.',
 '{"type":"mcq","question":"Lequel de ces mots est un adverbe ?","options":["lentement","lent","lenteur","lente"],"answer":"lentement"}'),
('Identifier une préposition', 1, 18000, 'Une préposition établit un rapport entre des mots. Exemples : à, de, en, pour, par, sur.',
 '{"type":"mcq","question":"Lequel de ces mots est une préposition ?","options":["mais","cependant","dans","lorsque"],"answer":"dans"}'),
('Identifier une conjonction de coordination', 1, 18000, 'Les conjonctions de coordination sont : mais, ou, et, donc, or, ni, car.',
 '{"type":"mcq","question":"Lequel de ces mots est une conjonction de coordination ?","options":["quand","parce que","mais","bien que"],"answer":"mais"}'),
('Identifier un pronom personnel', 1, 20000, 'Les pronoms personnels : je, tu, il, elle, nous, vous, ils, elles.',
 '{"type":"mcq","question":"Dans «Il mange une pomme», quel mot est un pronom personnel ?","options":["Il","mange","une","pomme"],"answer":"Il"}'),
('Identifier le sujet d''une phrase', 1, 20000, 'Le sujet répond à «Qui/Qu''est-ce qui + verbe ?». Dans «Le chat dort», c''est «Le chat».',
 '{"type":"mcq","question":"Quel est le sujet dans la phrase «La chatte noire ronronne doucement» ?","options":["noire","La chatte noire","ronronne","doucement"],"answer":"La chatte noire"}'),
('Identifier le verbe dans une phrase', 1, 20000, 'Le verbe est le noyau du groupe verbal. Dans «Les élèves lisent», c''est «lisent».',
 '{"type":"mcq","question":"Quel est le verbe dans la phrase «Mon frère joue au soccer» ?","options":["Mon","frère","joue","soccer"],"answer":"joue"}'),
('Identifier le complément direct', 1, 22000, 'Le CD complète le verbe sans préposition. «Qui/Quoi ? + verbe» → la réponse est le CD.',
 '{"type":"mcq","question":"Dans «Marie lit un roman», quel est le complément direct ?","options":["Marie","lit","un roman","directement"],"answer":"un roman"}'),
('Accord sujet-verbe simple', 1, 20000, 'Le verbe s''accorde avec son sujet. Sujet pluriel → verbe pluriel.',
 '{"type":"mcq","question":"Quelle forme est correcte : «Les enfants _____ dans le parc» ?","options":["joue","joues","jouent","jouons"],"answer":"jouent"}'),
('Accord de l''adjectif en genre', 1, 20000, 'Un adjectif s''accorde avec le nom qu''il qualifie. Nom féminin → adjectif féminin.',
 '{"type":"mcq","question":"Quelle forme est correcte : «une maison ___»  ?","options":["grand","grande","grands","grandes"],"answer":"grande"}'),
('Accord de l''adjectif en nombre', 1, 20000, 'Nom masculin pluriel → adjectif masculin pluriel.',
 '{"type":"mcq","question":"Quelle forme est correcte : «des livres ___»  ?","options":["intéressant","intéressante","intéressants","intéressantes"],"answer":"intéressants"}'),
('Déterminant défini ou indéfini', 1, 18000, '«le, la, les» = définis (référent connu). «un, une, des» = indéfinis (référent inconnu).',
 '{"type":"mcq","question":"Dans «J''ai vu un chien», le déterminant «un» est...","options":["Défini","Indéfini","Partitif","Démonstratif"],"answer":"Indéfini"}'),
('Déterminant possessif', 1, 18000, 'Les déterminants possessifs : mon, ma, mes, ton, ta, tes, son, sa, ses, notre, votre, leur...',
 '{"type":"mcq","question":"Lequel de ces déterminants est possessif ?","options":["le","cette","mon","quelques"],"answer":"mon"}'),
('Phrase déclarative', 1, 18000, 'Une phrase déclarative énonce un fait. Elle se termine par un point.',
 '{"type":"mcq","question":"Quelle phrase est une phrase déclarative ?","options":["Ferme la porte !","Est-ce qu''il pleut ?","Il fait beau aujourd''hui.","Comme c''est magnifique !"],"answer":"Il fait beau aujourd''hui."}'),
('Phrase interrogative', 1, 18000, 'Une phrase interrogative pose une question. Elle se termine par un point d''interrogation.',
 '{"type":"mcq","question":"Quelle phrase est une phrase interrogative ?","options":["Mange tes légumes.","Quel âge as-tu ?","Quelle belle journée !","Cours plus vite."],"answer":"Quel âge as-tu ?"}'),
('Phrase exclamative', 1, 18000, 'Une phrase exclamative exprime une émotion forte. Elle se termine par un point d''exclamation.',
 '{"type":"mcq","question":"Quelle phrase est une phrase exclamative ?","options":["Viens ici.","Pourquoi pleures-tu ?","Quelle merveilleuse surprise !","Je suis fatigué."],"answer":"Quelle merveilleuse surprise !"}'),
('Phrase impérative', 1, 18000, 'Une phrase impérative exprime un ordre ou une demande. Le verbe est à l''impératif.',
 '{"type":"mcq","question":"Quelle phrase est une phrase impérative ?","options":["Tu viens maintenant.","Viens maintenant !","Pourquoi tu ne viens pas ?","Il vient maintenant."],"answer":"Viens maintenant !"}'),
('Singulier et pluriel des noms', 1, 18000, 'En général, on ajoute -s au pluriel. Exceptions : -al → -aux, -eau → -eaux...',
 '{"type":"mcq","question":"Quel est le pluriel de «chapeau» ?","options":["chapeaus","chapeaux","chapeas","chapeaues"],"answer":"chapeaux"}'),
('Féminin des noms', 1, 18000, 'En général, on ajoute -e pour former le féminin. Exceptions : -eur → -euse, -teur → -trice...',
 '{"type":"mcq","question":"Quel est le féminin de «acteur» ?","options":["acteure","acteuresse","actrice","acteuse"],"answer":"actrice"}'),
('Groupe nominal', 1, 20000, 'Un groupe nominal (GN) est constitué d''un nom et de ses expansions. Noyau = nom.',
 '{"type":"mcq","question":"Dans «la grande maison bleue», quel est le noyau du groupe nominal ?","options":["la","grande","maison","bleue"],"answer":"maison"}'),
('Groupe verbal', 1, 20000, 'Le groupe verbal (GV) contient le verbe conjugué et ses compléments.',
 '{"type":"mcq","question":"Dans «Maria mange une salade», quel est le groupe verbal ?","options":["Maria","mange","une salade","mange une salade"],"answer":"mange une salade"}'),
('Complément indirect', 1, 22000, 'Le CI complète le verbe avec une préposition. «À/de + qui/quoi ?» → réponse = CI.',
 '{"type":"mcq","question":"Dans «Il téléphone à sa mère», quel est le complément indirect ?","options":["Il","téléphone","à sa mère","sa mère"],"answer":"à sa mère"}'),
('Attribut du sujet', 1, 22000, 'L''attribut du sujet est relié au sujet par un verbe attributif (être, paraître, sembler...).',
 '{"type":"mcq","question":"Dans «Elle est médecin», quel mot est l''attribut du sujet ?","options":["Elle","est","médecin","Elle est"],"answer":"médecin"}'),
('Subordonnée relative', 2, 30000, 'Une proposition subordonnée relative est introduite par un pronom relatif (qui, que, dont, où...).',
 '{"type":"mcq","question":"Quelle proposition est une subordonnée relative ?","options":["parce qu''il pleut","que je vois là-bas","bien qu''il soit tard","afin de réussir"],"answer":"que je vois là-bas"}'),
('Pronom relatif «qui»', 2, 30000, '«Qui» est sujet de la subordonnée relative. Il reprend un antécédent animé ou inanimé.',
 '{"type":"mcq","question":"Complète : «Le livre ___ traîne sur la table est à moi.»","options":["que","dont","qui","lequel"],"answer":"qui"}'),
('Pronom relatif «que»', 2, 30000, '«Que» est complément direct de la subordonnée relative. Il reprend un antécédent animé ou inanimé.',
 '{"type":"mcq","question":"Complète : «La fleur ___ il a cueillie est une rose.»","options":["qui","dont","où","que"],"answer":"que"}'),
('Pronom relatif «dont»', 2, 30000, '«Dont» = «de qui/duquel/de laquelle...». Il reprend un complément prépositionnel avec «de».',
 '{"type":"mcq","question":"Complète : «C''est l''élève ___ je t''ai parlé.»","options":["que","qui","dont","où"],"answer":"dont"}'),
('Pronom relatif «où»', 2, 30000, '«Où» exprime le lieu ou le temps. Il remplace une indication de lieu ou de temps.',
 '{"type":"mcq","question":"Complète : «Je me souviens du jour ___ nous nous sommes rencontrés.»","options":["que","qui","dont","où"],"answer":"où"}'),
('Subordonnée causale', 2, 30000, 'La subordonnée causale exprime la cause. Conjonctions : parce que, car, puisque, comme.',
 '{"type":"mcq","question":"Quelle conjonction introduit une subordonnée causale ?","options":["afin que","bien que","parce que","pour que"],"answer":"parce que"}'),
('Subordonnée consécutive', 2, 30000, 'La subordonnée consécutive exprime la conséquence. Conjonctions : si bien que, de sorte que, tellement... que.',
 '{"type":"mcq","question":"Quelle conjonction introduit une subordonnée de conséquence ?","options":["bien que","parce que","si bien que","afin que"],"answer":"si bien que"}'),
('Subordonnée de but', 2, 30000, 'La subordonnée de but exprime le but visé. Conjonctions : pour que, afin que, de crainte que.',
 '{"type":"mcq","question":"Quelle conjonction introduit une subordonnée de but ?","options":["parce que","si bien que","afin que","alors que"],"answer":"afin que"}'),
('Subordonnée concessive', 2, 30000, 'La subordonnée concessive exprime une opposition/concession. Conjonctions : bien que, quoique, même si.',
 '{"type":"mcq","question":"Quelle conjonction introduit une subordonnée concessive ?","options":["parce que","si","afin que","bien que"],"answer":"bien que"}'),
('Accord du participe passé avec être', 2, 32000, 'Avec l''auxiliaire être, le participe passé s''accorde avec le sujet.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Les filles sont ___»","options":["parti","partie","parties","partis"],"answer":"parties"}'),
('Accord du participe passé avec avoir', 2, 32000, 'Avec l''auxiliaire avoir, le participe passé s''accorde avec le COD si celui-ci est placé avant.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Les pommes que j''ai ___ sont bonnes.»","options":["mangé","mangée","mangées","mangés"],"answer":"mangées"}'),
('Accord sans COD antéposé', 2, 30000, 'Avec avoir, si le COD est après le verbe, le participe passé reste invariable.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Nous avons ___ les devoirs.»","options":["faite","faits","fait","faites"],"answer":"fait"}'),
('Voix active et voix passive', 2, 30000, 'Voix active : sujet fait l''action. Voix passive : sujet subit l''action.',
 '{"type":"mcq","question":"Quelle phrase est à la voix passive ?","options":["Le chat attrape la souris.","La souris attrape le chat.","La souris est attrapée par le chat.","La souris fuit le chat."],"answer":"La souris est attrapée par le chat."}'),
('Transformation active → passive', 2, 32000, 'Actif : «Le jardinier plante des fleurs.» Passif : «Des fleurs sont plantées par le jardinier.»',
 '{"type":"mcq","question":"Transforme en passif : «La directrice lit les rapports.»","options":["Les rapports lisent la directrice.","Les rapports sont lus par la directrice.","La directrice est lue par les rapports.","Les rapports ont été lire par la directrice."],"answer":"Les rapports sont lus par la directrice."}'),
('Complément du nom', 2, 28000, 'Le complément du nom précise le nom. Souvent introduit par une préposition.',
 '{"type":"mcq","question":"Dans «la maison de Pierre», quel est le complément du nom ?","options":["la maison","de Pierre","Pierre","maison"],"answer":"de Pierre"}'),
('Épithète et attribut : différence', 2, 30000, 'Épithète : adjectif directement à côté du nom. Attribut : lié au sujet par un verbe attributif.',
 '{"type":"mcq","question":"Dans «Elle porte une robe magnifique», l''adjectif «magnifique» est...","options":["Attribut du sujet","Épithète du nom «robe»","Attribut du complément direct","Complément de l''adverbe"],"answer":"Épithète du nom «robe»"}'),
('Modificateur d''adjectif', 2, 28000, 'Un adverbe peut modifier un adjectif pour l''intensifier.',
 '{"type":"mcq","question":"Dans «très grand», quel mot est le modificateur de l''adjectif ?","options":["très","grand","très grand","ni l''un ni l''autre"],"answer":"très"}'),
('Pronom démonstratif', 2, 28000, 'Les pronoms démonstratifs : celui, celle, ceux, celles, ce, c''.',
 '{"type":"mcq","question":"Lequel de ces mots est un pronom démonstratif ?","options":["ce livre","cette","celui","cet"],"answer":"celui"}'),
('Pronom indéfini', 2, 28000, 'Les pronoms indéfinis : on, tout, quelqu''un, rien, personne, chacun, quelque chose...',
 '{"type":"mcq","question":"Lequel de ces mots est un pronom indéfini ?","options":["il","me","lui","quelqu''un"],"answer":"quelqu''un"}'),
('Classe des mots invariables', 2, 28000, 'Les mots invariables ne changent ni en genre ni en nombre : adverbes, prépositions, conjonctions.',
 '{"type":"mcq","question":"Lequel de ces mots est invariable ?","options":["beau","grand","rapidement","courageux"],"answer":"rapidement"}'),
('Accord adjectif épithète f. pluriel', 2, 30000, 'Adjectif qualifiant un nom féminin pluriel → féminin pluriel.',
 '{"type":"mcq","question":"Quelle forme est correcte : «des notes ___»  ?","options":["excellent","excellente","excellentes","excellents"],"answer":"excellentes"}'),
('Accord avec plusieurs noms', 2, 32000, 'Si l''adjectif qualifie plusieurs noms de genres différents, il prend le masculin pluriel.',
 '{"type":"mcq","question":"Quelle forme est correcte : «un sac et une valise ___» ?","options":["lourd","lourde","lourdement","lourds"],"answer":"lourds"}'),
('Dédoublement par «est-ce que» (interrogation)', 2, 30000, 'On peut former une phrase interrogative avec inversion ou «est-ce que». Les deux sont valides.',
 '{"type":"mcq","question":"Quelle forme interrogative correspond à «Tu aimes le chocolat» ?","options":["Est-ce que tu aimes le chocolat ?","Aimes-tu le chocolat ?","Toutes les réponses","Ni l''une ni l''autre"],"answer":"Toutes les réponses"}'),
('Complément de phrase (CP)', 2, 30000, 'Le CP est mobile et effaçable. Il indique le contexte (temps, lieu, manière, cause).',
 '{"type":"mcq","question":"Dans «Hier soir, il a plu abondamment», quel est le complément de phrase ?","options":["il","a plu","abondamment","Hier soir"],"answer":"Hier soir"}'),
('Identifier le type de groupe', 2, 30000, 'Un groupe prépositionnel (GPrép) commence par une préposition.',
 '{"type":"mcq","question":"Dans «à toute vitesse», quel type de groupe est-ce ?","options":["Groupe nominal","Groupe verbal","Groupe prépositionnel","Groupe adjectival"],"answer":"Groupe prépositionnel"}'),
('Expansion du nom : type', 2, 30000, 'Un nom peut être expansé par un adjectif (épithète), un GPrep (complément du nom) ou une subordonnée relative.',
 '{"type":"mcq","question":"Dans «l''élève studieux qui réussit», quelles sont les expansions du nom «élève» ?","options":["studieux seulement","qui réussit seulement","studieux et qui réussit","aucune expansion"],"answer":"studieux et qui réussit"}'),
('Subordonnée temporelle', 3, 42000, 'La subordonnée temporelle situe l''action dans le temps. Conjonctions : quand, lorsque, dès que, avant que, après que.',
 '{"type":"mcq","question":"Quelle conjonction introduit une subordonnée temporelle ?","options":["parce que","bien que","lorsque","pour que"],"answer":"lorsque"}'),
('Concordance des temps : passé composé + imparfait', 3, 42000, 'Action principale (passé composé) + contexte (imparfait). «Il lisait quand elle est arrivée.»',
 '{"type":"mcq","question":"Quelle phrase illustre correctement la concordance passé composé / imparfait ?","options":["Il lisait et elle arrivait","Il lira quand elle arrivait","Il lisait quand elle est arrivée","Il lisait quand elle arrivera"],"answer":"Il lisait quand elle est arrivée"}'),
('Accord du participe passé des verbes pronominaux', 3, 45000, 'Verbes pronominaux : accord avec le sujet si le pronom est COD. «Elles se sont blessées.»',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Les joueuses se sont ___»","options":["blessé","blessés","blessée","blessées"],"answer":"blessées"}'),
('Participe passé invariable : verbes pronominaux', 3, 45000, 'Si le COD vient après le verbe pronominal, pas d''accord. «Elles se sont lavé les mains.»',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Elles se sont ___ les mains.»","options":["lavée","lavées","lavé","lavés"],"answer":"lavé"}'),
('Distinguer la cause et la conséquence', 3, 42000, 'Cause → conséquence. On peut reconnaître la cause avec «parce que» et la conséquence avec «donc».',
 '{"type":"mcq","question":"Dans «Il a raté l''autobus, donc il sera en retard», quelle proposition exprime la conséquence ?","options":["Il a raté l''autobus","il sera en retard","Il a raté l''autobus, donc","Ces deux propositions expriment la cause"],"answer":"il sera en retard"}'),
('Phrase complexe vs phrase simple', 3, 42000, 'Une phrase complexe contient au moins deux propositions avec un verbe conjugué chacune.',
 '{"type":"mcq","question":"Laquelle est une phrase complexe ?","options":["Le vent souffle.","Je mange et tu lis.","Le gros chien brun dort.","Vite, dépêche-toi !"],"answer":"Je mange et tu lis."}'),
('Paraphrase de subordonnée relative', 3, 42000, 'On peut remplacer une subordonnée relative par un adjectif ou un GPrep.',
 '{"type":"mcq","question":"Quelle expression peut remplacer «la maison qui appartient à ma tante» ?","options":["la maison belle","la maison de ma tante","la belle maison","la maison grande"],"answer":"la maison de ma tante"}'),
('Discours direct vs indirect', 3, 45000, 'Discours direct : «Il a dit : ''Je suis fatigué.''» Indirect : «Il a dit qu''il était fatigué.»',
 '{"type":"mcq","question":"Transforme en discours indirect : «Elle a crié : ''Je suis heureuse !''»","options":["Elle a crié qu''elle est heureuse.","Elle a crié qu''elle était heureuse.","Elle crie qu''elle est heureuse.","Elle dit qu''elle était heureuse."],"answer":"Elle a crié qu''elle était heureuse."}'),
('Changer personne au discours indirect', 3, 45000, 'Discours indirect : «je» devient «il/elle», «tu» devient «il/elle» ou «vous».',
 '{"type":"mcq","question":"Transforme en discours indirect : «Marc dit : ''Tu devrais venir.''»","options":["Marc dit que tu devrais venir.","Marc dit qu''il devrait venir.","Marc dit que je devrais venir.","Marc dit qu''elle devrait venir."],"answer":"Marc dit qu''il devrait venir."}'),
('Fonctions syntaxiques avancées : apposition', 3, 42000, 'L''apposition est un GN qui désigne la même réalité que le nom auquel il est rattaché.',
 '{"type":"mcq","question":"Dans «Montréal, la métropole du Québec, est une ville multiculturelle», qu''est-ce que «la métropole du Québec» ?","options":["Sujet","Complément direct","Apposition","Complément de phrase"],"answer":"Apposition"}'),
('Fonction de la subordonnée relative : complément du nom', 3, 42000, 'Une subordonnée relative a la même fonction que le complément du nom.',
 '{"type":"mcq","question":"Quelle est la fonction de «qui chante bien» dans «La fille qui chante bien est ma cousine» ?","options":["Sujet","Prédicat","Complément du nom «fille»","Complément direct"],"answer":"Complément du nom «fille»"}'),
('Accord après «avoir l''air»', 3, 45000, 'Quand «avoir l''air» signifie «paraître», l''adjectif s''accorde avec le sujet. «Elle a l''air fatiguée.»',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Elle a l''air fatigué.","Elle a l''air fatiguée.","Les deux sont acceptables.","Aucune des deux."],"answer":"Les deux sont acceptables."}'),
('Accord du participe passé : sujet collectif', 3, 45000, 'Nom collectif + complément au pluriel : accord selon le sens. «La plupart des élèves sont venus.»',
 '{"type":"mcq","question":"Quelle forme est correcte ? «La plupart des élèves ___ leur examen.»","options":["a réussi","ont réussi","avaient réussi","a réussit"],"answer":"ont réussi"}'),
('Subordonnée substantive (complétive)', 3, 45000, 'La subordonnée complétive a la fonction de CD du verbe principal. «Je pense que tu as raison.»',
 '{"type":"mcq","question":"Quelle est la fonction de «qu''il viendra» dans «J''espère qu''il viendra» ?","options":["Sujet","Complément direct","Complément indirect","Complément de phrase"],"answer":"Complément direct"}'),
('Subordonnée interrogative indirecte', 3, 45000, '«Je me demande si elle viendra.» La subordonnée interrogative indirecte est un type de complétive.',
 '{"type":"mcq","question":"Quelle phrase contient une subordonnée interrogative indirecte ?","options":["Elle vient ?","Je pense qu''elle viendra.","Je me demande si elle viendra.","Vient-elle ou non ?"],"answer":"Je me demande si elle viendra."}'),
('Accord avec «ni... ni...»', 3, 45000, '«Ni... ni...» : accord au singulier si les sujets sont exclusifs, au pluriel sinon.',
 '{"type":"mcq","question":"Quelle phrase est grammaticalement correcte ?","options":["Ni Paul ni Marie n''est venu.","Ni Paul ni Marie ne sont venus.","Les deux formes sont acceptables.","Aucune des deux."],"answer":"Les deux formes sont acceptables."}'),
('Accord avec «ou»', 3, 45000, 'Sujets liés par «ou» : accord selon le contexte. Si les deux sont possibles en même temps → pluriel.',
 '{"type":"mcq","question":"Quelle phrase est correcte : «Le médecin ou l''infirmière ___ venu(e)(s) ?»","options":["est venu","est venue","est venus","est venues"],"answer":"est venue"}'),
('Reprise pronominale et antécédent', 3, 42000, 'Un pronom reprend un nom antécédent. Le pronom s''accorde en genre et nombre avec son antécédent.',
 '{"type":"mcq","question":"Dans «J''ai vu les chiens. Ils aboient.», quel est l''antécédent de «Ils» ?","options":["J''ai vu","les chiens","aboient","aucun antécédent"],"answer":"les chiens"}'),
('Infinitif ou participe passé ?', 3, 45000, 'Après un auxiliaire (avoir/être) → participe passé. Après un autre verbe → infinitif.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «J''ai ___ une lettre.»","options":["écrire","écrit","écris","écrira"],"answer":"écrit"}'),
('Ambiguïté syntaxique', 3, 45000, 'Une phrase est ambiguë quand elle peut avoir deux interprétations selon la structure syntaxique.',
 '{"type":"mcq","question":"La phrase «Il a vu l''homme avec les jumelles» est ambiguë. Pourquoi ?","options":["Parce que «jumelles» peut signifier plusieurs choses","On ne sait pas qui avait les jumelles, lui ou l''homme","Parce que «vu» peut être au passé ou présent","Aucune ambiguïté"],"answer":"On ne sait pas qui avait les jumelles, lui ou l''homme"}'),
('Néologisme et emprunt', 3, 40000, 'Un néologisme est un mot nouveau. Un emprunt vient d''une autre langue.',
 '{"type":"mcq","question":"Le mot «courriel» est un exemple de...","options":["Emprunt à l''anglais","Néologisme québécois remplaçant \"e-mail\"","Archaïsme","Régionalisme"],"answer":"Néologisme québécois remplaçant \"e-mail\""}'),
('Fonction du groupe infinitif', 3, 42000, 'Un groupe infinitif peut avoir la fonction de sujet, CD, CI ou complément de phrase.',
 '{"type":"mcq","question":"Dans «Apprendre est enrichissant», quel est le rôle de «Apprendre» ?","options":["Verbe conjugué","Sujet de «est»","Complément direct","Attribut"],"answer":"Sujet de «est»"}'),
('Pronom relatif composé', 3, 45000, 'Les pronoms relatifs composés : lequel, laquelle, lesquels, lesquelles, duquel...',
 '{"type":"mcq","question":"Lequel de ces mots est un pronom relatif composé ?","options":["qui","que","dont","lequel"],"answer":"lequel"}'),
('Phrase emphatique', 3, 42000, 'La phrase emphatique met en relief un élément. «C''est Marie qui chante.» ou «La leçon, elle l''a apprise.»',
 '{"type":"mcq","question":"Laquelle est une phrase emphatique (mise en relief) ?","options":["Marie chante.","C''est Marie qui chante.","Marie a chanté.","Marie ne chante pas."],"answer":"C''est Marie qui chante."}'),
('Attribut du complément direct', 3, 45000, 'L''attribut du CD qualifie le CD par un verbe comme «trouver, nommer, élire, appeler».',
 '{"type":"mcq","question":"Dans «Ils ont élu Marie présidente», quel est l''attribut du complément direct ?","options":["Marie","présidente","ont élu","Ils"],"answer":"présidente"}'),
('Analyse syntaxique complète d''une phrase', 3, 45000, 'Phrase : «Ce matin, la petite fille a mangé une pomme rouge.»  Sujet = «la petite fille», prédicat = «a mangé une pomme rouge», CP = «Ce matin».',
 '{"type":"mcq","question":"Dans «Ce matin, la petite fille a mangé une pomme rouge», quel est le complément de phrase ?","options":["la petite fille","a mangé","une pomme rouge","Ce matin"],"answer":"Ce matin"}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);

COMMIT;
-- Total : 150 questions pour FRA_grammaire
