-- ============================================================
-- IMPORT — FRA_conjugaison | PFEQ-FRA-SEC1-CONJ
-- À exécuter dans Supabase → SQL Editor → Run
-- ============================================================
BEGIN;

-- SEC1_FRA_conjugaison.sql (71 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-FRA-SEC1-CONJ') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Présent indicatif — parler', 1, 20000, 'PARLER au présent : je parle, tu parles, il parle, nous parlons, vous parlez, ils parlent.',
 '{"type":"mcq","question":"Conjugue le verbe PARLER à la 3e personne du pluriel, présent de l''indicatif.","options":["ils parle","ils parlent","ils parlons","ils parlez"],"answer":"ils parlent"}'),
('Présent indicatif — finir', 1, 20000, 'FINIR au présent : je finis, tu finis, il finit, nous finissons, vous finissez, ils finissent.',
 '{"type":"mcq","question":"Conjugue le verbe FINIR à la 1re personne du pluriel, présent de l''indicatif.","options":["nous finissons","nous finissez","nous finissent","nous finissons-là"],"answer":"nous finissons"}'),
('Présent indicatif — être', 1, 20000, 'ÊTRE au présent : je suis, tu es, il est, nous sommes, vous êtes, ils sont.',
 '{"type":"mcq","question":"Conjugue le verbe ÊTRE à la 2e personne du singulier, présent de l''indicatif.","options":["tu as","tu es","tu ais","tu aies"],"answer":"tu es"}'),
('Présent indicatif — avoir', 1, 20000, 'AVOIR au présent : j''ai, tu as, il a, nous avons, vous avez, ils ont.',
 '{"type":"mcq","question":"Conjugue le verbe AVOIR à la 3e personne du singulier, présent de l''indicatif.","options":["il as","il est","il a","il ave"],"answer":"il a"}'),
('Présent indicatif — aller', 1, 20000, 'ALLER est irrégulier : je vais, tu vas, il va, nous allons, vous allez, ils vont.',
 '{"type":"mcq","question":"Conjugue le verbe ALLER à la 1re personne du singulier, présent de l''indicatif.","options":["je alle","je vas","je vais","j''allons"],"answer":"je vais"}'),
('Imparfait — parler', 1, 25000, 'PARLER à l''imparfait : je parlais, tu parlais, il parlait, nous parlions, vous parliez, ils parlaient.',
 '{"type":"mcq","question":"Conjugue PARLER à la 3e personne du singulier, imparfait de l''indicatif.","options":["il parlait","il parle","il parlera","il parla"],"answer":"il parlait"}'),
('Imparfait — être', 1, 25000, 'ÊTRE à l''imparfait : j''étais, tu étais, il était, nous étions, vous étiez, ils étaient.',
 '{"type":"mcq","question":"Conjugue ÊTRE à la 1re personne du singulier, imparfait de l''indicatif.","options":["j''était","j''étais","j''ai été","j''ères"],"answer":"j''étais"}'),
('Imparfait — avoir', 1, 25000, 'AVOIR à l''imparfait : j''avais, tu avais, il avait, nous avions, vous aviez, ils avaient.',
 '{"type":"mcq","question":"Conjugue AVOIR à la 3e personne du pluriel, imparfait de l''indicatif.","options":["ils avaient","ils avons","ils ont","ils avaient-là"],"answer":"ils avaient"}'),
('Futur simple — parler', 1, 25000, 'PARLER au futur : je parlerai, tu parleras, il parlera, nous parlerons, vous parlerez, ils parleront.',
 '{"type":"mcq","question":"Conjugue PARLER à la 2e personne du singulier, futur simple.","options":["tu parlais","tu parle","tu parleras","tu parlera"],"answer":"tu parleras"}'),
('Futur simple — être', 1, 25000, 'ÊTRE au futur : je serai, tu seras, il sera, nous serons, vous serez, ils seront.',
 '{"type":"mcq","question":"Conjugue ÊTRE à la 1re personne du pluriel, futur simple.","options":["nous serons","nous serez","nous étions","nous serions"],"answer":"nous serons"}'),
('Futur simple — avoir', 1, 25000, 'AVOIR au futur : j''aurai, tu auras, il aura, nous aurons, vous aurez, ils auront.',
 '{"type":"mcq","question":"Conjugue AVOIR à la 2e personne du pluriel, futur simple.","options":["vous aviez","vous aurez","vous aurait","vous avons"],"answer":"vous aurez"}'),
('Conditionnel présent — parler', 1, 30000, 'PARLER au conditionnel : je parlerais, tu parlerais, il parlerait, nous parlerions, vous parleriez, ils parleraient.',
 '{"type":"mcq","question":"Conjugue PARLER à la 3e personne du singulier, conditionnel présent.","options":["il parlerait","il parlait","il parlera","il parle"],"answer":"il parlerait"}'),
('Passé composé avec avoir', 1, 25000, 'Passé composé = avoir conjugué au présent + participe passé du verbe.',
 '{"type":"mcq","question":"Conjugue MANGER au passé composé, 1re personne du singulier.","options":["j''ai mangé","j''ai mangée","j''avais mangé","j''aurais mangé"],"answer":"j''ai mangé"}'),
('Passé composé avec être', 1, 25000, 'Les verbes de mouvement et les pronominaux se conjuguent avec être. Le PP s''accorde avec le sujet.',
 '{"type":"mcq","question":"Conjugue PARTIR au passé composé, 3e personne du singulier féminin.","options":["elle a partie","elle est partie","elle est parti","elle a parti"],"answer":"elle est partie"}'),
('Présent — verbe en -er irrégulier (appeler)', 1, 25000, 'APPELER double le L devant une terminaison muette : j''appelle, tu appelles, il appelle, nous appelons, vous appelez, ils appellent.',
 '{"type":"mcq","question":"Conjugue APPELER à la 1re personne du singulier, présent de l''indicatif.","options":["j''apele","j''appel","j''appelle","j''appels"],"answer":"j''appelle"}'),
('Présent — vouloir', 1, 25000, 'VOULOIR au présent : je veux, tu veux, il veut, nous voulons, vous voulez, ils veulent.',
 '{"type":"mcq","question":"Conjugue VOULOIR à la 3e personne du pluriel, présent de l''indicatif.","options":["ils voulons","ils veulent","ils voulaient","ils veulez"],"answer":"ils veulent"}'),
('Présent — pouvoir', 1, 25000, 'POUVOIR au présent : je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent.',
 '{"type":"mcq","question":"Conjugue POUVOIR à la 3e personne du singulier, présent de l''indicatif.","options":["il pouvait","il peux","il peut","il pouvoir"],"answer":"il peut"}'),
('Présent — savoir', 1, 25000, 'SAVOIR au présent : je sais, tu sais, il sait, nous savons, vous savez, ils savent.',
 '{"type":"mcq","question":"Conjugue SAVOIR à la 1re personne du singulier, présent de l''indicatif.","options":["je savais","je suis","je sait","je sais"],"answer":"je sais"}'),
('Présent — faire', 1, 25000, 'FAIRE au présent : je fais, tu fais, il fait, nous faisons, vous faites, ils font.',
 '{"type":"mcq","question":"Conjugue FAIRE à la 2e personne du pluriel, présent de l''indicatif.","options":["vous faisez","vous faites","vous font","vous faisons"],"answer":"vous faites"}'),
('Présent — venir', 1, 25000, 'VENIR au présent : je viens, tu viens, il vient, nous venons, vous venez, ils viennent.',
 '{"type":"mcq","question":"Conjugue VENIR à la 3e personne du pluriel, présent de l''indicatif.","options":["ils venons","ils venaient","ils viennent","ils venez"],"answer":"ils viennent"}'),
('Présent — prendre', 1, 25000, 'PRENDRE au présent : je prends, tu prends, il prend, nous prenons, vous prenez, ils prennent.',
 '{"type":"mcq","question":"Conjugue PRENDRE à la 1re personne du singulier, présent de l''indicatif.","options":["je prende","je prend","je prends","je prenons"],"answer":"je prends"}'),
('Imparfait — finir', 1, 25000, 'FINIR à l''imparfait : je finissais, tu finissais, il finissait, nous finissions, vous finissiez, ils finissaient.',
 '{"type":"mcq","question":"Conjugue FINIR à la 3e personne du pluriel, imparfait de l''indicatif.","options":["ils finissaient","ils finissent","ils finissaient-là","ils finissons"],"answer":"ils finissaient"}'),
('Futur — aller', 1, 25000, 'ALLER au futur : j''irai, tu iras, il ira, nous irons, vous irez, ils iront.',
 '{"type":"mcq","question":"Conjugue ALLER à la 1re personne du singulier, futur simple.","options":["j''allerai","j''irai","j''irarai","j''allais"],"answer":"j''irai"}'),
('Futur — venir', 1, 25000, 'VENIR au futur : je viendrai, tu viendras, il viendra, nous viendrons, vous viendrez, ils viendront.',
 '{"type":"mcq","question":"Conjugue VENIR à la 3e personne du singulier, futur simple.","options":["il venira","il viendra","il venait","il venira"],"answer":"il viendra"}'),
('Passé composé — faire', 1, 25000, 'Participe passé de FAIRE = fait. Auxiliaire avoir.',
 '{"type":"mcq","question":"Conjugue FAIRE au passé composé, 3e personne du pluriel.","options":["ils ont fait","ils ont fais","ils ont faits","ils ont faire"],"answer":"ils ont fait"}'),
('Passé composé — venir', 1, 25000, 'VENIR se conjugue avec être au passé composé. PP : venu(e)(s).',
 '{"type":"mcq","question":"Conjugue VENIR au passé composé, 1re personne du singulier (masculin).","options":["je suis venu","j''ai venu","je suis venus","j''ai venu"],"answer":"je suis venu"}'),
('Identifier le temps d''un verbe', 1, 20000, 'Les terminaisons -ait, -aient signalent l''imparfait. Les terminaisons -ai, -as signalent le futur.',
 '{"type":"mcq","question":"À quel temps est le verbe souligné : « Elles CHANTAIENT joyeusement » ?","options":["Présent","Imparfait","Futur","Passé composé"],"answer":"Imparfait"}'),
('Identifier le temps — futur', 1, 20000, 'Terminaison -ons au présent (nous parlons) ou -erons au futur (nous parlerons).',
 '{"type":"mcq","question":"À quel temps est conjugué le verbe : « Nous ARRIVERONS demain » ?","options":["Présent","Imparfait","Futur simple","Conditionnel"],"answer":"Futur simple"}'),
('Impératif présent', 1, 25000, 'L''impératif n''existe qu''à 3 personnes : 2e sing., 1re pl., 2e pl. Le -s de la 2e sing. disparaît pour les verbes en -er.',
 '{"type":"mcq","question":"Conjugue PARLER à l''impératif présent, 2e personne du singulier.","options":["Parles","Parlons","Parle","Parlez"],"answer":"Parle"}'),
('Impératif présent — pluriel', 1, 25000, 'MANGER à l''impératif, 2e personne du pluriel = Mangez.',
 '{"type":"mcq","question":"Conjugue MANGER à l''impératif présent, 2e personne du pluriel.","options":["Mangez","Mangeons","Mange","Mangent"],"answer":"Mangez"}'),
('Infinitif — identifier', 1, 20000, 'L''infinitif est la forme non conjuguée du verbe. Il ne varie pas en personne.',
 '{"type":"mcq","question":"Lequel de ces verbes est à l''infinitif ?","options":["il mange","nous mangeons","manger","il mangera"],"answer":"manger"}'),
('Participe présent', 1, 25000, 'Le participe présent se forme avec le radical de nous au présent + -ant. Mangeons → mangeant.',
 '{"type":"mcq","question":"Quel est le participe présent du verbe CHANTER ?","options":["chantant","chanté","chantait","chantés"],"answer":"chantant"}'),
('Passé simple introduction', 1, 30000, 'Le passé simple s''utilise à l''écrit pour des actions passées et délimitées. -er → -a (sing.), -èrent (pl. 3e).',
 '{"type":"mcq","question":"À quel temps est le verbe dans : « Le roi parla à la foule » ?","options":["Imparfait","Passé composé","Passé simple","Plus-que-parfait"],"answer":"Passé simple"}'),
('Conditionnel présent — être', 1, 30000, 'ÊTRE au conditionnel : je serais, tu serais, il serait, nous serions, vous seriez, ils seraient.',
 '{"type":"mcq","question":"Conjugue ÊTRE à la 1re personne du singulier, conditionnel présent.","options":["je serai","j''étais","je serais","je sois"],"answer":"je serais"}'),
('Plus-que-parfait formation', 2, 35000, 'Plus-que-parfait = imparfait d''avoir ou être + participe passé. Il exprime une action antérieure à une autre au passé.',
 '{"type":"mcq","question":"Conjugue MANGER au plus-que-parfait, 1re personne du singulier.","options":["j''ai mangé","j''avais mangé","j''aurais mangé","j''eus mangé"],"answer":"j''avais mangé"}'),
('Plus-que-parfait — sens', 2, 35000, 'Le plus-que-parfait exprime une action passée AVANT une autre action passée.',
 '{"type":"mcq","question":"Dans « Quand il est arrivé, elle AVAIT DÉJÀ MANGÉ », que signifie le plus-que-parfait ?","options":["Elle mange après lui","Elle a mangé avant lui","Elle mangeait en même temps","Elle mangera plus tard"],"answer":"Elle a mangé avant lui"}'),
('Futur antérieur formation', 2, 35000, 'Futur antérieur = futur de avoir/être + participe passé. Exprime une action future AVANT une autre action future.',
 '{"type":"mcq","question":"Conjugue PARTIR au futur antérieur, 3e personne du singulier féminin.","options":["elle sera partie","elle aura parti","elle est partie","elle sera partis"],"answer":"elle sera partie"}'),
('Conditionnel passé formation', 2, 35000, 'Conditionnel passé = conditionnel présent d''avoir/être + participe passé.',
 '{"type":"mcq","question":"Conjugue VENIR au conditionnel passé, 1re personne du singulier.","options":["je serais venu","je suis venu","je serai venu","j''aurais venu"],"answer":"je serais venu"}'),
('Subjonctif présent — regular verb', 2, 40000, 'PARLER au subjonctif : que je parle, que tu parles, qu''il parle, que nous parlions, que vous parliez, qu''ils parlent.',
 '{"type":"mcq","question":"Conjugue PARLER au subjonctif présent, 1re personne du pluriel.","options":["que nous parlons","que nous parlions","que nous parlez","que nous parlent"],"answer":"que nous parlions"}'),
('Subjonctif présent — être', 2, 40000, 'ÊTRE au subjonctif : que je sois, que tu sois, qu''il soit, que nous soyons, que vous soyez, qu''ils soient.',
 '{"type":"mcq","question":"Conjugue ÊTRE au subjonctif présent, 3e personne du singulier.","options":["qu''il est","qu''il soit","qu''il sera","qu''il ait"],"answer":"qu''il soit"}'),
('Subjonctif présent — avoir', 2, 40000, 'AVOIR au subjonctif : que j''aie, que tu aies, qu''il ait, que nous ayons, que vous ayez, qu''ils aient.',
 '{"type":"mcq","question":"Conjugue AVOIR au subjonctif présent, 1re personne du pluriel.","options":["que nous avons","que nous aurons","que nous ayons","que nous avons"],"answer":"que nous ayons"}'),
('Emploi du subjonctif', 2, 40000, 'Le subjonctif est requis après des verbes de volonté (vouloir que), d''émotion, de doute, et certaines conjonctions (bien que, pour que, avant que).',
 '{"type":"mcq","question":"Dans laquelle de ces phrases doit-on utiliser le subjonctif ?","options":["Je crois qu''il vient.","Il est certain qu''elle réussit.","Je veux qu''il vienne.","Je sais qu''il partira."],"answer":"Je veux qu''il vienne."}'),
('Concordance des temps — présent', 2, 40000, 'Si le verbe principal est au présent, le verbe subordonné peut être au présent (simultané), passé composé (antériorité) ou futur (postériorité).',
 '{"type":"mcq","question":"Laquelle de ces phrases est correcte selon la concordance des temps ?","options":["Je crois qu''il venait hier.","Je crois qu''il est venu hier.","Je crois qu''il viendrait hier.","Je crois qu''il venait demain."],"answer":"Je crois qu''il est venu hier."}'),
('Concordance des temps — passé', 2, 40000, 'Si le verbe principal est au passé, la subordonnée utilise l''imparfait (simultané) ou le plus-que-parfait (antériorité).',
 '{"type":"mcq","question":"Laquelle est correcte ? « Il savait que Marie ___ déjà »","options":["est partie","était partie","sera partie","avait été partait"],"answer":"était partie"}'),
('Passé récent', 2, 30000, 'Le passé récent se forme avec VENIR DE + infinitif. Il exprime une action qui vient de se produire.',
 '{"type":"mcq","question":"Comment exprimer le passé récent : « Elle vient de finir son travail » ?","options":["Elle finissait son travail.","Elle a fini son travail.","Elle vient de finir son travail.","Elle finira son travail."],"answer":"Elle vient de finir son travail."}'),
('Futur proche', 2, 30000, 'Le futur proche se forme avec ALLER (conjugué) + infinitif. Il exprime une action imminente.',
 '{"type":"mcq","question":"Lequel exprime un futur proche ?","options":["Il parte bientôt.","Il partira bientôt.","Il va partir bientôt.","Il part bientôt."],"answer":"Il va partir bientôt."}'),
('Choix imparfait vs passé composé', 2, 40000, 'Imparfait : action habituelle ou en cours. Passé composé : action ponctuelle et terminée.',
 '{"type":"mcq","question":"Quelle est la bonne phrase pour une action habituellement répétée dans le passé ?","options":["Chaque été, il a nagé dans le lac.","Chaque été, il nageait dans le lac.","Chaque été, il nagea dans le lac.","Chaque été, il nageon dans le lac."],"answer":"Chaque été, il nageait dans le lac."}'),
('Choix imparfait vs passé composé 2', 2, 40000, 'Pour une action ponctuelle qui interrompt une autre action : passé composé (l''interruption) + imparfait (l''arrière-plan).',
 '{"type":"mcq","question":"Laquelle est la phrase la mieux construite ?","options":["Quand il est entré, elle dormait.","Quand il entrait, elle a dormi.","Quand il entrait, elle dormait.","Quand il est entré, elle a dormi."],"answer":"Quand il est entré, elle dormait."}'),
('Passé simple — -ir', 2, 40000, 'FINIR au passé simple : je finis, tu finis, il finit, nous finîmes, vous finîtes, ils finirent.',
 '{"type":"mcq","question":"Conjugue FINIR au passé simple, 3e personne du pluriel.","options":["ils finissaient","ils finirent","ils ont fini","ils finit"],"answer":"ils finirent"}'),
('Passé simple — verbes irréguliers', 2, 40000, 'ÊTRE au passé simple : je fus, tu fus, il fut, nous fûmes, vous fûtes, ils furent.',
 '{"type":"mcq","question":"Conjugue ÊTRE au passé simple, 3e personne du singulier.","options":["il était","il a été","il fut","il sera"],"answer":"il fut"}'),
('Participe passé — -ir et -re', 2, 35000, 'Participes passés : finir → fini; vendre → vendu; prendre → pris; mettre → mis; voir → vu.',
 '{"type":"mcq","question":"Quel est le participe passé du verbe PRENDRE ?","options":["prendu","prenu","pris","prant"],"answer":"pris"}'),
('Participe passé — verbes irréguliers', 2, 35000, 'Participes irréguliers : être → été; avoir → eu; faire → fait; voir → vu; vouloir → voulu.',
 '{"type":"mcq","question":"Quel est le participe passé du verbe VOIR ?","options":["voyé","voiu","vu","vut"],"answer":"vu"}'),
('Emploi du conditionnel', 2, 35000, 'Le conditionnel s''emploie pour une action hypothétique, une demande polie ou une information non confirmée.',
 '{"type":"mcq","question":"Dans laquelle de ces phrases le conditionnel est-il correctement utilisé ?","options":["Si tu travailles, tu réussiras.","Si tu travaillais, tu réussirais.","Si tu travaillais, tu réussiras.","Si tu travailleras, tu réussiras."],"answer":"Si tu travaillais, tu réussirais."}'),
('Forme pronominale', 2, 35000, 'Les verbes pronominaux se conjuguent avec un pronom réfléchi (me, te, se, nous, vous, se).',
 '{"type":"mcq","question":"Conjugue SE LEVER au présent, 3e personne du singulier.","options":["il se lève","il lève","il se lèvent","il se lever"],"answer":"il se lève"}'),
('Passé composé pronominal', 2, 35000, 'Les verbes pronominaux se conjuguent avec ÊTRE au passé composé.',
 '{"type":"mcq","question":"Conjugue SE LAVER au passé composé, 3e personne du pluriel féminin.","options":["elles ont lavées","elles se sont lavé","elles se sont lavées","elles s''ont lavées"],"answer":"elles se sont lavées"}'),
('Accord PP pronominal', 2, 40000, 'PP des pronominaux réfléchis : accord avec le pronom sujet si le pronom est CD. Mais s''il est CI : pas d''accord.',
 '{"type":"mcq","question":"« Elles se sont ÉCRIT des lettres. » Pourquoi le PP « écrit » ne prend-il pas la marque du féminin ?","options":["Parce que c''est un verbe d''état","Parce que le pronom « se » est CI (à elle-même)","Parce que le verbe est irrégulier","Parce que l''auxiliaire est avoir"],"answer":"Parce que le pronom « se » est CI (à elle-même)"}'),
('Emploi du subjonctif — conjonctions', 2, 40000, 'Les conjonctions qui exigent le subjonctif : bien que, pour que, avant que, à moins que, afin que, quoique.',
 '{"type":"mcq","question":"Laquelle de ces conjonctions exige le subjonctif ?","options":["parce que","puisque","bien que","depuis que"],"answer":"bien que"}'),
('Verbe defectif — falloir', 2, 35000, 'FALLOIR est un verbe impersonnel (il faut, il fallait, il faudra, il faudrait, qu''il faille).',
 '{"type":"mcq","question":"Conjugue FALLOIR au présent de l''indicatif.","options":["je faux","il faut","vous fallez","ils fallent"],"answer":"il faut"}'),
('Subjonctif vs indicatif — verbes de pensée', 3, 50000, 'Verbes de pensée à l''affirmatif → indicatif. Verbes de pensée à la forme négative ou interrogative → subjonctif.',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Je crois qu''il vienne.","Je ne crois pas qu''il vient.","Je ne crois pas qu''il vienne.","Je crois qu''il viendrait."],"answer":"Je ne crois pas qu''il vienne."}'),
('Futur ou conditionnel dans une condition', 3, 50000, 'Dans une phrase conditionnelle : SI + imparfait → conditionnel présent. SI + présent → futur.',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Si j''avais le temps, je viendrai.","Si j''ai le temps, je viendrais.","Si j''avais le temps, je viendrais.","Si j''aurais le temps, je viendrais."],"answer":"Si j''avais le temps, je viendrais."}'),
('Conditionnel passé dans hypothèse irréelle', 3, 55000, 'Hypothèse dans le passé : SI + plus-que-parfait → conditionnel passé.',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Si j''avais su, je serais venu.","Si j''aurais su, je serais venu.","Si j''ai su, je serai venu.","Si j''avais su, j''aurais venu."],"answer":"Si j''avais su, je serais venu."}'),
('Passé antérieur — usage littéraire', 3, 50000, 'Le passé antérieur s''emploie dans les propositions subordonnées temporelles après des conjonctions comme « quand, lorsque, dès que » pour une action antérieure au passé simple.',
 '{"type":"mcq","question":"Dans quel temps est conjugué le verbe dans « Quand il EUT FINI, il repartit » ?","options":["Imparfait","Plus-que-parfait","Passé antérieur","Conditionnel passé"],"answer":"Passé antérieur"}'),
('Infinitif passé', 3, 50000, 'L''infinitif passé = avoir/être + participe passé. Exprime une action antérieure à une autre.',
 '{"type":"mcq","question":"Laquelle est correcte ? « Après ___ son travail, il est sorti »","options":["avoir fini","finir","avoir finit","finir de"],"answer":"avoir fini"}'),
('Gérondif', 3, 50000, 'Le gérondif = en + participe présent. Il exprime la simultanéité ou la manière.',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["En marchant, il réfléchissait.","En marché, il réfléchissait.","En marchera, il réfléchissait.","En avoir marché, il réfléchissait."],"answer":"En marchant, il réfléchissait."}'),
('Subjonctif imparfait — usage formel', 3, 55000, 'Le subjonctif imparfait s''utilise dans la langue soutenue quand le verbe principal est au passé.',
 '{"type":"mcq","question":"Dans la phrase soutenue « Il voulait qu''elle PARTÎT », quel temps est utilisé ?","options":["Subjonctif présent","Subjonctif imparfait","Imparfait de l''indicatif","Conditionnel présent"],"answer":"Subjonctif imparfait"}'),
('Temps du discours indirect', 3, 55000, 'Discours direct au présent → indirect imparfait. Direct passé composé → indirect plus-que-parfait. Direct futur → indirect conditionnel.',
 '{"type":"mcq","question":"Transformez : « Il a dit : \'Je partirai demain.\' » → Il a dit qu''il...","options":["partira demain","partait demain","partirait le lendemain","partît le lendemain"],"answer":"partirait le lendemain"}'),
('Erreur — emploi du subjonctif inutile', 3, 50000, 'On n''utilise pas le subjonctif après « parce que, puisque, quand, si, depuis que ».',
 '{"type":"mcq","question":"Laquelle est correcte ?","options":["Puisqu''il soit là, commençons.","Puisqu''il est là, commençons.","Puisqu''il serait là, commençons.","Puisqu''il viendrait là, commençons."],"answer":"Puisqu''il est là, commençons."}'),
('Valeur des temps narratifs', 3, 50000, 'Dans un récit littéraire, le passé simple est le temps du premier plan (actions), l''imparfait est celui du second plan (descriptions, habitudes).',
 '{"type":"mcq","question":"Dans un récit au passé, quel temps utilise-t-on pour décrire le paysage en arrière-plan ?","options":["Passé simple","Passé composé","Imparfait","Futur antérieur"],"answer":"Imparfait"}'),
('Concordance subjonctif passé', 3, 55000, 'Subjonctif passé = présent du subjonctif d''avoir/être + PP. Après verbe principal au présent, il exprime l''antériorité.',
 '{"type":"mcq","question":"Conjugue PARTIR au subjonctif passé, 3e personne du singulier féminin.","options":["qu''elle soit partie","qu''elle soit partis","qu''elle ait partie","qu''elle était partie"],"answer":"qu''elle soit partie"}'),
('Aspect perfectif vs imperfectif', 3, 55000, 'L''aspect perfectif (passé composé, passé simple) présente l''action comme achevée. L''aspect imperfectif (imparfait) présente l''action en cours.',
 '{"type":"mcq","question":"Quelle phrase présente l''action comme achevée ?","options":["Il nageait dans le lac.","Il nageait quand je l''ai vu.","Il a nagé dans le lac.","Il nage maintenant."],"answer":"Il a nagé dans le lac."}'),
('Erreur fréquente — si + conditionnel', 3, 50000, 'On ne met JAMAIS le conditionnel après « si » dans une phrase conditionnelle.',
 '{"type":"mcq","question":"Laquelle de ces phrases contient une erreur ?","options":["Si tu viens, je serai content.","Si tu venais, je serais content.","Si tu serais venu, j''aurais été content.","Si tu étais venu, j''aurais été content."],"answer":"Si tu serais venu, j''aurais été content."}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);


-- SEC1_FRA_conjugaison_supp.sql (79 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-FRA-SEC1-CONJ') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Présent de l''indicatif : être', 1, 18000, 'Conjugaison de «être» au présent : je suis, tu es, il est, nous sommes, vous êtes, ils sont.',
 '{"type":"mcq","question":"Quelle est la forme correcte de «être» à la 2e personne du singulier, présent ?","options":["suis","es","est","êtes"],"answer":"es"}'),
('Présent de l''indicatif : avoir', 1, 18000, 'Conjugaison de «avoir» au présent : j''ai, tu as, il a, nous avons, vous avez, ils ont.',
 '{"type":"mcq","question":"Quelle est la forme correcte de «avoir» à la 3e personne du pluriel, présent ?","options":["avons","avez","ont","as"],"answer":"ont"}'),
('Présent : verbe du 1er groupe en -er', 1, 18000, 'Terminaisons du 1er groupe au présent : -e, -es, -e, -ons, -ez, -ent.',
 '{"type":"mcq","question":"Conjugue «chanter» à la 3e personne du pluriel, présent.","options":["chante","chantez","chantent","chantons"],"answer":"chantent"}'),
('Présent : verbe du 2e groupe en -ir', 1, 18000, 'Terminaisons du 2e groupe au présent : -is, -is, -it, -issons, -issez, -issent.',
 '{"type":"mcq","question":"Conjugue «finir» à la 3e personne du singulier, présent.","options":["finis","finit","finissons","finissent"],"answer":"finit"}'),
('Présent : verbe «aller»', 1, 20000, '«Aller» est irrégulier : je vais, tu vas, il va, nous allons, vous allez, ils vont.',
 '{"type":"mcq","question":"Conjugue «aller» à la 1re personne du singulier, présent.","options":["alle","vas","vais","aille"],"answer":"vais"}'),
('Présent : verbe «faire»', 1, 20000, '«Faire» est irrégulier : je fais, tu fais, il fait, nous faisons, vous faites, ils font.',
 '{"type":"mcq","question":"Conjugue «faire» à la 2e personne du pluriel, présent.","options":["faisez","faites","faisons","font"],"answer":"faites"}'),
('Présent : verbe «prendre»', 1, 20000, '«Prendre» : je prends, tu prends, il prend, nous prenons, vous prenez, ils prennent.',
 '{"type":"mcq","question":"Conjugue «prendre» à la 3e personne du pluriel, présent.","options":["prennent","prends","prend","prenons"],"answer":"prennent"}'),
('Imparfait : terminaisons', 1, 20000, 'Terminaisons de l''imparfait : -ais, -ais, -ait, -ions, -iez, -aient.',
 '{"type":"mcq","question":"Quelle est la terminaison de l''imparfait à la 1re personne du pluriel ?","options":["-ais","-ait","-ions","-iez"],"answer":"-ions"}'),
('Imparfait : verbe «parler»', 1, 20000, 'Imparfait de «parler» : je parlais, tu parlais, il parlait, nous parlions, vous parliez, ils parlaient.',
 '{"type":"mcq","question":"Conjugue «parler» à la 3e personne du singulier, imparfait.","options":["parle","parlait","parlera","parlait"],"answer":"parlait"}'),
('Imparfait : verbe «être»', 1, 20000, 'Imparfait de «être» : j''étais, tu étais, il était, nous étions, vous étiez, ils étaient.',
 '{"type":"mcq","question":"Conjugue «être» à la 1re personne du singulier, imparfait.","options":["suis","serai","étais","étions"],"answer":"étais"}'),
('Futur simple : terminaisons', 1, 20000, 'Terminaisons du futur : -rai, -ras, -ra, -rons, -rez, -ront.',
 '{"type":"mcq","question":"Quelle est la terminaison du futur simple à la 3e personne du pluriel ?","options":["-rai","-ra","-rons","-ront"],"answer":"-ront"}'),
('Futur simple : verbe du 1er groupe', 1, 20000, 'Futur du 1er groupe = infinitif + terminaisons. Parler : je parlerai.',
 '{"type":"mcq","question":"Conjugue «travailler» à la 1re personne du singulier, futur simple.","options":["travaille","travaillais","travaillerai","travaillera"],"answer":"travaillerai"}'),
('Futur simple : verbe «venir»', 1, 22000, '«Venir» est irrégulier au futur : je viendrai, tu viendras, il viendra...',
 '{"type":"mcq","question":"Conjugue «venir» à la 3e personne du singulier, futur simple.","options":["vient","venait","viendra","viendr"],"answer":"viendra"}'),
('Futur simple : verbe «avoir»', 1, 22000, 'Futur de «avoir» : j''aurai, tu auras, il aura, nous aurons, vous aurez, ils auront.',
 '{"type":"mcq","question":"Conjugue «avoir» à la 2e personne du pluriel, futur simple.","options":["avez","aviez","aurez","aurons"],"answer":"aurez"}'),
('Passé composé : formation', 1, 22000, 'Passé composé = auxiliaire (avoir/être) au présent + participe passé.',
 '{"type":"mcq","question":"Quelle est la bonne formation du passé composé ?","options":["infinitif + -é","imparfait + participe passé","avoir/être au présent + participe passé","futur + participe passé"],"answer":"avoir/être au présent + participe passé"}'),
('Passé composé avec avoir : manger', 1, 22000, 'Passé composé de «manger» : j''ai mangé (auxiliaire avoir + p.p. mangé).',
 '{"type":"mcq","question":"Conjugue «manger» à la 3e personne du singulier, passé composé.","options":["il mangea","il a mangé","il avait mangé","il mange"],"answer":"il a mangé"}'),
('Passé composé avec être : partir', 1, 22000, 'Passé composé de «partir» avec être : je suis parti(e).',
 '{"type":"mcq","question":"Conjugue «partir» à la 1re personne du singulier (masculin), passé composé.","options":["j''ai parti","je suis partis","je suis parti","j''étais parti"],"answer":"je suis parti"}'),
('Verbes conjugués avec être au passé composé', 1, 20000, 'Verbes avec être au p.c. : aller, venir, partir, arriver, naître, mourir, rester, retourner...',
 '{"type":"mcq","question":"Lequel de ces verbes se conjugue avec «être» au passé composé ?","options":["manger","écrire","arriver","lire"],"answer":"arriver"}'),
('Impératif présent : 2e personne du singulier', 1, 20000, 'Impératif présent des verbes en -er : pas de «s» à la 2e personne du singulier. «Chante !» (pas «Chantes !»).',
 '{"type":"mcq","question":"Quelle est la forme correcte de l''impératif (2e personne du singulier) de «écouter» ?","options":["Écoutes !","Écoute !","Écoutes-toi !","Écoutez !"],"answer":"Écoute !"}'),
('Impératif présent : 1re personne du pluriel', 1, 20000, 'Impératif 1re personne du pluriel : terminaison -ons.',
 '{"type":"mcq","question":"Quelle est la forme correcte de l''impératif (1re pers. du pluriel) de «finir» ?","options":["Finissons !","Finissez !","Finissent !","Finissons-nous !"],"answer":"Finissons !"}'),
('Choisir l''auxiliaire : être ou avoir', 1, 22000, 'Les verbes pronominaux et certains verbes de mouvement prennent être. Les autres prennent avoir.',
 '{"type":"mcq","question":"Quel auxiliaire prend «tomber» au passé composé ?","options":["avoir","être","les deux","aucun"],"answer":"être"}'),
('Présent : verbe «pouvoir»', 1, 22000, '«Pouvoir» : je peux, tu peux, il peut, nous pouvons, vous pouvez, ils peuvent.',
 '{"type":"mcq","question":"Conjugue «pouvoir» à la 3e personne du singulier, présent.","options":["peut","peux","pouvons","peuvent"],"answer":"peut"}'),
('Présent : verbe «vouloir»', 1, 22000, '«Vouloir» : je veux, tu veux, il veut, nous voulons, vous voulez, ils veulent.',
 '{"type":"mcq","question":"Conjugue «vouloir» à la 3e personne du pluriel, présent.","options":["voulons","voulez","veulent","veut"],"answer":"veulent"}'),
('Présent : verbe «savoir»', 1, 22000, '«Savoir» : je sais, tu sais, il sait, nous savons, vous savez, ils savent.',
 '{"type":"mcq","question":"Conjugue «savoir» à la 1re personne du singulier, présent.","options":["savons","savent","sais","sait"],"answer":"sais"}'),
('Temps de base : passé, présent, futur', 1, 18000, 'Présent = maintenant. Imparfait/p.c. = passé. Futur = plus tard.',
 '{"type":"mcq","question":"Le verbe «jouait» est à quel temps ?","options":["Présent","Futur","Imparfait","Passé composé"],"answer":"Imparfait"}'),
('Reconnaître le passé composé', 1, 18000, 'Le passé composé est formé de l''auxiliaire au présent + participe passé.',
 '{"type":"mcq","question":"Quelle phrase est au passé composé ?","options":["Il chantait.","Il chantera.","Il a chanté.","Il chante."],"answer":"Il a chanté."}'),
('Plus-que-parfait : formation', 2, 30000, 'Plus-que-parfait = auxiliaire à l''imparfait + participe passé. «J''avais mangé.»',
 '{"type":"mcq","question":"Quelle est la formation du plus-que-parfait ?","options":["avoir/être au futur + p.p.","avoir/être au présent + p.p.","avoir/être à l''imparfait + p.p.","avoir/être au passé simple + p.p."],"answer":"avoir/être à l''imparfait + p.p."}'),
('Plus-que-parfait : verbe «dormir»', 2, 30000, 'P.-q.-p. de «dormir» : j''avais dormi, tu avais dormi, il avait dormi...',
 '{"type":"mcq","question":"Conjugue «dormir» à la 3e personne du singulier, plus-que-parfait.","options":["il avait dormi","il avait dormit","il avait dormi","il aura dormi"],"answer":"il avait dormi"}'),
('Futur antérieur : formation', 2, 30000, 'Futur antérieur = auxiliaire au futur + participe passé. «J''aurai fini.»',
 '{"type":"mcq","question":"Quelle est la formation du futur antérieur ?","options":["avoir/être au présent + p.p.","avoir/être au futur simple + p.p.","avoir/être à l''imparfait + p.p.","avoir/être au passé composé + p.p."],"answer":"avoir/être au futur simple + p.p."}'),
('Futur antérieur : exemple', 2, 30000, 'Futur antérieur de «manger» : j''aurai mangé.',
 '{"type":"mcq","question":"Quelle phrase illustre correctement le futur antérieur ?","options":["J''ai mangé avant.","J''aurai mangé avant qu''il arrive.","Je mangerai avant.","J''avais mangé avant."],"answer":"J''aurai mangé avant qu''il arrive."}'),
('Conditionnel présent : formation', 2, 32000, 'Conditionnel présent = infinitif + terminaisons : -rais, -rais, -rait, -rions, -riez, -raient.',
 '{"type":"mcq","question":"Quelle est la terminaison du conditionnel présent à la 3e personne du singulier ?","options":["-rait","-rais","-rons","-raient"],"answer":"-rait"}'),
('Conditionnel présent : verbe «aller»', 2, 32000, 'Conditionnel de «aller» : j''irais, tu irais, il irait, nous irions, vous iriez, ils iraient.',
 '{"type":"mcq","question":"Conjugue «aller» à la 1re personne du singulier, conditionnel présent.","options":["j''alerais","j''allais","j''irais","je vais"],"answer":"j''irais"}'),
('Conditionnel passé : formation', 2, 32000, 'Conditionnel passé = auxiliaire au conditionnel + participe passé. «J''aurais mangé.»',
 '{"type":"mcq","question":"Conjugue «partir» à la 3e personne du singulier, conditionnel passé.","options":["il partirait","il est parti","il serait parti","il sera parti"],"answer":"il serait parti"}'),
('Subjonctif présent : concept', 2, 32000, 'Le subjonctif exprime le doute, la volonté, la nécessité. «Il faut que tu viennes.»',
 '{"type":"mcq","question":"Dans quelle phrase le verbe est-il au subjonctif ?","options":["Je viens demain.","Il faut que je vienne.","Je venais souvent.","Je suis venu hier."],"answer":"Il faut que je vienne."}'),
('Subjonctif présent : terminaisons', 2, 32000, 'Terminaisons du subjonctif présent : -e, -es, -e, -ions, -iez, -ent.',
 '{"type":"mcq","question":"Quelle est la terminaison du subjonctif à la 1re personne du pluriel ?","options":["-ons","-ions","-iez","-ent"],"answer":"-ions"}'),
('Subjonctif : verbe «avoir»', 2, 32000, 'Subjonctif de «avoir» : que j''aie, que tu aies, qu''il ait, que nous ayons, que vous ayez, qu''ils aient.',
 '{"type":"mcq","question":"Conjugue «avoir» au subjonctif, 3e personne du singulier.","options":["ait","a","aie","ayons"],"answer":"ait"}'),
('Subjonctif : verbe «être»', 2, 32000, 'Subjonctif de «être» : que je sois, que tu sois, qu''il soit, que nous soyons, que vous soyez, qu''ils soient.',
 '{"type":"mcq","question":"Conjugue «être» au subjonctif, 3e personne du pluriel.","options":["sont","étaient","soient","seraient"],"answer":"soient"}'),
('Distinguer imparfait et passé composé', 2, 30000, 'Imparfait = action continue/habituelle au passé. P.c. = action ponctuelle/achevée au passé.',
 '{"type":"mcq","question":"Quelle phrase exprime une action habituelle dans le passé ?","options":["Il est tombé.","Il tombait souvent.","Il tombe.","Il tombera."],"answer":"Il tombait souvent."}'),
('Temps des verbes et contexte narratif', 2, 30000, 'Dans un récit, l''imparfait décrit le contexte et le passé composé raconte les événements.',
 '{"type":"mcq","question":"Dans «Il pleuvait quand elle est arrivée», quel temps décrit le contexte ?","options":["«est arrivée» (passé composé)","«pleuvait» (imparfait)","Les deux décrivent le contexte","Ni l''un ni l''autre"],"answer":"«pleuvait» (imparfait)"}'),
('Passé simple : forme', 2, 32000, 'Passé simple du 1er groupe : -ai, -as, -a, -âmes, -âtes, -èrent.',
 '{"type":"mcq","question":"Conjugue «chanter» à la 3e personne du singulier, passé simple.","options":["chantait","a chanté","chanta","chanterait"],"answer":"chanta"}'),
('Passé simple : verbe «venir»', 2, 32000, 'Passé simple de «venir» : je vins, tu vins, il vint, nous vînmes, vous vîntes, ils vinrent.',
 '{"type":"mcq","question":"Conjugue «venir» à la 3e personne du singulier, passé simple.","options":["venait","vint","venu","est venu"],"answer":"vint"}'),
('Futur simple : verbe «être»', 2, 28000, 'Futur de «être» : je serai, tu seras, il sera, nous serons, vous serez, ils seront.',
 '{"type":"mcq","question":"Conjugue «être» à la 3e personne du pluriel, futur simple.","options":["sont","étaient","seront","soient"],"answer":"seront"}'),
('Imparfait : verbe «avoir»', 2, 28000, 'Imparfait de «avoir» : j''avais, tu avais, il avait, nous avions, vous aviez, ils avaient.',
 '{"type":"mcq","question":"Conjugue «avoir» à la 2e personne du pluriel, imparfait.","options":["avez","aurez","aviez","ayez"],"answer":"aviez"}'),
('Verbe pronominal : se laver', 2, 30000, 'Les verbes pronominaux se conjuguent avec un pronom réfléchi : me, te, se, nous, vous, se.',
 '{"type":"mcq","question":"Conjugue «se laver» à la 3e personne du singulier, présent.","options":["il lave","il se lave","il se laves","il se lavait"],"answer":"il se lave"}'),
('Verbe pronominal au passé composé', 2, 32000, 'Les verbes pronominaux se conjuguent avec être au p.c. «Elle s''est lavée.»',
 '{"type":"mcq","question":"Conjugue «se lever» à la 3e personne du singulier (féminin), passé composé.","options":["elle a levé","elle s''est levée","elle s''est levé","elle était levée"],"answer":"elle s''est levée"}'),
('Impératif des verbes pronominaux', 2, 30000, 'Impératif des verbes pronominaux : «Lève-toi !», «Levons-nous !», «Levez-vous !»',
 '{"type":"mcq","question":"Quelle est la forme correcte de l''impératif (2e pers. sing.) de «se dépêcher» ?","options":["Dépêche !","Te dépêche !","Dépêche-toi !","Dépêches-toi !"],"answer":"Dépêche-toi !"}'),
('Présent du subjonctif après «il faut que»', 2, 30000, '«Il faut que» est toujours suivi du subjonctif.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Il faut que tu ___ ce livre.»","options":["lisas","lis","lises","lise"],"answer":"lise"}'),
('Concordance des temps : si + présent', 2, 32000, 'Avec «si» de condition : si + présent, futur. «Si tu viens, je serai là.»',
 '{"type":"mcq","question":"Quelle phrase respecte la concordance des temps ?","options":["Si tu viendras, je serai là.","Si tu viens, je serai là.","Si tu venais, je serai là.","Si tu es venu, je serai là."],"answer":"Si tu viens, je serai là."}'),
('Concordance des temps : si + imparfait', 2, 32000, 'Condition au passé : si + imparfait, conditionnel présent. «Si j''avais le temps, j''irais.»',
 '{"type":"mcq","question":"Quelle phrase respecte la concordance des temps ?","options":["Si j''aurais le temps, j''irais.","Si j''avais le temps, j''irais.","Si j''ai le temps, j''irais.","Si j''eus le temps, j''irai."],"answer":"Si j''avais le temps, j''irais."}'),
('Futur simple : verbe «faire»', 2, 28000, 'Futur de «faire» : je ferai, tu feras, il fera, nous ferons, vous ferez, ils feront.',
 '{"type":"mcq","question":"Conjugue «faire» à la 1re personne du pluriel, futur simple.","options":["ferons","faisons","ferez","font"],"answer":"ferons"}'),
('Conditionnel : valeur d''hypothèse', 2, 30000, 'Le conditionnel exprime une hypothèse ou un souhait. «Je voudrais un café.»',
 '{"type":"mcq","question":"Dans «Je voudrais aller au cinéma», le conditionnel exprime...","options":["Un fait certain","Une hypothèse/un souhait","Un ordre","Un événement passé"],"answer":"Une hypothèse/un souhait"}'),
('Reconnaître l''infinitif passé', 2, 30000, 'L''infinitif passé = avoir/être + participe passé. «Après avoir mangé, il est sorti.»',
 '{"type":"mcq","question":"Dans «Après avoir terminé ses devoirs, elle est sortie», «avoir terminé» est...","options":["Un passé composé","Un infinitif passé","Un plus-que-parfait","Un futur antérieur"],"answer":"Un infinitif passé"}'),
('Impératif négatif', 2, 30000, 'Impératif négatif : «Ne mange pas !», «Ne mangeons pas !», «Ne mangez pas !»',
 '{"type":"mcq","question":"Quelle est la forme correcte de l''impératif négatif (2e pers. sing.) de «partir» ?","options":["Ne pas pars !","Ne pars pas !","Ne partis pas !","Pas partir !"],"answer":"Ne pars pas !"}'),
('Subjonctif passé : formation', 3, 45000, 'Subjonctif passé = auxiliaire au subjonctif présent + participe passé. «Bien qu''il soit parti.»',
 '{"type":"mcq","question":"Conjugue «partir» au subjonctif passé, 3e personne du singulier.","options":["qu''il partie","qu''il soit parti","qu''il serait parti","qu''il partît"],"answer":"qu''il soit parti"}'),
('Distinguer subjonctif et indicatif', 3, 45000, 'Après «douter», «craindre», «vouloir» → subjonctif. Après «savoir», «penser» + affirmation → indicatif.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Je veux que tu viens.","Je veux que tu viennes.","Je sais que tu viennes.","Je veux que tu venais."],"answer":"Je veux que tu viennes."}'),
('Subjonctif ou indicatif après «penser que»', 3, 45000, 'À l''affirmative : «Je pense qu''il vient.» (indicatif). À la négative ou interrogative : subjonctif possible.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Je pense qu''il ___»","options":["vienne","viendrait","viendra","vienne ou viendra selon le contexte"],"answer":"viendra"}'),
('Concordance des temps : si + plus-que-parfait', 3, 45000, 'Hypothèse dans le passé : si + plus-que-parfait, conditionnel passé.',
 '{"type":"mcq","question":"Complète : «Si tu ___ étudié, tu aurais réussi.»","options":["as","avais","auras","aurais"],"answer":"avais"}'),
('Discours indirect : transposition des temps', 3, 45000, 'Passé composé du discours direct → plus-que-parfait dans le discours indirect au passé.',
 '{"type":"mcq","question":"Transforme en discours indirect : «Elle a dit : ''J''ai fini.''»","options":["Elle a dit qu''elle finit.","Elle a dit qu''elle avait fini.","Elle a dit qu''elle a fini.","Elle a dit qu''elle finira."],"answer":"Elle a dit qu''elle avait fini."}'),
('Temps littéraires : passé simple vs imparfait', 3, 42000, 'En littérature, le passé simple remplace le passé composé pour les actions ponctuelles.',
 '{"type":"mcq","question":"Dans un récit littéraire au passé, quel temps remplace généralement le passé composé ?","options":["Le plus-que-parfait","Le conditionnel","Le passé simple","Le présent historique"],"answer":"Le passé simple"}'),
('Passé simple : verbe «être»', 3, 42000, 'Passé simple de «être» : je fus, tu fus, il fut, nous fûmes, vous fûtes, ils furent.',
 '{"type":"mcq","question":"Conjugue «être» à la 3e personne du singulier, passé simple.","options":["était","fut","est","aura été"],"answer":"fut"}'),
('Passé simple : verbe «avoir»', 3, 42000, 'Passé simple de «avoir» : j''eus, tu eus, il eut, nous eûmes, vous eûtes, ils eurent.',
 '{"type":"mcq","question":"Conjugue «avoir» à la 3e personne du pluriel, passé simple.","options":["eurent","avaient","ont eu","auront"],"answer":"eurent"}'),
('Passé simple : verbe «faire»', 3, 42000, 'Passé simple de «faire» : je fis, tu fis, il fit, nous fîmes, vous fîtes, ils firent.',
 '{"type":"mcq","question":"Conjugue «faire» à la 1re personne du singulier, passé simple.","options":["faisais","ferai","fis","faisait"],"answer":"fis"}'),
('Imparfait du subjonctif : notion', 3, 45000, 'L''imparfait du subjonctif est un temps littéraire. «Bien qu''il vînt» (vînt = imparfait du subjonctif de venir).',
 '{"type":"mcq","question":"L''imparfait du subjonctif est principalement utilisé...","options":["Dans la langue parlée quotidienne","Dans les textes littéraires ou soutenu","Toujours après «il faut»","Pour exprimer le futur"],"answer":"Dans les textes littéraires ou soutenu"}'),
('Verbe «naître» au passé composé', 3, 42000, '«Naître» prend l''auxiliaire «être». Je suis né(e), tu es né(e)...',
 '{"type":"mcq","question":"Conjugue «naître» à la 3e personne du singulier (féminin), passé composé.","options":["elle a née","elle est née","elle est né","elle naissait"],"answer":"elle est née"}'),
('Verbe «mourir» au passé composé', 3, 42000, '«Mourir» prend l''auxiliaire «être». Il est mort, elle est morte.',
 '{"type":"mcq","question":"Conjugue «mourir» à la 3e personne du pluriel (masculin), passé composé.","options":["ils ont mort","ils sont morts","ils sont mortes","ils ont mouri"],"answer":"ils sont morts"}'),
('Aspect : accompli vs inaccompli', 3, 42000, 'Aspect accompli : action terminée (passé composé, futur antérieur). Inaccompli : en cours (imparfait, futur).',
 '{"type":"mcq","question":"Lequel de ces temps exprime un aspect accompli ?","options":["L''imparfait","Le futur simple","Le passé composé","Le présent"],"answer":"Le passé composé"}'),
('Valeur du présent : narration historique', 3, 42000, 'Le présent de narration (présent historique) rend un événement passé plus vivant.',
 '{"type":"mcq","question":"Dans «En 1534, Cartier arrive au Canada», le présent exprime...","options":["Une action en cours maintenant","Un fait habituel","Une action historique racontée au présent","Une hypothèse"],"answer":"Une action historique racontée au présent"}'),
('Conditionnel journalistique', 3, 42000, 'Le conditionnel journalistique exprime une information non confirmée. «Le maire démissionnerait.»',
 '{"type":"mcq","question":"Dans un article de journal : «Le premier ministre aurait décidé de démissionner.» Le conditionnel exprime...","options":["Un souhait","Une information non confirmée","Un ordre","Une hypothèse future"],"answer":"Une information non confirmée"}'),
('Mode infinitif : après une préposition', 3, 40000, 'Après une préposition (à, de, pour, sans, avant de, après avoir)  → infinitif.',
 '{"type":"mcq","question":"Quelle forme est correcte ? «Il est parti sans ___ adieu.»","options":["dit","dire","disant","dise"],"answer":"dire"}'),
('Gérondif : formation et emploi', 3, 42000, 'Gérondif = «en» + participe présent. «En chantant, elle danse.» Simultanéité.',
 '{"type":"mcq","question":"Dans «Il travaille en écoutant de la musique», le gérondif exprime...","options":["La cause","La conséquence","La simultanéité","L''opposition"],"answer":"La simultanéité"}'),
('Participe présent vs adjectif verbal', 3, 45000, 'Participe présent (invariable) : «Des enfants jouant dehors.» Adjectif verbal (variable) : «Des enfants joueurs.»',
 '{"type":"mcq","question":"Dans «Des enfants chantants», «chantants» est...","options":["Un participe présent invariable","Un adjectif verbal qui s''accorde","Un gérondif","Un infinitif"],"answer":"Un adjectif verbal qui s''accorde"}'),
('Verbe «courir» au passé composé', 3, 40000, '«Courir» se conjugue avec «avoir» au p.c. «J''ai couru.»',
 '{"type":"mcq","question":"Conjugue «courir» à la 1re personne du singulier, passé composé.","options":["je suis couru","j''ai couru","j''étais couru","je courus"],"answer":"j''ai couru"}'),
('Verbe «ouvrir» au présent', 3, 40000, '«Ouvrir» se conjugue comme un verbe du 1er groupe au présent : j''ouvre, tu ouvres, il ouvre...',
 '{"type":"mcq","question":"Conjugue «ouvrir» à la 2e personne du singulier, présent.","options":["ouvris","ouvres","ouvrez","ouvre"],"answer":"ouvres"}'),
('Verbe «résoudre» au présent', 3, 42000, '«Résoudre» : je résous, tu résous, il résout, nous résolvons, vous résolvez, ils résolvent.',
 '{"type":"mcq","question":"Conjugue «résoudre» à la 3e personne du singulier, présent.","options":["résous","résout","résolvons","résolvent"],"answer":"résout"}'),
('Verbe «vaincre» au présent', 3, 42000, '«Vaincre» : je vaincs, tu vaincs, il vainc (sans c), nous vainquons...',
 '{"type":"mcq","question":"Conjugue «vaincre» à la 3e personne du singulier, présent.","options":["vainque","vaincs","vainc","vainquit"],"answer":"vainc"}'),
('Changer de mode : subjonctif ou indicatif', 3, 45000, 'Après «croire» à la négative ou interrogative, on peut employer le subjonctif.',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Je ne crois pas qu''il vient.","Je ne crois pas qu''il vienne.","Je ne crois pas qu''il viendra.","Les formes en gras et les deux premières sont acceptables."],"answer":"Je ne crois pas qu''il vienne."}'),
('Temps du discours indirect : futur → conditionnel', 3, 45000, 'En discours indirect au passé, le futur du discours direct devient conditionnel présent.',
 '{"type":"mcq","question":"Discours direct : «Il dit : ''Je viendrai demain.''» Transforme en discours indirect (verbe intro au passé).","options":["Il dit qu''il viendra demain.","Il a dit qu''il viendrait demain.","Il a dit qu''il est venu.","Il a dit qu''il venait demain."],"answer":"Il a dit qu''il viendrait demain."}'),
('Expression de la durée avec «depuis»', 3, 42000, '«Depuis» + présent = action qui a commencé dans le passé et continue. «Il travaille depuis 3 ans.»',
 '{"type":"mcq","question":"Quelle forme est correcte avec «depuis» ? «Il ___ ce projet depuis deux ans.»","options":["a travaillé","avait travaillé","travaille","travailla"],"answer":"travaille"}'),
('Infinitif après «faire»', 3, 40000, 'Après «faire», le verbe reste à l''infinitif. «Il fait construire une maison.»',
 '{"type":"mcq","question":"Quelle phrase est correcte ?","options":["Il fait construisant une maison.","Il fait construit une maison.","Il fait construire une maison.","Il fait construction une maison."],"answer":"Il fait construire une maison."}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);

COMMIT;
-- Total : 150 questions pour FRA_conjugaison
