-- ============================================================
-- IMPORT — MAT_geometrie | PFEQ-MAT-SEC1-GEO
-- À exécuter dans Supabase → SQL Editor → Run
-- ============================================================
BEGIN;

-- SEC1_MAT_geometrie.sql (74 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-MAT-SEC1-GEO') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Périmètre carré', 1, 20000, 'Le périmètre d''un carré = 4 × côté = 4 × 5 = 20 cm.',
 '{"type":"mcq","question":"Quel est le périmètre d''un carré de côté 5 cm ?","options":["10 cm","15 cm","20 cm","25 cm"],"answer":"20 cm"}'),
('Périmètre rectangle', 1, 20000, 'Périmètre = 2 × (longueur + largeur) = 2 × (8 + 3) = 22 cm.',
 '{"type":"mcq","question":"Quel est le périmètre d''un rectangle de 8 cm × 3 cm ?","options":["11 cm","22 cm","24 cm","48 cm"],"answer":"22 cm"}'),
('Aire carré', 1, 20000, 'Aire d''un carré = côté² = 6² = 36 cm².',
 '{"type":"mcq","question":"Quelle est l''aire d''un carré de côté 6 cm ?","options":["12 cm²","24 cm²","36 cm²","48 cm²"],"answer":"36 cm²"}'),
('Aire rectangle', 1, 20000, 'Aire = longueur × largeur = 9 × 4 = 36 cm².',
 '{"type":"mcq","question":"Quelle est l''aire d''un rectangle de 9 cm × 4 cm ?","options":["13 cm²","26 cm²","32 cm²","36 cm²"],"answer":"36 cm²"}'),
('Aire triangle', 1, 25000, 'Aire d''un triangle = (base × hauteur) ÷ 2 = (10 × 6) ÷ 2 = 30 cm².',
 '{"type":"mcq","question":"Quelle est l''aire d''un triangle de base 10 cm et hauteur 6 cm ?","options":["16 cm²","30 cm²","60 cm²","120 cm²"],"answer":"30 cm²"}'),
('Angle droit', 1, 15000, 'Un angle droit mesure exactement 90°.',
 '{"type":"mcq","question":"Quelle est la mesure d''un angle droit ?","options":["45°","90°","180°","360°"],"answer":"90°"}'),
('Angle plat', 1, 15000, 'Un angle plat mesure 180° — il correspond à une ligne droite.',
 '{"type":"mcq","question":"Quelle est la mesure d''un angle plat ?","options":["90°","120°","180°","360°"],"answer":"180°"}'),
('Somme angles triangle', 1, 20000, 'La somme des angles d''un triangle est toujours 180°.',
 '{"type":"mcq","question":"Quelle est la somme des angles intérieurs d''un triangle ?","options":["90°","180°","270°","360°"],"answer":"180°"}'),
('Troisième angle triangle', 1, 25000, 'La somme des angles d''un triangle = 180°. Troisième angle = 180 - 60 - 50 = 70°.',
 '{"type":"mcq","question":"Un triangle a des angles de 60° et 50°. Quel est le troisième angle ?","options":["60°","70°","80°","90°"],"answer":"70°"}'),
('Types de triangles angles', 1, 20000, 'Un triangle rectangle a un angle de 90°. Un triangle acutangle a tous ses angles inférieurs à 90°.',
 '{"type":"mcq","question":"Comment appelle-t-on un triangle dont un angle est égal à 90° ?","options":["Acutangle","Isocèle","Rectangle","Obtusangle"],"answer":"Rectangle"}'),
('Somme angles quadrilatère', 1, 20000, 'La somme des angles d''un quadrilatère est toujours 360°.',
 '{"type":"mcq","question":"Quelle est la somme des angles intérieurs d''un quadrilatère ?","options":["180°","270°","360°","540°"],"answer":"360°"}'),
('Identifier parallèles', 1, 15000, 'Des droites parallèles ne se croisent jamais et gardent toujours la même distance entre elles.',
 '{"type":"mcq","question":"Comment appelle-t-on deux droites qui ne se croisent jamais ?","options":["Perpendiculaires","Sécantes","Parallèles","Concourantes"],"answer":"Parallèles"}'),
('Identifier perpendiculaires', 1, 15000, 'Deux droites perpendiculaires se croisent à angle droit (90°).',
 '{"type":"mcq","question":"Deux droites perpendiculaires forment un angle de...","options":["45°","60°","90°","180°"],"answer":"90°"}'),
('Rayon et diamètre cercle', 1, 15000, 'Le diamètre = 2 × rayon. Rayon = 5 cm → diamètre = 10 cm.',
 '{"type":"mcq","question":"Un cercle a un rayon de 5 cm. Quel est son diamètre ?","options":["2,5 cm","5 cm","10 cm","25 cm"],"answer":"10 cm"}'),
('Circonférence cercle approximation', 1, 25000, 'Circonférence = π × d ≈ 3,14 × 10 = 31,4 cm.',
 '{"type":"mcq","question":"Quelle est la circonférence approximative d''un cercle de diamètre 10 cm ? (π ≈ 3,14)","options":["15,7 cm","31,4 cm","62,8 cm","78,5 cm"],"answer":"31,4 cm"}'),
('Aire cercle', 1, 25000, 'Aire = π × r² ≈ 3,14 × 4² = 3,14 × 16 ≈ 50,24 cm².',
 '{"type":"mcq","question":"Quelle est l''aire approximative d''un cercle de rayon 4 cm ? (π ≈ 3,14)","options":["25,12 cm²","50,24 cm²","100,48 cm²","12,56 cm²"],"answer":"50,24 cm²"}'),
('Côtés triangle isocèle', 1, 15000, 'Un triangle isocèle a exactement deux côtés égaux.',
 '{"type":"mcq","question":"Combien de côtés égaux a un triangle isocèle ?","options":["0","1","2","3"],"answer":"2"}'),
('Triangle équilatéral angles', 1, 20000, 'Triangle équilatéral : 3 côtés égaux et 3 angles égaux. Chaque angle = 180° ÷ 3 = 60°.',
 '{"type":"mcq","question":"Quelle est la mesure de chaque angle d''un triangle équilatéral ?","options":["45°","60°","90°","120°"],"answer":"60°"}'),
('Quadrilatères classement', 1, 15000, 'Un carré est un cas particulier de rectangle (tous les côtés égaux ET angles droits).',
 '{"type":"mcq","question":"Lequel de ces énoncés est vrai ?","options":["Tout carré est un rectangle","Tout rectangle est un carré","Un losange est un carré","Un carré n''est pas un polygone"],"answer":"Tout carré est un rectangle"}'),
('Axe de symétrie', 1, 20000, 'Un carré a 4 axes de symétrie (2 diagonales et 2 médianes).',
 '{"type":"mcq","question":"Combien d''axes de symétrie a un carré ?","options":["1","2","4","8"],"answer":"4"}'),
('Polygone nombre côtés', 1, 15000, 'Un hexagone a 6 côtés. Hex = 6 en grec.',
 '{"type":"mcq","question":"Combien de côtés a un hexagone ?","options":["4","5","6","8"],"answer":"6"}'),
('Angle aigu', 1, 15000, 'Un angle aigu est plus petit que 90°.',
 '{"type":"mcq","question":"Lequel est un angle aigu ?","options":["90°","95°","130°","45°"],"answer":"45°"}'),
('Angles complémentaires', 1, 20000, 'Deux angles complémentaires ont une somme de 90°. Si un angle = 35°, l''autre = 90 - 35 = 55°.',
 '{"type":"mcq","question":"Deux angles sont complémentaires. L''un mesure 35°. Quel est l''autre ?","options":["45°","55°","65°","145°"],"answer":"55°"}'),
('Angles supplémentaires', 1, 20000, 'Deux angles supplémentaires ont une somme de 180°. Si un angle = 110°, l''autre = 180 - 110 = 70°.',
 '{"type":"mcq","question":"Deux angles sont supplémentaires. L''un mesure 110°. Quel est l''autre ?","options":["50°","60°","70°","80°"],"answer":"70°"}'),
('Diagonales rectangle', 1, 20000, 'Un rectangle a 2 diagonales qui se coupent en leur milieu et sont de longueur égale.',
 '{"type":"mcq","question":"Combien de diagonales a un rectangle ?","options":["0","1","2","4"],"answer":"2"}'),
('Volume cube', 1, 25000, 'Volume d''un cube = côté³ = 3³ = 27 cm³.',
 '{"type":"mcq","question":"Quel est le volume d''un cube de côté 3 cm ?","options":["9 cm³","18 cm³","27 cm³","81 cm³"],"answer":"27 cm³"}'),
('Volume prisme rectangulaire', 1, 25000, 'Volume = longueur × largeur × hauteur = 5 × 4 × 3 = 60 cm³.',
 '{"type":"mcq","question":"Quel est le volume d''un prisme rectangulaire de 5 cm × 4 cm × 3 cm ?","options":["48 cm³","60 cm³","72 cm³","120 cm³"],"answer":"60 cm³"}'),
('Angle obtus', 1, 15000, 'Un angle obtus est compris entre 90° et 180°.',
 '{"type":"mcq","question":"Lequel est un angle obtus ?","options":["45°","88°","90°","120°"],"answer":"120°"}'),
('Périmètre triangle', 1, 20000, 'Périmètre = somme de tous les côtés = 5 + 7 + 9 = 21 cm.',
 '{"type":"mcq","question":"Quel est le périmètre d''un triangle dont les côtés mesurent 5 cm, 7 cm et 9 cm ?","options":["19 cm","21 cm","23 cm","25 cm"],"answer":"21 cm"}'),
('Aire parallélogramme', 1, 25000, 'Aire parallélogramme = base × hauteur = 8 × 5 = 40 cm².',
 '{"type":"mcq","question":"Quelle est l''aire d''un parallélogramme de base 8 cm et hauteur 5 cm ?","options":["26 cm²","32 cm²","40 cm²","80 cm²"],"answer":"40 cm²"}'),
('Aire trapèze', 1, 30000, 'Aire trapèze = (grande base + petite base) × hauteur ÷ 2 = (10 + 6) × 4 ÷ 2 = 32 cm².',
 '{"type":"mcq","question":"Quelle est l''aire d''un trapèze de bases 10 cm et 6 cm, et hauteur 4 cm ?","options":["24 cm²","32 cm²","40 cm²","64 cm²"],"answer":"32 cm²"}'),
('Angles alternes internes', 1, 25000, 'Quand deux droites parallèles sont coupées par une sécante, les angles alternes-internes sont égaux.',
 '{"type":"mcq","question":"Si deux droites parallèles sont coupées par une transversale, les angles alternes-internes sont...","options":["complémentaires","supplémentaires","égaux","différents"],"answer":"égaux"}'),
('Rotation centre', 1, 20000, 'Une rotation de 360° ramène la figure à sa position initiale.',
 '{"type":"mcq","question":"Une rotation de 360° autour d''un point résulte en...","options":["une translation","un retour à la position initiale","une réflexion","un agrandissement"],"answer":"un retour à la position initiale"}'),
('Identifier losange', 1, 15000, 'Un losange est un quadrilatère dont les 4 côtés sont égaux.',
 '{"type":"mcq","question":"Lequel a tous ses côtés égaux mais pas nécessairement des angles droits ?","options":["Rectangle","Trapèze","Losange","Pentagone"],"answer":"Losange"}'),
('Théorème Pythagore', 2, 40000, 'Dans un triangle rectangle, c² = a² + b². c² = 3² + 4² = 9 + 16 = 25. c = 5 cm.',
 '{"type":"mcq","question":"Dans un triangle rectangle, les deux cathètes mesurent 3 cm et 4 cm. Quelle est la longueur de l''hypoténuse ?","options":["5 cm","6 cm","7 cm","12 cm"],"answer":"5 cm"}'),
('Pythagore inverse', 2, 40000, 'Si c = 13 et a = 5 : b² = 13² - 5² = 169 - 25 = 144. b = 12 cm.',
 '{"type":"mcq","question":"Dans un triangle rectangle, l''hypoténuse est 13 cm et une cathète est 5 cm. Quelle est l''autre cathète ?","options":["8 cm","10 cm","12 cm","14 cm"],"answer":"12 cm"}'),
('Périmètre figure composée', 2, 40000, 'Figure en L : périmètre = 6 + 2 + 2 + 4 + 4 + 6 = 24 cm (en comptant tous les côtés extérieurs).',
 '{"type":"mcq","question":"Un terrain en L a des côtés de 6m, 2m, 2m, 4m, 4m, 6m (dans l''ordre). Quel est son périmètre ?","options":["20 m","22 m","24 m","26 m"],"answer":"24 m"}'),
('Aire figure composée', 2, 40000, 'Rectangle total : 10 × 6 = 60 cm². Moins le coin coupé (3 × 2 = 6 cm²). Aire = 60 - 6 = 54 cm².',
 '{"type":"mcq","question":"Une pièce rectangulaire de 10 cm × 6 cm a un coin coupé formant un rectangle de 3 cm × 2 cm. Quelle est son aire ?","options":["48 cm²","54 cm²","56 cm²","60 cm²"],"answer":"54 cm²"}'),
('Angle manquant quadrilatère', 2, 35000, 'Somme des angles d''un quadrilatère = 360°. Angle manquant = 360 - 80 - 110 - 95 = 75°.',
 '{"type":"mcq","question":"Un quadrilatère a des angles de 80°, 110° et 95°. Quel est le 4e angle ?","options":["70°","75°","85°","95°"],"answer":"75°"}'),
('Surface totale cube', 2, 35000, 'Surface totale d''un cube = 6 × côté² = 6 × 4² = 6 × 16 = 96 cm².',
 '{"type":"mcq","question":"Quelle est la surface totale d''un cube de côté 4 cm ?","options":["48 cm²","64 cm²","96 cm²","192 cm²"],"answer":"96 cm²"}'),
('Surface totale prisme', 2, 40000, 'Prisme rectangulaire 5×3×2 : Surface = 2(5×3 + 5×2 + 3×2) = 2(15+10+6) = 2×31 = 62 cm².',
 '{"type":"mcq","question":"Quelle est la surface totale d''un prisme rectangulaire de 5 cm × 3 cm × 2 cm ?","options":["30 cm²","52 cm²","62 cm²","86 cm²"],"answer":"62 cm²"}'),
('Rapport de similitude', 2, 40000, 'Si le rapport est 2:1, toutes les longueurs sont doublées. Côté original : 4 cm → côté agrandi : 8 cm.',
 '{"type":"mcq","question":"Deux figures sont semblables avec un rapport 2:1. Si un côté de la petite figure mesure 4 cm, quelle est la mesure du côté correspondant dans la grande ?","options":["2 cm","4 cm","6 cm","8 cm"],"answer":"8 cm"}'),
('Angle inscrit cercle', 2, 40000, 'Un angle inscrit vaut la moitié de l''arc qu''il intercepte. Si l''arc = 80°, l''angle inscrit = 40°.',
 '{"type":"mcq","question":"Un angle inscrit dans un cercle intercepte un arc de 80°. Quelle est la mesure de l''angle ?","options":["20°","40°","80°","160°"],"answer":"40°"}'),
('Réflexion axe', 2, 35000, 'Lors d''une réflexion, le point (3, 2) devient (-3, 2) par rapport à l''axe des y.',
 '{"type":"mcq","question":"Quel est l''image du point (3, 2) après une réflexion par rapport à l''axe des y ?","options":["(3, -2)","(-3, 2)","(-3, -2)","(2, 3)"],"answer":"(-3, 2)"}'),
('Translation vecteur', 2, 35000, 'Le point (2, 3) translaté par (4, -1) devient (2+4, 3-1) = (6, 2).',
 '{"type":"mcq","question":"Le point (2, 3) est translaté par le vecteur (4, -1). Quelles sont les coordonnées du point image ?","options":["(6, 4)","(6, 2)","(-2, 4)","(8, -3)"],"answer":"(6, 2)"}'),
('Rotation 90 degrés', 2, 40000, 'Une rotation de 90° dans le sens antihoraire transforme (x, y) en (-y, x). (3, 1) → (-1, 3).',
 '{"type":"mcq","question":"Le point (3, 1) subit une rotation de 90° dans le sens antihoraire autour de l''origine. Quel est le point image ?","options":["(-1, 3)","(1, -3)","(-3, -1)","(3, -1)"],"answer":"(-1, 3)"}'),
('Aire anneau circulaire', 2, 40000, 'Aire anneau = π×R² - π×r² = π(5² - 3²) = π×16 ≈ 50,3 cm².',
 '{"type":"mcq","question":"Quelle est l''aire de la région entre deux cercles concentriques de rayons 5 cm et 3 cm ? (π ≈ 3,14)","options":["25,1 cm²","50,3 cm²","62,8 cm²","78,5 cm²"],"answer":"50,3 cm²"}'),
('Angles vertically opposite', 2, 30000, 'Les angles opposés par le sommet sont égaux. Si un angle = 65°, l''angle opposé = 65° aussi.',
 '{"type":"mcq","question":"Deux droites se croisent. Un des angles formés mesure 65°. Quel est l''angle opposé par le sommet ?","options":["25°","65°","115°","180°"],"answer":"65°"}'),
('Diagonale rectangle longueur', 2, 40000, 'd² = 6² + 8² = 36 + 64 = 100. d = 10 cm.',
 '{"type":"mcq","question":"Un rectangle mesure 6 cm × 8 cm. Quelle est la longueur de sa diagonale ?","options":["7 cm","9 cm","10 cm","14 cm"],"answer":"10 cm"}'),
('Agrandissement aire', 2, 40000, 'Si le rapport de similitude est k, les aires sont multipliées par k². k=3 → aire × 9.',
 '{"type":"mcq","question":"On agrandit une figure par un rapport 3. Par combien est multipliée son aire ?","options":["3","6","9","12"],"answer":"9"}'),
('Somme angles polygone', 2, 35000, 'Somme des angles d''un polygone à n côtés = (n-2) × 180°. Pentagone : (5-2)×180 = 540°.',
 '{"type":"mcq","question":"Quelle est la somme des angles intérieurs d''un pentagone ?","options":["360°","450°","540°","720°"],"answer":"540°"}'),
('Angle intérieur polygone régulier', 2, 35000, 'Hexagone régulier : somme = (6-2)×180 = 720°. Chaque angle = 720÷6 = 120°.',
 '{"type":"mcq","question":"Quelle est la mesure de chaque angle intérieur d''un hexagone régulier ?","options":["90°","108°","120°","135°"],"answer":"120°"}'),
('Volume pyramide', 2, 40000, 'Volume pyramide = (1/3) × Aire base × hauteur = (1/3) × (6×6) × 4 = (1/3) × 36 × 4 = 48 cm³.',
 '{"type":"mcq","question":"Quel est le volume d''une pyramide à base carrée de côté 6 cm et hauteur 4 cm ?","options":["36 cm³","48 cm³","72 cm³","144 cm³"],"answer":"48 cm³"}'),
('Volume cylindre', 2, 40000, 'Volume cylindre = π × r² × h ≈ 3,14 × 3² × 10 = 3,14 × 9 × 10 ≈ 282,6 cm³.',
 '{"type":"mcq","question":"Quel est le volume d''un cylindre de rayon 3 cm et hauteur 10 cm ? (π ≈ 3,14)","options":["94,2 cm³","188,4 cm³","282,6 cm³","565,2 cm³"],"answer":"282,6 cm³"}'),
('Repère cartésien quadrant', 2, 25000, 'Le point (-3, 5) est dans le 2e quadrant (x négatif, y positif).',
 '{"type":"mcq","question":"Dans quel quadrant se trouve le point (-3, 5) ?","options":["1er","2e","3e","4e"],"answer":"2e"}'),
('Distance entre deux points', 2, 40000, 'd = √((5-1)² + (7-4)²) = √(16+9) = √25 = 5 unités.',
 '{"type":"mcq","question":"Quelle est la distance entre les points (1, 4) et (5, 7) ?","options":["3","4","5","7"],"answer":"5"}'),
('Médiatrice segment', 2, 35000, 'La médiatrice est perpendiculaire au segment et passe par son milieu. Milieu de AB = ((1+5)/2, (2+6)/2) = (3, 4).',
 '{"type":"mcq","question":"Quel est le milieu du segment AB avec A(1,2) et B(5,6) ?","options":["(3, 4)","(4, 8)","(2, 4)","(6, 8)"],"answer":"(3, 4)"}'),
('Aire losange', 2, 35000, 'Aire losange = (diagonale 1 × diagonale 2) ÷ 2 = (8 × 6) ÷ 2 = 24 cm².',
 '{"type":"mcq","question":"Quelle est l''aire d''un losange dont les diagonales mesurent 8 cm et 6 cm ?","options":["12 cm²","24 cm²","48 cm²","14 cm²"],"answer":"24 cm²"}'),
('Angle co-internes', 2, 35000, 'Les angles co-internes (du même côté de la transversale) sont supplémentaires : 60° + 120° = 180°.',
 '{"type":"mcq","question":"Deux droites parallèles sont coupées par une transversale. Un angle co-interne mesure 60°. Quel est l''autre angle co-interne ?","options":["60°","90°","120°","180°"],"answer":"120°"}'),
('Symétrie centrale', 2, 35000, 'La symétrie centrale par rapport à l''origine transforme (x, y) en (-x, -y). (4, -3) → (-4, 3).',
 '{"type":"mcq","question":"Quelle est l''image du point (4, -3) par une symétrie centrale par rapport à l''origine ?","options":["(-4, 3)","(4, 3)","(-4, -3)","(3, -4)"],"answer":"(-4, 3)"}'),
('Apothème polygone régulier', 2, 40000, 'L''apothème est la distance du centre au milieu d''un côté. Aire hexagone régulier = (périmètre × apothème) / 2.',
 '{"type":"mcq","question":"Un hexagone régulier a un côté de 6 cm et un apothème de 5,2 cm. Quelle est son aire approximative ?","options":["78 cm²","93,6 cm²","104 cm²","140 cm²"],"answer":"93,6 cm²"}'),
('Pythagore problème complexe', 3, 55000, 'Hauteur² = 10² - 6² = 100 - 36 = 64. Hauteur = 8 m. Aire = (12 × 8) ÷ 2 = 48 m².',
 '{"type":"mcq","question":"Un triangle isocèle a une base de 12 m et des côtés égaux de 10 m. Quelle est son aire ?","options":["40 m²","48 m²","60 m²","72 m²"],"answer":"48 m²"}'),
('Problème surface peindre', 3, 55000, 'Murs : 2×(10×3) + 2×(8×3) = 60+48 = 108 m². Plafond : 10×8 = 80 m². Total : 188 m². 2 couches : 376 m². Bidons : 376÷15 ≈ 25,1 → 26 bidons.',
 '{"type":"mcq","question":"Une pièce de 10 m × 8 m × 3 m doit être peinte (murs et plafond, 2 couches). Un bidon couvre 15 m². Combien de bidons faut-il ?","options":["24","25","26","27"],"answer":"26"}'),
('Rapport similitude aire', 3, 50000, 'Rapport de similitude k = 5/3. Les aires sont multipliées par k² = 25/9. Aire grande = 36 × 25/9 = 100 cm².',
 '{"type":"mcq","question":"Deux triangles semblables ont leurs côtés dans un rapport 5:3. Le petit triangle a une aire de 36 cm². Quelle est l''aire du grand ?","options":["60 cm²","80 cm²","100 cm²","120 cm²"],"answer":"100 cm²"}'),
('Volume cône', 3, 50000, 'Volume cône = (1/3) × π × r² × h = (1/3) × 3,14 × 4² × 9 = (1/3) × 3,14 × 16 × 9 ≈ 150,7 cm³.',
 '{"type":"mcq","question":"Quel est le volume d''un cône de rayon 4 cm et hauteur 9 cm ? (π ≈ 3,14)","options":["113 cm³","150,7 cm³","301 cm³","452 cm³"],"answer":"150,7 cm³"}'),
('Volume sphère', 3, 50000, 'Volume sphère = (4/3) × π × r³ = (4/3) × 3,14 × 3³ = (4/3) × 3,14 × 27 ≈ 113 cm³.',
 '{"type":"mcq","question":"Quel est le volume approximatif d''une sphère de rayon 3 cm ? (π ≈ 3,14)","options":["37,7 cm³","113 cm³","339 cm³","904 cm³"],"answer":"113 cm³"}'),
('Transformation composée', 3, 55000, 'Réflexion de (3,-2) sur l''axe x → (3,2). Puis translation (−4, 5) → (3-4, 2+5) = (-1, 7).',
 '{"type":"mcq","question":"Le point (3, -2) subit une réflexion par rapport à l''axe des x, puis une translation de vecteur (-4, 5). Quel est le point final ?","options":["(-1, 7)","(-1, -7)","(7, -1)","(-7, 1)"],"answer":"(-1, 7)"}'),
('Problème diagonales', 3, 50000, 'Diagonal d''un prisme rectangulaire = √(l²+w²+h²) = √(4²+3²+12²) = √(16+9+144) = √169 = 13 cm.',
 '{"type":"mcq","question":"Quelle est la longueur de la diagonale principale d''un prisme rectangulaire de 4 cm × 3 cm × 12 cm ?","options":["11 cm","12 cm","13 cm","14 cm"],"answer":"13 cm"}'),
('Angle polygone extérieur', 3, 45000, 'La somme des angles extérieurs d''un polygone convexe est toujours 360°. Pour un octogone régulier : 360÷8 = 45°.',
 '{"type":"mcq","question":"Quelle est la mesure d''un angle extérieur d''un octogone régulier ?","options":["40°","45°","50°","55°"],"answer":"45°"}'),
('Problème coordonnées et géométrie', 3, 55000, 'A(0,0), B(4,0), C(4,3). AB=4, BC=3, AC=5 (Pythagore). Périmètre = 4+3+5 = 12 unités.',
 '{"type":"mcq","question":"Un triangle a ses sommets en A(0,0), B(4,0) et C(4,3). Quel est son périmètre ?","options":["10","12","14","15"],"answer":"12"}'),
('Surface totale cylindre', 3, 50000, 'Surface = 2πr² + 2πrh = 2π×5² + 2π×5×12 = 50π + 120π = 170π ≈ 534 cm².',
 '{"type":"mcq","question":"Quelle est la surface totale d''un cylindre de rayon 5 cm et hauteur 12 cm ? (π ≈ 3,14)","options":["408 cm²","471 cm²","534 cm²","628 cm²"],"answer":"534 cm²"}'),
('Problème ombre et angle', 3, 55000, 'Ombre/hauteur = 3/2. Si l''ombre de l''arbre = 9 m : hauteur arbre = 9 × (2/3) × (hauteur poteau/ombre poteau). Hauteur poteau = 2, ombre = 3, arbre = x, ombre = 9. x/9 = 2/3. x = 6 m.',
 '{"type":"mcq","question":"Un poteau de 2 m projette une ombre de 3 m. À la même heure, un arbre projette une ombre de 9 m. Quelle est la hauteur de l''arbre ?","options":["4 m","6 m","8 m","12 m"],"answer":"6 m"}'),
('Lieu géométrique', 3, 50000, 'L''ensemble des points à égale distance de deux points A et B est la médiatrice du segment AB.',
 '{"type":"mcq","question":"Quel est l''ensemble des points équidistants de deux points A et B ?","options":["Le segment AB","La médiatrice de AB","Le cercle de centre A","La bissectrice de l''angle A"],"answer":"La médiatrice de AB"}'),
('Problème peinture cylindre', 3, 55000, 'Surface latérale = 2πrh = 2 × 3,14 × 0,5 × 2 = 6,28 m². 5 réservoirs : 5 × 6,28 = 31,4 m². Bidons : 31,4 ÷ 10 = 3,14 → 4 bidons.',
 '{"type":"mcq","question":"On peint la surface latérale de 5 réservoirs cylindriques de rayon 0,5 m et hauteur 2 m. Chaque bidon couvre 10 m². Combien de bidons faut-il ? (π ≈ 3,14)","options":["3","4","5","6"],"answer":"4"}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);


-- SEC1_MAT_geometrie_supp.sql (76 questions)
INSERT INTO questions (skill_id, title, difficulty_level, expected_time_ms, explanation, is_active, content)
SELECT
  (SELECT id FROM skills WHERE pfeq_reference = 'PFEQ-MAT-SEC1-GEO') AS skill_id,
  q.title, q.difficulty_level::int, q.expected_time_ms::int, q.explication, true, q.content::jsonb
FROM (VALUES
('Identifier un triangle selon ses côtés', 1, 20000, 'Un triangle équilatéral a ses 3 côtés égaux.',
 '{"type":"mcq","question":"Quel type de triangle possède 3 côtés de longueur égale ?","options":["Isocèle","Scalène","Équilatéral","Rectangle"],"answer":"Équilatéral"}'),
('Identifier un triangle isocèle', 1, 20000, 'Un triangle isocèle a exactement 2 côtés égaux.',
 '{"type":"mcq","question":"Un triangle a deux côtés de 5 cm et un côté de 7 cm. Quel type de triangle est-ce ?","options":["Équilatéral","Isocèle","Scalène","Rectangle"],"answer":"Isocèle"}'),
('Somme des angles d''un triangle', 1, 22000, 'La somme des angles intérieurs d''un triangle est toujours 180°.',
 '{"type":"mcq","question":"Un triangle a des angles de 60° et 80°. Quel est le troisième angle ?","options":["20°","40°","60°","80°"],"answer":"40°"}'),
('Angle droit', 1, 18000, 'Un angle droit mesure exactement 90°.',
 '{"type":"mcq","question":"Comment s''appelle un angle qui mesure 90° ?","options":["Aigu","Obtus","Droit","Plat"],"answer":"Droit"}'),
('Angle aigu', 1, 18000, 'Un angle aigu mesure entre 0° et 90°.',
 '{"type":"mcq","question":"Lequel de ces angles est un angle aigu ?","options":["95°","90°","130°","45°"],"answer":"45°"}'),
('Angle obtus', 1, 18000, 'Un angle obtus mesure entre 90° et 180°.',
 '{"type":"mcq","question":"Lequel de ces angles est un angle obtus ?","options":["45°","90°","120°","180°"],"answer":"120°"}'),
('Angles complémentaires', 1, 22000, 'Deux angles complémentaires ont une somme de 90°. Si l''un est 35°, l''autre est 55°.',
 '{"type":"mcq","question":"Deux angles sont complémentaires. L''un mesure 35°. Quel est l''autre ?","options":["35°","45°","55°","145°"],"answer":"55°"}'),
('Angles supplémentaires', 1, 22000, 'Deux angles supplémentaires ont une somme de 180°. 180° − 110° = 70°.',
 '{"type":"mcq","question":"Deux angles sont supplémentaires. L''un mesure 110°. Quel est l''autre ?","options":["70°","80°","110°","90°"],"answer":"70°"}'),
('Périmètre d''un rectangle', 1, 22000, 'P = 2l + 2w = 2(6) + 2(4) = 12 + 8 = 20 cm.',
 '{"type":"mcq","question":"Calcule le périmètre d''un rectangle de longueur 6 cm et largeur 4 cm.","options":["10 cm","20 cm","24 cm","48 cm"],"answer":"20 cm"}'),
('Périmètre d''un carré', 1, 20000, 'P = 4 × côté = 4 × 5 = 20 cm.',
 '{"type":"mcq","question":"Calcule le périmètre d''un carré de côté 5 cm.","options":["10 cm","15 cm","20 cm","25 cm"],"answer":"20 cm"}'),
('Périmètre d''un triangle équilatéral', 1, 20000, 'P = 3 × côté = 3 × 7 = 21 cm.',
 '{"type":"mcq","question":"Un triangle équilatéral a un côté de 7 cm. Quel est son périmètre ?","options":["14 cm","18 cm","21 cm","49 cm"],"answer":"21 cm"}'),
('Aire d''un carré', 1, 20000, 'A = côté² = 6² = 36 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un carré de côté 6 cm.","options":["12 cm²","24 cm²","36 cm²","66 cm²"],"answer":"36 cm²"}'),
('Aire d''un rectangle', 1, 20000, 'A = l × w = 8 × 3 = 24 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un rectangle de longueur 8 cm et largeur 3 cm.","options":["11 cm²","22 cm²","24 cm²","48 cm²"],"answer":"24 cm²"}'),
('Aire d''un triangle', 1, 22000, 'A = (base × hauteur) / 2 = (10 × 6) / 2 = 30 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un triangle de base 10 cm et hauteur 6 cm.","options":["30 cm²","60 cm²","16 cm²","32 cm²"],"answer":"30 cm²"}'),
('Identifier un quadrilatère', 1, 18000, 'Un quadrilatère est un polygone à 4 côtés.',
 '{"type":"mcq","question":"Combien de côtés possède un quadrilatère ?","options":["3","4","5","6"],"answer":"4"}'),
('Identifier un pentagone', 1, 18000, 'Un pentagone a 5 côtés.',
 '{"type":"mcq","question":"Combien de côtés possède un pentagone régulier ?","options":["4","5","6","8"],"answer":"5"}'),
('Propriété d''un parallélogramme', 1, 20000, 'Dans un parallélogramme, les côtés opposés sont parallèles et égaux.',
 '{"type":"mcq","question":"Quelle est la propriété caractéristique d''un parallélogramme ?","options":["Tous les angles sont droits","Les diagonales sont égales","Les côtés opposés sont parallèles et égaux","Tous les côtés sont égaux"],"answer":"Les côtés opposés sont parallèles et égaux"}'),
('Propriété d''un losange', 1, 20000, 'Un losange est un parallélogramme dont tous les côtés sont égaux.',
 '{"type":"mcq","question":"Qu''est-ce qui distingue un losange d''un simple parallélogramme ?","options":["Ses angles sont droits","Tous ses côtés sont égaux","Ses diagonales sont égales","Il a 5 côtés"],"answer":"Tous ses côtés sont égaux"}'),
('Droites parallèles', 1, 18000, 'Deux droites parallèles ne se croisent jamais et ont la même pente.',
 '{"type":"mcq","question":"Deux droites parallèles sont des droites qui...","options":["Se croisent à angle droit","Ne se croisent jamais","Se croisent en un point quelconque","Ont la même longueur"],"answer":"Ne se croisent jamais"}'),
('Droites perpendiculaires', 1, 18000, 'Deux droites perpendiculaires se croisent à 90°.',
 '{"type":"mcq","question":"Deux droites perpendiculaires forment un angle de...","options":["45°","60°","90°","180°"],"answer":"90°"}'),
('Rayon et diamètre d''un cercle', 1, 20000, 'Diamètre = 2 × rayon. Si rayon = 5, diamètre = 10.',
 '{"type":"mcq","question":"Un cercle a un rayon de 5 cm. Quel est son diamètre ?","options":["2,5 cm","5 cm","10 cm","25 cm"],"answer":"10 cm"}'),
('Circonférence d''un cercle (formule)', 1, 22000, 'C = πd = π × 8 ≈ 3,14 × 8 ≈ 25,12 cm.',
 '{"type":"mcq","question":"Calcule la circonférence d''un cercle de diamètre 8 cm (π ≈ 3,14).","options":["25,12 cm","50,24 cm","12,56 cm","200,96 cm"],"answer":"25,12 cm"}'),
('Aire d''un cercle', 1, 22000, 'A = πr² = π × 4² = π × 16 ≈ 50,24 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un cercle de rayon 4 cm (π ≈ 3,14).","options":["12,56 cm²","25,12 cm²","50,24 cm²","100,48 cm²"],"answer":"50,24 cm²"}'),
('Plan cartésien : identifier un point', 1, 20000, 'Le point (3, −2) est à 3 unités à droite et 2 unités en dessous de l''origine.',
 '{"type":"mcq","question":"Dans quel quadrant se trouve le point (3, −2) ?","options":["Quadrant I","Quadrant II","Quadrant III","Quadrant IV"],"answer":"Quadrant IV"}'),
('Plan cartésien : coordonnées', 1, 20000, 'L''axe des abscisses (x) est horizontal, l''axe des ordonnées (y) est vertical.',
 '{"type":"mcq","question":"Quelles sont les coordonnées de l''origine du plan cartésien ?","options":["(1, 1)","(0, 1)","(1, 0)","(0, 0)"],"answer":"(0, 0)"}'),
('Translation : image d''un point', 1, 22000, 'Translation de (2, 3) : point (4, 1) devient (4+2, 1+3) = (6, 4).',
 '{"type":"mcq","question":"On applique une translation de vecteur (2, 3) au point (4, 1). Quelles sont les coordonnées de l''image ?","options":["(6, 4)","(2, −2)","(8, 3)","(4, 4)"],"answer":"(6, 4)"}'),
('Théorème de Pythagore : trouver l''hypoténuse', 2, 35000, 'a² + b² = c². 3² + 4² = 9 + 16 = 25 = 5². Hypoténuse = 5.',
 '{"type":"mcq","question":"Un triangle rectangle a des cathètes de 3 cm et 4 cm. Quelle est la longueur de l''hypoténuse ?","options":["5 cm","6 cm","7 cm","12 cm"],"answer":"5 cm"}'),
('Théorème de Pythagore : trouver une cathète', 2, 35000, 'c² = a² + b² → a² = c² − b² = 13² − 5² = 169 − 25 = 144 → a = 12.',
 '{"type":"mcq","question":"Un triangle rectangle a une hypoténuse de 13 cm et une cathète de 5 cm. Quelle est la deuxième cathète ?","options":["8 cm","10 cm","12 cm","18 cm"],"answer":"12 cm"}'),
('Vérifier si un triangle est rectangle', 2, 35000, '6² + 8² = 36 + 64 = 100 = 10². Oui, triangle rectangle.',
 '{"type":"mcq","question":"Un triangle a des côtés de 6 cm, 8 cm et 10 cm. Est-il rectangle ?","options":["Oui","Non","Impossible à déterminer","Oui mais isocèle"],"answer":"Oui"}'),
('Angles alternes-internes', 2, 32000, 'Deux droites parallèles coupées par une transversale forment des angles alternes-internes égaux.',
 '{"type":"mcq","question":"Deux droites parallèles sont coupées par une transversale. Un angle alterne-interne mesure 65°. Quel est son correspondant alterne-interne ?","options":["25°","65°","115°","180°"],"answer":"65°"}'),
('Angles correspondants', 2, 32000, 'Deux droites parallèles coupées par une transversale : les angles correspondants sont égaux.',
 '{"type":"mcq","question":"Deux droites parallèles sont coupées par une transversale formant un angle de 75°. Quel est l''angle correspondant ?","options":["15°","75°","105°","180°"],"answer":"75°"}'),
('Angles co-internes', 2, 32000, 'Les angles co-internes (du même côté de la transversale) sont supplémentaires : somme = 180°.',
 '{"type":"mcq","question":"Un angle co-interne mesure 70° (entre deux droites parallèles). Quel est l''autre angle co-interne ?","options":["70°","80°","100°","110°"],"answer":"110°"}'),
('Aire d''un parallélogramme', 2, 30000, 'A = base × hauteur = 8 × 5 = 40 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un parallélogramme de base 8 cm et hauteur 5 cm.","options":["13 cm²","26 cm²","40 cm²","80 cm²"],"answer":"40 cm²"}'),
('Aire d''un trapèze', 2, 32000, 'A = (b₁ + b₂)/2 × h = (6 + 10)/2 × 4 = 8 × 4 = 32 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un trapèze de bases 6 cm et 10 cm, avec une hauteur de 4 cm.","options":["32 cm²","64 cm²","24 cm²","40 cm²"],"answer":"32 cm²"}'),
('Volume d''un prisme rectangulaire', 2, 32000, 'V = l × w × h = 5 × 3 × 4 = 60 cm³.',
 '{"type":"mcq","question":"Calcule le volume d''un prisme rectangulaire de longueur 5 cm, largeur 3 cm et hauteur 4 cm.","options":["12 cm³","48 cm³","60 cm³","120 cm³"],"answer":"60 cm³"}'),
('Volume d''un cube', 2, 30000, 'V = côté³ = 4³ = 64 cm³.',
 '{"type":"mcq","question":"Calcule le volume d''un cube de côté 4 cm.","options":["16 cm³","48 cm³","64 cm³","128 cm³"],"answer":"64 cm³"}'),
('Surface d''un prisme', 2, 35000, 'Aire latérale + 2 faces : 2(lb + lh + wh) = 2(15 + 20 + 12) = 2(47) = 94 cm².',
 '{"type":"mcq","question":"Calcule l''aire totale d''un prisme rectangulaire de 5 cm × 3 cm × 4 cm.","options":["60 cm²","74 cm²","94 cm²","120 cm²"],"answer":"94 cm²"}'),
('Symétrie axiale : image d''un point', 2, 32000, 'Symétrie par rapport à l''axe des y : (x, y) → (−x, y). Point (3, 2) → (−3, 2).',
 '{"type":"mcq","question":"Quel est l''image du point (3, 2) par une réflexion par rapport à l''axe des y ?","options":["(3, −2)","(−3, 2)","(−3, −2)","(2, 3)"],"answer":"(−3, 2)"}'),
('Symétrie axiale : axe des x', 2, 32000, 'Symétrie par rapport à l''axe des x : (x, y) → (x, −y). Point (4, −1) → (4, 1).',
 '{"type":"mcq","question":"Quel est l''image du point (4, −1) par une réflexion par rapport à l''axe des x ?","options":["(−4, −1)","(4, 1)","(−4, 1)","(1, −4)"],"answer":"(4, 1)"}'),
('Rotation de 90° dans le sens antihoraire', 2, 35000, 'Rotation de 90° antihoraire autour de l''origine : (x, y) → (−y, x). (3, 1) → (−1, 3).',
 '{"type":"mcq","question":"Quelle est l''image du point (3, 1) après une rotation de 90° antihoraire autour de l''origine ?","options":["(1, 3)","(−1, 3)","(−3, 1)","(3, −1)"],"answer":"(−1, 3)"}'),
('Agrandissement et réduction (homothétie)', 2, 32000, 'Facteur d''homothétie 2 : les côtés doublent, les aires quadruplent.',
 '{"type":"mcq","question":"Un carré de 3 cm de côté est agrandi par un facteur de 2. Quelle est la nouvelle aire ?","options":["18 cm²","24 cm²","36 cm²","6 cm²"],"answer":"36 cm²"}'),
('Distance entre deux points', 2, 35000, 'd = √[(x₂−x₁)² + (y₂−y₁)²] = √[(5−1)² + (7−4)²] = √[16+9] = √25 = 5.',
 '{"type":"mcq","question":"Calcule la distance entre les points (1, 4) et (5, 7).","options":["3","4","5","7"],"answer":"5"}'),
('Milieu d''un segment', 2, 32000, 'M = ((x₁+x₂)/2, (y₁+y₂)/2) = ((2+8)/2, (3+7)/2) = (5, 5).',
 '{"type":"mcq","question":"Quel est le milieu du segment joignant (2, 3) et (8, 7) ?","options":["(4, 5)","(5, 5)","(6, 4)","(3, 2)"],"answer":"(5, 5)"}'),
('Angle central dans un cercle', 2, 32000, 'L''angle inscrit est la moitié de l''angle central qui intercepte le même arc.',
 '{"type":"mcq","question":"Un angle central dans un cercle mesure 80°. Quel est l''angle inscrit qui intercepte le même arc ?","options":["40°","80°","160°","20°"],"answer":"40°"}'),
('Nombre de diagonales d''un polygone', 2, 30000, 'Nombre de diagonales = n(n−3)/2 pour un hexagone (n=6) : 6(3)/2 = 9.',
 '{"type":"mcq","question":"Combien de diagonales possède un hexagone ?","options":["6","8","9","12"],"answer":"9"}'),
('Somme des angles d''un quadrilatère', 2, 28000, 'Somme des angles intérieurs d''un quadrilatère = 360°.',
 '{"type":"mcq","question":"Quelle est la somme des angles intérieurs d''un quadrilatère ?","options":["180°","270°","360°","540°"],"answer":"360°"}'),
('Angles d''un polygone régulier', 2, 32000, 'Angle intérieur d''un polygone régulier à n côtés = 180(n−2)/n. Hexagone : 180(4)/6 = 120°.',
 '{"type":"mcq","question":"Quel est la mesure de chaque angle intérieur d''un hexagone régulier ?","options":["108°","120°","135°","144°"],"answer":"120°"}'),
('Rapport de similitude', 2, 32000, 'Si deux triangles similaires ont des côtés dans le rapport 2:3, leurs aires sont dans le rapport 4:9.',
 '{"type":"mcq","question":"Deux triangles similaires ont des côtés dans le rapport 2:3. Quel est le rapport de leurs aires ?","options":["2:3","4:6","4:9","8:27"],"answer":"4:9"}'),
('Volume d''un cylindre', 2, 35000, 'V = πr²h = π(3²)(10) = 90π ≈ 282,6 cm³.',
 '{"type":"mcq","question":"Calcule le volume d''un cylindre de rayon 3 cm et hauteur 10 cm (π ≈ 3,14).","options":["94,2 cm³","188,4 cm³","282,6 cm³","377 cm³"],"answer":"282,6 cm³"}'),
('Triangles semblables : trouver un côté', 2, 35000, 'Triangles semblables ABC et DEF. AB/DE = AC/DF → 4/6 = 6/x → x = 9.',
 '{"type":"mcq","question":"Deux triangles semblables ont des côtés correspondants : 4 cm et 6 cm. Si un autre côté du premier triangle mesure 6 cm, quel est le côté correspondant du second ?","options":["8 cm","9 cm","10 cm","12 cm"],"answer":"9 cm"}'),
('Plan cartésien : pente d''une droite', 2, 32000, 'Pente = (y₂−y₁)/(x₂−x₁) = (7−3)/(5−1) = 4/4 = 1.',
 '{"type":"mcq","question":"Quelle est la pente de la droite passant par (1, 3) et (5, 7) ?","options":["0,5","1","2","4"],"answer":"1"}'),
('Théorème de Pythagore : problème en contexte', 3, 45000, 'Un échelle de 10 m appuyée contre un mur, pied à 6 m du mur. Hauteur = √(100−36) = √64 = 8 m.',
 '{"type":"mcq","question":"Une échelle de 10 m est appuyée contre un mur. Le pied de l''échelle est à 6 m du mur. À quelle hauteur touche-t-elle le mur ?","options":["4 m","6 m","8 m","16 m"],"answer":"8 m"}'),
('Lieu géométrique', 3, 45000, 'L''ensemble des points équidistants d''un centre est un cercle.',
 '{"type":"mcq","question":"Quel est le lieu géométrique de tous les points à 5 cm d''un point fixe O ?","options":["Une droite","Un segment","Un cercle de rayon 5 cm","Un carré"],"answer":"Un cercle de rayon 5 cm"}'),
('Angle inscrit dans un demi-cercle', 3, 42000, 'Tout angle inscrit dans un demi-cercle est un angle droit (90°). Théorème de Thalès.',
 '{"type":"mcq","question":"Un angle est inscrit dans un demi-cercle (il s''appuie sur le diamètre). Quelle est sa mesure ?","options":["45°","60°","90°","180°"],"answer":"90°"}'),
('Volume d''une pyramide', 3, 45000, 'V = (1/3) × Base × hauteur = (1/3) × 36 × 12 = 144 cm³.',
 '{"type":"mcq","question":"Calcule le volume d''une pyramide à base carrée de côté 6 cm et hauteur 12 cm.","options":["72 cm³","144 cm³","216 cm³","432 cm³"],"answer":"144 cm³"}'),
('Volume d''un cône', 3, 45000, 'V = (1/3)πr²h = (1/3) × 3,14 × 4² × 9 = (1/3) × 3,14 × 144 = 150,72 cm³.',
 '{"type":"mcq","question":"Calcule le volume d''un cône de rayon 4 cm et hauteur 9 cm (π ≈ 3,14).","options":["150,72 cm³","452,16 cm³","75,36 cm³","301,44 cm³"],"answer":"150,72 cm³"}'),
('Déplacement composé de transformations', 3, 45000, 'Translation (3,1) puis réflexion sur l''axe des y : A(2,4) → A1(5,5) → A2(-5,5).',
 '{"type":"mcq","question":"Le point A(2, 4) subit d''abord une translation de vecteur (3, 1), puis une réflexion par rapport à l''axe des y. Quelles sont les coordonnées finales ?","options":["(5, 5)","(−5, 5)","(−5, −5)","(5, −5)"],"answer":"(−5, 5)"}'),
('Équation d''un cercle', 3, 45000, 'Équation : (x−h)² + (y−k)² = r². Centre (2, 3), rayon 5 : (x−2)² + (y−3)² = 25.',
 '{"type":"mcq","question":"Quelle est l''équation d''un cercle de centre (2, 3) et de rayon 5 ?","options":["x² + y² = 25","(x+2)² + (y+3)² = 25","(x−2)² + (y−3)² = 25","(x−2)² + (y−3)² = 5"],"answer":"(x−2)² + (y−3)² = 25"}'),
('Angle extérieur d''un triangle', 3, 42000, 'L''angle extérieur = somme des deux angles non-adjacents. 60° + 70° = 130°.',
 '{"type":"mcq","question":"Un triangle a des angles intérieurs de 60° et 70°. Quel est l''angle extérieur adjacent au troisième angle intérieur ?","options":["50°","130°","110°","120°"],"answer":"130°"}'),
('Démonstration par Pythagore inversé', 3, 45000, 'Si a² + b² = c², le triangle est rectangle. 5² + 12² = 25 + 144 = 169 = 13². Oui.',
 '{"type":"mcq","question":"Lesquels de ces côtés forment un triangle rectangle ? 5, 12, 13","options":["Oui, car 5² + 12² = 13²","Non, car ce ne sont pas des entiers consécutifs","Non, le plus grand côté n''est pas la somme des deux autres","Impossible à dire"],"answer":"Oui, car 5² + 12² = 13²"}'),
('Trigonométrie : rapport sinus', 3, 45000, 'sin(angle) = côté opposé / hypoténuse. sin(30°) = 1/2.',
 '{"type":"mcq","question":"Dans un triangle rectangle, l''angle A mesure 30°. Quel est le rapport sin(A) ?","options":["√3/2","1/2","√2/2","1/√3"],"answer":"1/2"}'),
('Trigonométrie : trouver un côté', 3, 45000, 'cos(60°) = adjacent/hypoténuse = x/10 → x = 10 × 0,5 = 5.',
 '{"type":"mcq","question":"Dans un triangle rectangle, l''angle est de 60° et l''hypoténuse est de 10 cm. Quel est le côté adjacent ? (cos 60° = 0,5)","options":["5 cm","7,07 cm","8,66 cm","10 cm"],"answer":"5 cm"}'),
('Homothétie : trouver le centre', 3, 45000, 'Pour une homothétie de rapport 2 avec centre C, l''image A'' de A est telle que CA'' = 2×CA.',
 '{"type":"mcq","question":"Par une homothétie de rapport 2 centrée en C(0,0), quelle est l''image du point A(3, 4) ?","options":["(6, 8)","(3, 4)","(1,5, 2)","(−6, −8)"],"answer":"(6, 8)"}'),
('Angle formé par deux droites sécantes', 3, 42000, 'Deux droites se croisent en formant 4 angles. Les angles opposés sont égaux. Si un angle est 65°, l''opposé est 65° et les deux autres sont 115°.',
 '{"type":"mcq","question":"Deux droites se croisent en formant un angle de 65°. Quelle est la mesure de l''angle adjacent à cet angle ?","options":["25°","65°","115°","90°"],"answer":"115°"}'),
('Périmètre d''un secteur circulaire', 3, 45000, 'Arc + 2 rayons. Arc = (90/360) × 2πr = (1/4) × 2π × 6 = 3π ≈ 9,42. Périmètre = 9,42 + 12 = 21,42 cm.',
 '{"type":"mcq","question":"Calcule le périmètre d''un secteur circulaire de rayon 6 cm et d''angle 90° (π ≈ 3,14).","options":["21,42 cm","18,84 cm","24,28 cm","12 cm"],"answer":"21,42 cm"}'),
('Aire d''un secteur circulaire', 3, 45000, 'A = (θ/360°) × πr² = (90/360) × π × 5² = (1/4) × 78,5 = 19,625 cm².',
 '{"type":"mcq","question":"Calcule l''aire d''un secteur de rayon 5 cm et angle 90° (π ≈ 3,14).","options":["19,63 cm²","39,25 cm²","78,5 cm²","15,7 cm²"],"answer":"19,63 cm²"}'),
('Triangles semblables : problème de mesure indirecte', 3, 45000, 'Ombre poteau / ombre bâton = hauteur poteau / hauteur bâton. 12/2 = h/1,5 → h = 9 m.',
 '{"type":"mcq","question":"Un bâton de 1,5 m projette une ombre de 2 m. Un poteau projette une ombre de 12 m. Quelle est la hauteur du poteau ?","options":["6 m","9 m","12 m","18 m"],"answer":"9 m"}'),
('Surface totale d''un cylindre', 3, 45000, 'S = 2πr² + 2πrh = 2π(3²) + 2π(3)(10) = 18π + 60π = 78π ≈ 244,92 cm².',
 '{"type":"mcq","question":"Calcule la surface totale d''un cylindre de rayon 3 cm et hauteur 10 cm (π ≈ 3,14).","options":["188,4 cm²","244,92 cm²","282,6 cm²","376,8 cm²"],"answer":"244,92 cm²"}'),
('Coordonnées après rotation de 180°', 3, 42000, 'Rotation de 180° autour de l''origine : (x, y) → (−x, −y). (4, −3) → (−4, 3).',
 '{"type":"mcq","question":"Quel est l''image du point (4, −3) après une rotation de 180° autour de l''origine ?","options":["(3, −4)","(−4, 3)","(−4, −3)","(4, 3)"],"answer":"(−4, 3)"}'),
('Perpendiculaire à mi-chemin', 3, 45000, 'La médiatrice d''un segment passe par son milieu et lui est perpendiculaire.',
 '{"type":"mcq","question":"Que caractérise la médiatrice d''un segment ?","options":["Elle passe par les extrémités","Elle coupe le segment en son milieu et lui est perpendiculaire","Elle est parallèle au segment","Elle coupe le segment en 3 parties égales"],"answer":"Elle coupe le segment en son milieu et lui est perpendiculaire"}'),
('Angle entre une tangente et un rayon', 3, 42000, 'La tangente à un cercle est perpendiculaire au rayon au point de contact : angle = 90°.',
 '{"type":"mcq","question":"Quel est l''angle entre une tangente à un cercle et le rayon au point de tangence ?","options":["45°","60°","90°","180°"],"answer":"90°"}'),
('Problème de toit (Pythagore appliqué)', 3, 45000, 'Demi-largeur = 4 m, hauteur = 3 m. Côté du toit = √(4² + 3²) = √25 = 5 m. Total = 10 m.',
 '{"type":"mcq","question":"Un toit a la forme d''un triangle isocèle de 8 m de base et 3 m de hauteur. Quelle est la longueur totale des deux versants du toit ?","options":["8 m","10 m","11 m","14 m"],"answer":"10 m"}'),
('Périmètre d''une figure composite', 3, 45000, 'Figure = rectangle + demi-cercle. P = 2l + w + πr (la longueur avec arc). l=10, w=6, r=3. P = 20+6+3π ≈ 35,42.',
 '{"type":"mcq","question":"Une figure est formée d''un rectangle de 10 cm × 6 cm avec un demi-cercle de rayon 3 cm sur un côté de 6 cm. Quel est son périmètre (π ≈ 3,14) ?","options":["35,42 cm","38,42 cm","41,42 cm","32 cm"],"answer":"35,42 cm"}'),
('Construire un triangle à partir de données', 3, 42000, 'Pour deux côtés et l''angle inclus (SAS), un unique triangle est déterminé.',
 '{"type":"mcq","question":"Deux côtés et l''angle qu''ils forment (SAS) permettent de construire...","options":["Aucun triangle","Un seul triangle","Deux triangles différents","Une infinité de triangles"],"answer":"Un seul triangle"}'),
('Théorème de Thalès : proportion', 3, 45000, 'AB // DE, avec A,D sur un côté et B,E sur l''autre d''un triangle. CA/CD = CB/CE. CA=4, CD=6, CB=6, CE=x → x = 9.',
 '{"type":"mcq","question":"Dans un triangle, une parallèle à la base coupe les deux côtés. Les segments créés sont CA=4, CD=6, CB=6. Quelle est la valeur de CE ?","options":["8","9","10","12"],"answer":"9"}'),
('Formule de l''aire d''un polygone régulier', 3, 45000, 'A = (périmètre × apothème) / 2. Hexagone de côté 4 : P=24, apothème ≈ 3,46. A = 24×3,46/2 ≈ 41,57.',
 '{"type":"mcq","question":"L''apothème d''un hexagone régulier de côté 4 cm mesure environ 3,46 cm. Quelle est son aire approximative ?","options":["41,52 cm²","48 cm²","24 cm²","83,04 cm²"],"answer":"41,52 cm²"}')
) AS q(title, difficulty_level, expected_time_ms, explication, content);

COMMIT;
-- Total : 150 questions pour MAT_geometrie
